<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_biodata;
use App\Models\Master\M_mt_salary;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use PhpOffice\PhpSpreadsheet\IOFactory;
$session = session();


class Biodata_act extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/biodata_act_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $mtDept = new M_dept();
         $data['data_dept'] = $mtDept->get_dept();
         $data['actView'] = 'Master/biodata_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view($biodata_id)
     {
     	$mtBiodata = new M_mt_biodata();
          $mtDept = new M_dept();
          $data['data_dept'] = $mtDept->get_dept();
          $data['mtBiodata'] = $mtBiodata->getById($biodata_id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/biodata_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {

          $localed = 0; 
          
          if($_POST['isActive'] == "Y"){
          $localed = 1; 
          }
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");
          // $isActive = '1';
          /*$db = \Config\Database::connect('hris', false);*/
          $mtBiodata = new M_mt_biodata();
          $headerId = $mtBiodata->generateId('biodata_id')['doc_id'];
          $mtBiodata->resetValues();
          $mtBiodata->setBiodataId($headerId);
          $mtBiodata->setFullName($_POST['fullName']);
          $mtBiodata->setPlaceOfBirth($_POST['placeOfBirth']);
          $mtBiodata->setDateOfBirth($_POST['dateOfBirth']);
          $mtBiodata->setGender($_POST['gender']);
          $mtBiodata->setEthnic($_POST['ethnic']);
          $mtBiodata->setNationality($_POST['nationality']);
          $mtBiodata->setDept($_POST['dept']);
          $mtBiodata->setEmpPosition($_POST['empPosition']);
          $mtBiodata->setPlacement($_POST['placement']);
          $mtBiodata->setJoinDate($_POST['joinDate']);
          $mtBiodata->setIdCardNo($_POST['idCardNo']);
          $mtBiodata->setIdCardAddress($_POST['idCardAddress']);
          $mtBiodata->setCurrentAddress($_POST['currentAddress']);
          $mtBiodata->setReligion($_POST['religion']);
          $mtBiodata->setDrivingLicense($_POST['drivingLicense']);
          $mtBiodata->setMaritalStatus($_POST['maritalStatus']);
          $mtBiodata->setEmpHeight($_POST['empHeight']);
          $mtBiodata->setEmpWeight($_POST['empWeight']);
          $mtBiodata->setBloodType($_POST['bloodType']);
          $mtBiodata->setEmailAddress($_POST['emailAddress']);
          $mtBiodata->setTelpNo($_POST['telpNo']);
          $mtBiodata->setCellNo($_POST['cellNo']);
          $mtBiodata->setIsGlasses($_POST['isGlasses']);
          $mtBiodata->setEmpStatus($_POST['empStatus']);
          $mtBiodata->setTaxNo($_POST['taxNo']);
          $mtBiodata->setBpjsNo($_POST['bpjsNo']);
          $mtBiodata->setBpjsTkNo($_POST['bpjsTkNo']);
          $mtBiodata->setIsActive($_POST['isActive']);
          $mtBiodata->setPicInput($userId);
          $mtBiodata->setInputTime($currDateTm);/*
          $mtBiodata->setPicEdit($userId]);
          $mtBiodata->setEditTime($currDateTm);*/
          $arrayList = $mtBiodata->checkByKtp($_POST['idCardNo']);
           // dd($arrayList['id_card_no']);
          // dd($arrayList[]);
          if ($arrayList > 0) {
            $jsonStatus = ['status' => false, 'message' => 'KTP sudah terdaftar!!'];
           return json_encode($jsonStatus);
          } else {
            $jsonStatus = ['status' => true, 'message' => 'Data Berhasil Ditambahkan!!'] ;
            $mtBiodata->ins();
            return json_encode($jsonStatus);
          }
          /*echo $mtBiodata;*/
     }
     
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
          $localed = 0; 
         
          
     	 $id = $_POST['BiodataId'];
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");
     	  $mtBiodata = new M_mt_biodata();
     	  $mtBiodata->setObjectById($id);
          // $mtBiodata->setFullName($_POST['fullName']);
          $mtBiodata->setPlaceOfBirth($_POST['placeOfBirth']);
          $mtBiodata->setDateOfBirth($_POST['dateOfBirth']);
          $mtBiodata->setGender($_POST['gender']);
          $mtBiodata->setEthnic($_POST['ethnic']);
          $mtBiodata->setNationality($_POST['nationality']);
          $mtBiodata->setDept($_POST['dept']);
          //$mtBiodata->setEmpPosition($_POST['empPosition']);
          $mtBiodata->setPlacement($_POST['placement']);
          $mtBiodata->setJoinDate($_POST['joinDate']);
          $mtBiodata->setIdCardNo($_POST['idCardNo']);
          $mtBiodata->setIdCardAddress($_POST['idCardAddress']);
          $mtBiodata->setCurrentAddress($_POST['currentAddress']);
          $mtBiodata->setReligion($_POST['religion']);
          $mtBiodata->setDrivingLicense($_POST['drivingLicense']);
          $mtBiodata->setMaritalStatus($_POST['maritalStatus']);
          $mtBiodata->setEmpHeight($_POST['empHeight']);
          $mtBiodata->setEmpWeight($_POST['empWeight']);
          $mtBiodata->setBloodType($_POST['bloodType']);
          $mtBiodata->setEmailAddress($_POST['emailAddress']);
          $mtBiodata->setTelpNo($_POST['telpNo']);
          $mtBiodata->setCellNo($_POST['cellNo']);
          $mtBiodata->setIsGlasses($_POST['isGlasses']);
          $mtBiodata->setEmpStatus($_POST['empStatus']);
          $mtBiodata->setTaxNo($_POST['taxNo']);
          $mtBiodata->setBpjsNo($_POST['bpjsNo']);
          $mtBiodata->setBpjsTkNo($_POST['bpjsTkNo']);
          /*$mtBiodata->setPicInput($userId);
          $mtBiodata->setInputTime($currDateTm);*/
     	$mtBiodata->setPicEdit($userId);
     	$mtBiodata->setEditTime($currDateTm);
     	$mtBiodata->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
          $mtBiodata = new M_mt_biodata();
          $id = $_POST['id'];
          $mtBiodata->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function search($keywords)
     {
          $mtBiodata = new M_mt_biodata();
          $rs = $mtBiodata->search($keywords);
          $myData = array();
            foreach ($rs as $key => $row) 
            {
                $status = 'Non Active';
                $button = "<button class='btn btn-primary btn-xs' type='button' id='active' data-id='".$row['biodata_id']."'><i class='fa fa-check'></i> Active</button>";
                
                if ($row['is_active']) {
                    $status = 'Active';
                    $button = "<button class='btn btn-danger btn-xs' type='button' id='nonActive' data-id='".$row['biodata_id']."'><i class='fa fa-times'></i> Non Active</button>";
                }
                   $myData[] = array(
                    $row['biodata_id'],
                    $row['salary_id'], 
                    $row['full_name'],        
                    $row['dept'],
                    $row['monthly'],
                    $status,
                    $button
                );            
            }
              

            echo json_encode($myData);
     }

     public function active()
     {
        $id = $_POST['id'];
         $mtBiodata = new M_mt_biodata();
         $mtSalary = new M_mt_salary();
         $data = $mtSalary->getByBioId($id);
         $salaryId = $data['salary_id'];
         $mtBiodata->active($id);
         $mtSalary->active($salaryId);


     }

     public function nonActive()
     {
        $id = $_POST['id'];
         $mtBiodata = new M_mt_biodata();
         $mtSalary = new M_mt_salary();
         $data = $mtSalary->getByBioId($id);
         $salaryId = $data['salary_id'];
         $mtBiodata->nonActive($id);
         $mtSalary->nonActive($salaryId);
     }
 }
?>
