<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Aug 18, 2020                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_Company;

$session = session();
class Company extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/company_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/company_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view($id)
     {
     	$mtCompany = new M_Company();
          $data['mtCompany'] = $mtCompany->getById($id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/company_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function insData()
     {
          $userId = $_SESSION['tId'];
          $currDateTm = date("Y-m-d H:i:s");

          // $localed = 0; 
          
          // if($_POST['isLocal'] == "Y"){
          // $localed = 1; 
          // }

     	$mtCompany = new M_Company();
     	$mtCompany->resetValues();
     	// $mtCompany->setCompanyId($_POST['companyId']);
          $mtCompany->setCompanyCode($_POST['tCode']);
          $mtCompany->setCompanyName($_POST['tName']);
          $mtCompany->setLogo($_POST['tLogo']);
          $mtCompany->setTaxNo($_POST['tTaxNo']);
          $mtCompany->setTaxName($_POST['tTaxName']);
          $mtCompany->setAddress($_POST['tAddress']);
          $mtCompany->setPhone1($_POST['tPhone1']);
          $mtCompany->setPhone2($_POST['tPhone2']);
          $mtCompany->setPicInput($userId);
          $mtCompany->setInputTime($currDateTm);
          // $mtCompany->setPicEdit($_POST['picEdit']);
          // $mtCompany->setEditTime($_POST['editTime']);
     	$mtCompany->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function editData()
     {
     	$id            = $_POST['tId'];
          $userId        = $_SESSION['tId'];
          $currDateTm    = date("Y-m-d H:i:s");

     	$mtCompany = new M_Company();
          // $mtCompany->setCompanyId($_POST['tId']);
          $mtCompany->setCompanyCode($_POST['tCode']);
          $mtCompany->setCompanyName($_POST['tName']);
          $mtCompany->setLogo($_POST['tLogo']);
          $mtCompany->setTaxNo($_POST['tTaxNo']);
          $mtCompany->setTaxName($_POST['tTaxName']);
          $mtCompany->setAddress($_POST['tAddress']);
          $mtCompany->setPhone1($_POST['tPhone1']);
          $mtCompany->setPhone2($_POST['tPhone2']);
          $mtCompany->setPicEdit($userId);
          $mtCompany->setEditTime($currDateTm);
     	$mtCompany->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtCompany = new M_Company();
     	$id = $_POST['id'];
     	$mtCompany->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtCompany = new M_Company();
     	$rs = $mtCompany->getAll();
          // test($rs,1);
     	return json_encode($rs); 
     }
     /* END GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/company'));
            
        }
     }
    
}
?>
