<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_attendance;

class Mt_attendance extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'master/v_mt_attendance';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'master/ins_mt_attendance';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$mtAttendance = new M_mt_attendance();
          $data['mtAttendance'] = $mtAttendance->getById($att_id);
          /* ***Using Valid Path */
          $data['actView'] = 'master/upd_mt_attendance';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$mtAttendance = new M_mt_attendance();
     	$mtAttendance->resetValues();
     	$mtAttendance->setAttId($_POST['attId']);
     	$mtAttendance->setBiodataId($_POST['biodataId']);
     	$mtAttendance->setYearPeriod($_POST['yearPeriod']);
     	$mtAttendance->setMonthPeriod($_POST['monthPeriod']);
     	$mtAttendance->setDayCount($_POST['dayCount']);
     	$mtAttendance->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['attId'];
     	$mtAttendance = new M_mt_attendance();
     	$mtAttendance->setObjectById($id);
     	$mtAttendance->setAttId($_POST['attId']);
     	$mtAttendance->setBiodataId($_POST['biodataId']);
     	$mtAttendance->setYearPeriod($_POST['yearPeriod']);
     	$mtAttendance->setMonthPeriod($_POST['monthPeriod']);
     	$mtAttendance->setDayCount($_POST['dayCount']);
     	$mtAttendance->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtAttendance = new M_mt_attendance();
     	$id = $_POST['attId'];
     	$mtAttendance->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtAttendance = new M_mt_attendance();
     	$rs = $mtAttendance->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
