<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 16, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_config;

$session = session();
class Mt_config extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'master/config_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'master/config_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view($conf_id)
     {
          $mtConfig = new M_mt_config();
          $data['mtConfig'] = $mtConfig->getById($conf_id);
          /* ***Using Valid Path */
          $data['actView'] = 'master/config_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");

          $localed = 0; 
          
          if($_POST['isActive'] == "Y"){
          $localed = 1; 
          }
          $mtConfig = new M_mt_config();
          $mtConfig->resetValues();
          $mtConfig->setConfId($_POST['confId']);
          $mtConfig->setConfCode($_POST['confCode']);
          $mtConfig->setConfName($_POST['confName']);
          $mtConfig->setConfValue($_POST['confValue']);
          $mtConfig->setRemarks($_POST['remarks']);
          $mtConfig->setIsActive($localed);
          $mtConfig->setPicInput($userId);
          $mtConfig->setInputTime($currDateTm);
          $mtConfig->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");

          
          $id = $_POST['confId'];
          $mtConfig = new M_mt_config();
          $mtConfig->setObjectById($id);
          $mtConfig->setConfId($_POST['confId']);
          $mtConfig->setConfCode($_POST['confCode']);
          $mtConfig->setConfName($_POST['confName']);
          $mtConfig->setConfValue($_POST['confValue']);
          $mtConfig->setRemarks($_POST['remarks']);
          $mtConfig->setPicEdit($userId);
          $mtConfig->setEditTime($currDateTm);
          $mtConfig->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
          $mtConfig = new M_mt_config();
          $id = $_POST['id'];
          $mtConfig->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
          $mtConfig = new M_mt_config();
          $rs = $mtConfig->getAll();
          return json_encode($rs); 
     }
     /* END GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/mt_config'));
            
        }
     }
}
?>
