<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Sep 03, 2020                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
/*********************************************************************
 * To use XSS Filter, Altering                                       *
 * your application/config/autoload.php file in the following way:   *
 * $autoload['helper']=array('security');                            *
 * Example : $data = $this->security->xss_clean($data);              *
 *********************************************************************/
use App\Controllers\BaseController;
use App\Models\Master\M_statutory_date;

$session = session();
class Mt_st_date extends BaseController
{
     /* START CONSTRUCTOR */
     // public function __construct()
     // {
     // 	parent::__construct();
     // 	$this->load->helper('security');
     // 	$this->load->model('M_mst_process_closing');
     // }
     /* END CONSTRUCTOR */
     /* START INDEX FUNCTION */
     public function index()
     {
         $data['actView'] = 'Master/st_date_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         // $mtBiodata = new M_biodata_01();
         $mtStatutory   = new M_statutory_date();
         // $data['data_biodata'] = $mtBiodata->get_biodata();
         
         $data['actView'] = 'Master/st_date_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START INSERT */
     public function insData()
     {
          // $userId = $_SESSION['uId'];
          // $currDateTm = date("Y-m-d H:i:s");

          $mtStatutory = new M_statutory_date();

          $headerId    = $mtStatutory->generateId('msd_id')['doc_id'];

          $mtStatutory->resetValues();
          $mtStatutory->setMsdId($headerId);
          $mtStatutory->setMsdDate($_POST['msdDate']);
          $mtStatutory->setMsdMonth($_POST['msdMonth']);
          $mtStatutory->setRemarks($_POST['remarks']);
          // $mtStatutory->setInputTime($currDateTm);
          // $mtStatutory->setPicInput($userId);
          $mtStatutory->ins();
     }
     /* END INSERT*/
     /* START UPDATE FUNCTION */
     public function upd_view($msd_id)
     {
          $mtStatutory     = new M_statutory_date();
          $data['stDate']  = $mtStatutory->getById($msd_id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/st_date_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START UPDATE */
     public function editData()
     {

          $id = $_POST['msdId'];

          $mtStatutory = new M_statutory_date();
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");

          // $isActived = '1'; 
          
          // if($_POST['isActive'] == "Y"){
          // $isActived = 0; 
          // }
          // else if($_POST['isLocal'] == "T"){
          // $localed = 0; 
          // }

          $mtStatutory->setObjectById($id);
          $mtStatutory->setMsdId($_POST['msdId']);
          $mtStatutory->setMsdDate($_POST['msdDate']);
          $mtStatutory->setMsdMonth($_POST['msdMonth']);
          $mtStatutory->setRemarks($_POST['remarks']);
          $mtStatutory->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
          $mtStatutory = new M_statutory_date();
          $id = $_POST['id'];
          $mtStatutory->del($id);
     }
     /* END DELETE */
      /* START GET ALL */
     public function getAll()
     {
          $mtStatutory = new M_statutory_date();
          $rs = $mtStatutory->getAll();
          return json_encode($rs); 
     }
     /* END GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/mt_st_date'));
            
        }
     }
}
?>
