<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Aug 06, 2020                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
/*********************************************************************
 * To use XSS Filter, Altering                                       *
 * your application/config/autoload.php file in the following way:   *
 * $autoload['helper']=array('security');                            *
 * Example : $data = $this->security->xss_clean($data);              *
 *********************************************************************/
use App\Controllers\BaseController;
use App\Models\Master\M_salary;
use App\Models\Master\M_biodata_01;
use App\Models\Master\M_class;
use App\Models\Master\M_bank;
use App\Models\Master\M_contract;

$session = session();
class Mt_salary extends BaseController
{
     /* START CONSTRUCTOR */
     // public function __construct()//eror kalau pakai ini//
     // {
     // 	parent::__construct();
     // }
     /* END CONSTRUCTOR */
     public function index()
     {    
          // echo 'hello'; exit();
          // $biodataModel = new BiodataModel();  
          // $rs = $ebiodataodel->getAll();
          // return json_encode($rs);
          $data['actView'] = 'Master/view_salary';
          return view('home', $data);   
     }

    public function ins_view()
    {
        $mtBiodata = new M_biodata_01();
        $mtClass   = new M_class();
        $mtBank   = new M_bank();
        $mtContract   = new M_contract();
        $data['data_biodata'] = $mtBiodata->get_biodata();//ambil data untuk di form input//
        $data['data_class']   = $mtClass->get_class();
        $data['data_bank_local']    = $mtBank->get_bank_local();
        $data['data_bank_foreign']    = $mtBank->get_bank_foreign();
        $data['data_contract']      = $mtContract->get_data_contract();
        // $data['data_biodata']  = $mtSalary->get_biodata();

        $data['actView'] = 'Master/ins_salary';
        return view('home', $data);     
    }
     /* START INSERT *///INSERT SALARY//
     public function insData()
     {
        $mtSalary = new M_salary();

        $userId     = $_SESSION['uId'];
        $currDateTm = date("Y-m-d H:i:s");

        $getTaxed = 0; 
          
        if($_POST['isGetTax'] == "Y"){
        $getTaxed = 1; 
        }
          
        $headerId = $mtSalary->generateId('salary_id')['doc_id'];

       	$mtSalary->resetValues();
       	$mtSalary->setSalaryId($headerId);
       	$mtSalary->setBiodataId($_POST['biodataId']);
       	$mtSalary->setClassId($_POST['classId']);
        $mtSalary->setBadgeNo($_POST['badgeNo']);
        $mtSalary->setLocalBankId($_POST['localBankId']);
        $mtSalary->setForeignBankId($_POST['foreignBankId']);
        $mtSalary->setIsEmpTrvTax($getTaxed);
        // $mtSalary->setIsActive($_POST['isActive']);
       	$mtSalary->setPicInput($userId);
       	$mtSalary->setInputTime($currDateTm);
       	$mtSalary->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function updData()
     {

      $userId     = $_SESSION['uId'];
      $currDateTm = date("Y-m-d H:i:s");

      $actived = 1; 
          
      if($_POST['isActive'] == "Y"){
      $actived = 0; 
      }

     	$id       = $_POST['salaryId'];
     	$mtSalary = new M_salary();
     	$mtSalary->setObjectById($id);
     	$mtSalary->setSalaryId($_POST['salaryId']);
     	$mtSalary->setBiodataId($_POST['biodataId']);
     	$mtSalary->setClassId($_POST['classId']);
      $mtSalary->setBadgeNo($_POST['badgeNo']);
      $mtSalary->setLocalBankId($_POST['localBankId']);
      $mtSalary->setForeignBankId($_POST['foreignBankId']);
      $mtSalary->setIsActive($actived);
     	$mtSalary->setPicEdit($userId);
     	$mtSalary->setEditTime($currDateTm);
     	$mtSalary->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtSalary = new M_salary();
     	$id = $_POST['salaryId'];
     	$mtSalary->del($id);
     }
     /* END DELETE */
     /* START GET ALL *///GET VIEW SALARY//
     public function getAll()
     {
          $mtSalary = new M_salary();
          $rs = $mtSalary->getAll();
          return json_encode($rs);
     }
     /* END GET ALL */
     /* START VIEW UPDATE */
     public function upd_view($salaryId)
     {
          
          $mtSalary  = new M_salary();
          $mtBiodata = new M_biodata_01();
          $mtClass   = new M_class();
          $mtBank   = new M_bank();

          $data['salary01']     = $mtSalary->getById($salaryId);
          $data['data_biodata'] = $mtBiodata->get_biodata();
          $data['data_class']   = $mtClass->get_class();
          $data['data_bank_local']    = $mtBank->get_bank_local();
          $data['data_bank_foreign']    = $mtBank->get_bank_foreign();

          $data['actView']      = 'Master/upd_salary';

          return view('home', $data);
     }
     /* END VIEW UPDATE */
     /*ADD MANUAL by venny*//*GET BADGE NO*/
     public function getIdNo($badgeNo)
      {
        $mtSalary = new M_salary();
        $rs = $mtSalary->getBadgeNumber();
        return json_encode($rs);
      }

     public function reset()
       {
            /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/mt_class'));
              
          }
       }



}
?>
