<?php namespace App\Models\Master; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Feb 16, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_mt_config extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = '';
     protected $table = 'mt_configuration';
     protected $primaryKey = 'conf_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $confId;
     protected $confCode;
     protected $confName;
     protected $confValue;
     protected $remarks;
     protected $isActive;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
          parent::__construct();
          $this->db = \Config\Database::connect($this->DBGroup, false);
          $this->confId = '';
          $this->confCode = '';
          $this->confName = '';
          $this->confValue = '';
          $this->remarks = '';
          $this->isActive = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setConfId($aConfId)
     {
          $this->confId = $aConfId;
     }
     public function getConfId()
     {
          return $this->confId;
     }
     public function setConfCode($aConfCode)
     {
          $this->confCode = $aConfCode;
     }
     public function getConfCode()
     {
          return $this->confCode;
     }
     public function setConfName($aConfName)
     {
          $this->confName = $aConfName;
     }
     public function getConfName()
     {
          return $this->confName;
     }
     public function setConfValue($aConfValue)
     {
          $this->confValue = $aConfValue;
     }
     public function getConfValue()
     {
          return $this->confValue;
     }
     public function setRemarks($aRemarks)
     {
          $this->remarks = $aRemarks;
     }
     public function getRemarks()
     {
          return $this->remarks;
     }
     public function setIsActive($aIsActive)
     {
          $this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
          return $this->isActive;
     }
     public function setPicInput($aPicInput)
     {
          $this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
          return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
          $this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
          return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
          $this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
          return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
          $this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
          return $this->editTime;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
          if($this->confId =="" || $this->confId == NULL) 
          {
               $this->confId = ''; 
          }
          if($this->confCode =="" || $this->confCode == NULL) 
          {
               $this->confCode = ''; 
          }
          if($this->confName =="" || $this->confName == NULL) 
          {
               $this->confName = ''; 
          }
          if($this->confValue =="" || $this->confValue == NULL) 
          {
               $this->confValue = ''; 
          }
          if($this->remarks =="" || $this->remarks == NULL) 
          {
               $this->remarks = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picInput =="" || $this->picInput == NULL) 
          {
               $this->picInput = ''; 
          }
          if($this->inputTime =="" || $this->inputTime == NULL) 
          {
               $this->inputTime = '1700-01-01 00:00:00'; 
          }
          if($this->picEdit =="" || $this->picEdit == NULL) 
          {
               $this->picEdit = ''; 
          }
          if($this->editTime =="" || $this->editTime == NULL) 
          {
               $this->editTime = '1700-01-01 00:00:00'; 
          }

          $stQuery  = "INSERT INTO ".$this->table." ";
          $stQuery .= "( ";
          $stQuery .=   "conf_id,"; 
          $stQuery .=   "conf_code,"; 
          $stQuery .=   "conf_name,"; 
          $stQuery .=   "conf_value,"; 
          $stQuery .=   "remarks,"; 
          $stQuery .=   "is_active,"; 
          $stQuery .=   "pic_input,"; 
          $stQuery .=   "input_time,"; 
          $stQuery .=   "pic_edit,"; 
          $stQuery .=   "edit_time"; 
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          $stQuery .=   "'".$this->db->escapeString($this->confId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confCode)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confValue)."',";
          $stQuery .=   "'".$this->db->escapeString($this->remarks)."',";
          $stQuery .=   " ".$this->isActive.",";
          $stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
          $stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
          $stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
          $stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
          $stQuery .= "); "; 
          $this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START QUERY INSERT */
     public function getInsQuery()
     {
          if($this->confId =="" || $this->confId == NULL) 
          {
               $this->confId = ''; 
          }
          if($this->confCode =="" || $this->confCode == NULL) 
          {
               $this->confCode = ''; 
          }
          if($this->confName =="" || $this->confName == NULL) 
          {
               $this->confName = ''; 
          }
          if($this->confValue =="" || $this->confValue == NULL) 
          {
               $this->confValue = ''; 
          }
          if($this->remarks =="" || $this->remarks == NULL) 
          {
               $this->remarks = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picInput =="" || $this->picInput == NULL) 
          {
               $this->picInput = ''; 
          }
          if($this->inputTime =="" || $this->inputTime == NULL) 
          {
               $this->inputTime = '1700-01-01 00:00:00'; 
          }
          if($this->picEdit =="" || $this->picEdit == NULL) 
          {
               $this->picEdit = ''; 
          }
          if($this->editTime =="" || $this->editTime == NULL) 
          {
               $this->editTime = '1700-01-01 00:00:00'; 
          }

          $stQuery  = "INSERT INTO ".$this->table." ";
          $stQuery .= "( ";
          $stQuery .=   "conf_id,"; 
          $stQuery .=   "conf_code,"; 
          $stQuery .=   "conf_name,"; 
          $stQuery .=   "conf_value,"; 
          $stQuery .=   "remarks,"; 
          $stQuery .=   "is_active,"; 
          $stQuery .=   "pic_input,"; 
          $stQuery .=   "input_time,"; 
          $stQuery .=   "pic_edit,"; 
          $stQuery .=   "edit_time"; 
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          $stQuery .=   "'".$this->db->escapeString($this->confId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confCode)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->confValue)."',";
          $stQuery .=   "'".$this->db->escapeString($this->remarks)."',";
          $stQuery .=   " ".$this->isActive.",";
          $stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
          $stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
          $stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
          $stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
          $stQuery .= "); "; 
          return $stQuery; 
     }
     /* END QUERY INSERT */
     /* START UPDATE */
     public function upd($id)
     {
          if($this->confId =="" || $this->confId == NULL) 
          { 
               $this->confId = ''; 
          } 
          if($this->confCode =="" || $this->confCode == NULL) 
          { 
               $this->confCode = ''; 
          } 
          if($this->confName =="" || $this->confName == NULL) 
          { 
               $this->confName = ''; 
          } 
          if($this->confValue =="" || $this->confValue == NULL) 
          { 
               $this->confValue = ''; 
          } 
          if($this->remarks =="" || $this->remarks == NULL) 
          { 
               $this->remarks = ''; 
          } 
          if($this->isActive =="" || $this->isActive == NULL) 
          { 
               $this->isActive = 0; 
          } 
          if($this->picInput =="" || $this->picInput == NULL) 
          { 
               $this->picInput = ''; 
          } 
          if($this->inputTime =="" || $this->inputTime == NULL) 
          { 
               $this->inputTime = '1700-01-01 00:00:00'; 
          } 
          if($this->picEdit =="" || $this->picEdit == NULL) 
          { 
               $this->picEdit = ''; 
          } 
          if($this->editTime =="" || $this->editTime == NULL) 
          { 
               $this->editTime = '1700-01-01 00:00:00'; 
          } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "conf_id ='".$this->db->escapeString($this->confId)."', "; 
          $stQuery .=   "conf_code ='".$this->db->escapeString($this->confCode)."', "; 
          $stQuery .=   "conf_name ='".$this->db->escapeString($this->confName)."', "; 
          $stQuery .=   "conf_value ='".$this->db->escapeString($this->confValue)."', "; 
          $stQuery .=   "remarks ='".$this->db->escapeString($this->remarks)."', "; 
          $stQuery .=   'is_active ='.$this->isActive.','; 
          $stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
          $stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
          $stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
          $stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "conf_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }
     /* END UPDATE */
     /* START QUERY UPDATE */
     public function getUpdQuery($id)
     {
          if($this->confId =="" || $this->confId == NULL) 
          { 
               $this->confId = ''; 
          } 
          if($this->confCode =="" || $this->confCode == NULL) 
          { 
               $this->confCode = ''; 
          } 
          if($this->confName =="" || $this->confName == NULL) 
          { 
               $this->confName = ''; 
          } 
          if($this->confValue =="" || $this->confValue == NULL) 
          { 
               $this->confValue = ''; 
          } 
          if($this->remarks =="" || $this->remarks == NULL) 
          { 
               $this->remarks = ''; 
          } 
          if($this->isActive =="" || $this->isActive == NULL) 
          { 
               $this->isActive = 0; 
          } 
          if($this->picInput =="" || $this->picInput == NULL) 
          { 
               $this->picInput = ''; 
          } 
          if($this->inputTime =="" || $this->inputTime == NULL) 
          { 
               $this->inputTime = '1700-01-01 00:00:00'; 
          } 
          if($this->picEdit =="" || $this->picEdit == NULL) 
          { 
               $this->picEdit = ''; 
          } 
          if($this->editTime =="" || $this->editTime == NULL) 
          { 
               $this->editTime = '1700-01-01 00:00:00'; 
          } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "conf_id ='".$this->db->escapeString($this->confId)."', "; 
          $stQuery .=   "conf_code ='".$this->db->escapeString($this->confCode)."', "; 
          $stQuery .=   "conf_name ='".$this->db->escapeString($this->confName)."', "; 
          $stQuery .=   "conf_value ='".$this->db->escapeString($this->confValue)."', "; 
          $stQuery .=   "remarks ='".$this->db->escapeString($this->remarks)."', "; 
          $stQuery .=   'is_active ='.$this->isActive.','; 
          $stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
          $stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
          $stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
          $stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "conf_id = '".$this->db->escapeString($id)."'"; 
          return $stQuery; 
     }
     /* END QUERY UPDATE */
     /* START DELETE */
     public function del($id)
     {
          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "is_active ='0'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "conf_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery);  
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
          $stQuery  = "SELECT * FROM ".$this->table." WHERE is_active='1' "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." ";     
          $stQuery .= "WHERE conf_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." "; 
          $stQuery .= "WHERE conf_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          $this->confId = $arrayRow['conf_id']; 
          $this->confCode = $arrayRow['conf_code']; 
          $this->confName = $arrayRow['conf_name']; 
          $this->confValue = $arrayRow['conf_value']; 
          $this->remarks = $arrayRow['remarks']; 
          $this->isActive = $arrayRow['is_active']; 
          $this->picInput = $arrayRow['pic_input']; 
          $this->inputTime = $arrayRow['input_time']; 
          $this->picEdit = $arrayRow['pic_edit']; 
          $this->editTime = $arrayRow['edit_time']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
          $this->confId = ''; 
          $this->confCode = ''; 
          $this->confName = ''; 
          $this->confValue = ''; 
          $this->remarks = ''; 
          $this->isActive = 0; 
          $this->picInput = ''; 
          $this->inputTime = '1700-01-01 00:00:00'; 
          $this->picEdit = ''; 
          $this->editTime = '1700-01-01 00:00:00'; 
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
          $strSql = "SELECT ";
          $strSql .= " CASE WHEN id_year = curr_ym THEN ";
          $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
          $strSql .= " ELSE ";
          $strSql .= "   CONCAT(curr_ym, '00001') ";
          $strSql .= " END AS doc_id ";
          $strSql .= "FROM ";
          $strSql .= " (SELECT ";
          $strSql .= "   MAX(".$columnId.") fi,";
          $strSql .= "   LEFT(".$columnId.",4) id_year,";
          $strSql .= "   current_date dt,";
          $strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
          $strSql .= "   CONCAT(";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
          $strSql .= "   LPAD(";
          $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
          $strSql .= "    )";
          $strSql .= "   ) curr_ym,";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
          $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
          $strSql .= " FROM ";
          $strSql .= "   ".$this->table." ";
          $strSql .= " GROUP BY ".$columnId.") a ";
          $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
          $query  = $this->db->query($strSql); 
          $arrayRow = $query->getRowArray(); 
          if(!isset($arrayRow))
          {
               $curYM = date('ym');
               $arrayRow['doc_id'] = $curYM.'00001';
          }
          return $arrayRow;
     }
     /* END OF ID GENERATOR */
      function get_config_active()
     {
        $stQuery = "SELECT conf_id, conf_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_active = '1' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     } 

     function get_config_foreign()
     {
        $stQuery = "SELECT conf_id, conf_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_active = '0' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     }
}
