<?php namespace App\Models\Master; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Jul 26, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_mt_biodata extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = 'hris';
     protected $table = 'mt_biodata_01';
     protected $primaryKey = 'biodata_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $biodataId;
     protected $fullName;
     protected $placeOfBirth;
     protected $dateOfBirth;
     protected $gender;
     protected $ethnic;
     protected $nationality;
     protected $dept;
     protected $empPosition;
     protected $passportNo;
     protected $placement;
     protected $joinDate;
     protected $idCardNo;
     protected $idCardAddress;
     protected $currentAddress;
     protected $religion;
     protected $drivingLicense;
     protected $maritalStatus;
     protected $empHeight;
     protected $empWeight;
     protected $bloodType;
     protected $emailAddress;
     protected $telpNo;
     protected $cellNo;
     protected $isGlasses;
     protected $empStatus;
     protected $taxNo;
     protected $bpjsNo;
     protected $bpjsTkNo;
     protected $isActive;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
          parent::__construct();
          $this->db = \Config\Database::connect($this->DBGroup, false);
          $this->biodataId = '';
          $this->deptId = 0;
          $this->fullName = '';
          $this->firstName = '';
          $this->middleName = '';
          $this->lastName = '';
          $this->placeOfBirth = '';
          $this->dateOfBirth = '0000-00-00';
          $this->gender = '';
          $this->ethnic = '';
          $this->nationality = '';
          $this->dept = '';
          $this->empPosition = '';
          $this->placement = '';
          $this->joinDate = '0000-00-00';
          $this->idCardNo = '';
          $this->idCardAddress = '';
          $this->currentAddress = '';
          $this->religion = '';
          $this->drivingLicense = '';
          $this->maritalStatus = '';
          $this->empHeight = 0;
          $this->empWeight = 0;
          $this->bloodType = '';
          $this->emailAddress = '';
          $this->telpNo = '';
          $this->cellNo = '';
          $this->isGlasses = 0;
          $this->empStatus = '';
          $this->taxNo = '';
          $this->bpjsNo = '';
          $this->bpjsTkNo = '';
          $this->isActive = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setBiodataId($aBiodataId)
     {
          $this->biodataId = $aBiodataId;
     }
     public function getBiodataId()
     {
          return $this->biodataId;
     }
     public function setFullName($aFullName)
     {
          $this->fullName = $aFullName;
     }
     public function getFullName()
     {
          return $this->fullName;
     }
     public function setPlaceOfBirth($aPlaceOfBirth)
     {
          $this->placeOfBirth = $aPlaceOfBirth;
     }
     public function getPlaceOfBirth()
     {
          return $this->placeOfBirth;
     }
     public function setDateOfBirth($aDateOfBirth)
     {
          $this->dateOfBirth = $aDateOfBirth;
     }
     public function getDateOfBirth()
     {
          return $this->dateOfBirth;
     }
     public function setGender($aGender)
     {
          $this->gender = $aGender;
     }
     public function getGender()
     {
          return $this->gender;
     }
     public function setEthnic($aEthnic)
     {
          $this->ethnic = $aEthnic;
     }
     public function getEthnic()
     {
          return $this->ethnic;
     }
     public function setNationality($aNationality)
     {
          $this->nationality = $aNationality;
     }
     public function getNationality()
     {
          return $this->nationality;
     }
     public function setCompany($aCompany)
     {
          $this->company = $aCompany;
     }
     public function getCompany()
     {
          return $this->company;
     }
     public function setDept($aDept)
     {
          $this->dept = $aDept;
     }
     public function getDept()
     {
          return $this->dept;
     }
     public function setEmpPosition($aEmpPosition)
     {
          $this->empPosition = $aEmpPosition;
     }
     public function getEmpPosition()
     {
          return $this->empPosition;
     }
     public function setPlacement($aPlacement)
     {
          $this->placement = $aPlacement;
     }
     public function getPlacement()
     {
          return $this->placement;
     }
     public function setJoinDate($aJoinDate)
     {
          $this->joinDate = $aJoinDate;
     }
     public function getJoinDate()
     {
          return $this->joinDate;
     }
     public function setIdCardNo($aIdCardNo)
     {
          $this->idCardNo = $aIdCardNo;
     }
     public function getIdCardNo()
     {
          return $this->idCardNo;
     }
     public function setIdCardAddress($aIdCardAddress)
     {
          $this->idCardAddress = $aIdCardAddress;
     }
     public function getIdCardAddress()
     {
          return $this->idCardAddress;
     }
     public function setCurrentAddress($aCurrentAddress)
     {
          $this->currentAddress = $aCurrentAddress;
     }
     public function getCurrentAddress()
     {
          return $this->currentAddress;
     }
     public function setReligion($aReligion)
     {
          $this->religion = $aReligion;
     }
     public function getReligion()
     {
          return $this->religion;
     }
     public function setDrivingLicense($aDrivingLicense)
     {
          $this->drivingLicense = $aDrivingLicense;
     }
     public function getDrivingLicense()
     {
          return $this->drivingLicense;
     }
     public function setMaritalStatus($aMaritalStatus)
     {
          $this->maritalStatus = $aMaritalStatus;
     }
     public function getMaritalStatus()
     {
          return $this->maritalStatus;
     }
     public function setEmpHeight($aEmpHeight)
     {
          $this->empHeight = $aEmpHeight;
     }
     public function getEmpHeight()
     {
          return $this->empHeight;
     }
     public function setEmpWeight($aEmpWeight)
     {
          $this->empWeight = $aEmpWeight;
     }
     public function getEmpWeight()
     {
          return $this->empWeight;
     }
     public function setBloodType($aBloodType)
     {
          $this->bloodType = $aBloodType;
     }
     public function getBloodType()
     {
          return $this->bloodType;
     }
     public function setEmailAddress($aEmailAddress)
     {
          $this->emailAddress = $aEmailAddress;
     }
     public function getEmailAddress()
     {
          return $this->emailAddress;
     }
     public function setTelpNo($aTelpNo)
     {
          $this->telpNo = $aTelpNo;
     }
     public function getTelpNo()
     {
          return $this->telpNo;
     }
     public function setCellNo($aCellNo)
     {
          $this->cellNo = $aCellNo;
     }
     public function getCellNo()
     {
          return $this->cellNo;
     }
     public function setIsGlasses($aIsGlasses)
     {
          $this->isGlasses = $aIsGlasses;
     }
     public function getIsGlasses()
     {
          return $this->isGlasses;
     }
     public function setEmpStatus($aEmpStatus)
     {
          $this->empStatus = $aEmpStatus;
     }
     public function getEmpStatus()
     {
          return $this->empStatus;
     }
     public function setTaxNo($aTaxNo)
     {
          $this->taxNo = $aTaxNo;
     }
     public function getTaxNo()
     {
          return $this->taxNo;
     }
     public function setBpjsNo($aBpjsNo)
     {
          $this->bpjsNo = $aBpjsNo;
     }
     public function getBpjsNo()
     {
          return $this->bpjsNo;
     }
     public function setBpjsTkNo($aBpjsTkNo)
     {
          $this->bpjsTkNo = $aBpjsTkNo;
     }
     public function getBpjsTkNo()
     {
          return $this->bpjsTkNo;
     }
     public function setIsActive($aIsActive)
     {
          $this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
          return $this->isActive;
     }
     public function setPicInput($aPicInput)
     {
          $this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
          return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
          $this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
          return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
          $this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
          return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
          $this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
          return $this->editTime;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
          if($this->biodataId =="" || $this->biodataId == NULL) 
          {
               $this->biodataId = ''; 
          }
          if($this->fullName =="" || $this->fullName == NULL) 
          {
               $this->fullName = ''; 
          }
          if($this->placeOfBirth =="" || $this->placeOfBirth == NULL) 
          {
               $this->placeOfBirth = ''; 
          }
          if($this->dateOfBirth =="" || $this->dateOfBirth == NULL) 
          {
               $this->dateOfBirth = '1700-01-01'; 
          }
          if($this->gender =="" || $this->gender == NULL) 
          {
               $this->gender = ''; 
          }
          if($this->ethnic =="" || $this->ethnic == NULL) 
          {
               $this->ethnic = ''; 
          }
          if($this->nationality =="" || $this->nationality == NULL) 
          {
               $this->nationality = ''; 
          }
          if($this->dept =="" || $this->dept == NULL) 
          {
               $this->dept = ''; 
          }
          if($this->empPosition =="" || $this->empPosition == NULL) 
          {
               $this->empPosition = ''; 
          }
          if($this->placement =="" || $this->placement == NULL) 
          {
               $this->placement = ''; 
          }
          if($this->joinDate =="" || $this->joinDate == NULL) 
          {
               $this->joinDate = '1700-01-01'; 
          }
          if($this->idCardNo =="" || $this->idCardNo == NULL) 
          {
               $this->idCardNo = ''; 
          }
          if($this->idCardAddress =="" || $this->idCardAddress == NULL) 
          {
               $this->idCardAddress = ''; 
          }
          if($this->currentAddress =="" || $this->currentAddress == NULL) 
          {
               $this->currentAddress = ''; 
          }
          if($this->religion =="" || $this->religion == NULL) 
          {
               $this->religion = ''; 
          }
          if($this->drivingLicense =="" || $this->drivingLicense == NULL) 
          {
               $this->drivingLicense = ''; 
          }
          if($this->maritalStatus =="" || $this->maritalStatus == NULL) 
          {
               $this->maritalStatus = ''; 
          }
          if($this->empHeight =="" || $this->empHeight == NULL) 
          {
               $this->empHeight = 0; 
          }
          if($this->empWeight =="" || $this->empWeight == NULL) 
          {
               $this->empWeight = 0; 
          }
          if($this->bloodType =="" || $this->bloodType == NULL) 
          {
               $this->bloodType = ''; 
          }
          if($this->emailAddress =="" || $this->emailAddress == NULL) 
          {
               $this->emailAddress = ''; 
          }
          if($this->telpNo =="" || $this->telpNo == NULL) 
          {
               $this->telpNo = ''; 
          }
          if($this->cellNo =="" || $this->cellNo == NULL) 
          {
               $this->cellNo = ''; 
          }
          if($this->isGlasses =="" || $this->isGlasses == NULL) 
          {
               $this->isGlasses = 0; 
          }
          if($this->empStatus =="" || $this->empStatus == NULL) 
          {
               $this->empStatus = ''; 
          }
          if($this->taxNo =="" || $this->taxNo == NULL) 
          {
               $this->taxNo = ''; 
          }
          if($this->bpjsNo =="" || $this->bpjsNo == NULL) 
          {
               $this->bpjsNo = ''; 
          }
          if($this->bpjsTkNo =="" || $this->bpjsTkNo == NULL) 
          {
               $this->bpjsTkNo = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picInput =="" || $this->picInput == NULL) 
          {
               $this->picInput = ''; 
          }
          if($this->inputTime =="" || $this->inputTime == NULL) 
          {
               $this->inputTime = '1700-01-01 00:00:00'; 
          }
          if($this->picEdit =="" || $this->picEdit == NULL) 
          {
               $this->picEdit = ''; 
          }
          if($this->editTime =="" || $this->editTime == NULL) 
          {
               $this->editTime = '1700-01-01 00:00:00'; 
          }

          $stQuery  = "INSERT INTO ".$this->table." ";
          $stQuery .= "( ";
          $stQuery .=   "biodata_id,"; 
          $stQuery .=   "full_name,"; 
          $stQuery .=   "place_of_birth,"; 
          $stQuery .=   "date_of_birth,"; 
          $stQuery .=   "gender,"; 
          $stQuery .=   "ethnic,"; 
          $stQuery .=   "nationality,"; 
          $stQuery .=   "dept,"; 
          $stQuery .=   "emp_position,"; 
          $stQuery .=   "placement,"; 
          $stQuery .=   "join_date,"; 
          $stQuery .=   "id_card_no,"; 
          $stQuery .=   "id_card_address,"; 
          $stQuery .=   "current_address,"; 
          $stQuery .=   "religion,"; 
          $stQuery .=   "driving_license,"; 
          $stQuery .=   "marital_status,"; 
          $stQuery .=   "emp_height,"; 
          $stQuery .=   "emp_weight,"; 
          $stQuery .=   "blood_type,"; 
          $stQuery .=   "email_address,"; 
          $stQuery .=   "telp_no,"; 
          $stQuery .=   "cell_no,"; 
          $stQuery .=   "is_glasses,"; 
          $stQuery .=   "emp_status,"; 
          $stQuery .=   "tax_no,"; 
          $stQuery .=   "bpjs_no,"; 
          $stQuery .=   "bpjs_tk_no,"; 
          $stQuery .=   "is_active,"; 
          $stQuery .=   "pic_input,"; 
          $stQuery .=   "input_time"; 
          // $stQuery .=   "pic_edit,"; 
          // $stQuery .=   "edit_time";
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          $stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->fullName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->placeOfBirth)."',";
          $stQuery .=   "'".$this->db->escapeString($this->dateOfBirth)."',";
          $stQuery .=   "'".$this->db->escapeString($this->gender)."',";
          $stQuery .=   "'".$this->db->escapeString($this->ethnic)."',";
          $stQuery .=   "'".$this->db->escapeString($this->nationality)."',";
          $stQuery .=   "'".$this->db->escapeString($this->dept)."',";
          $stQuery .=   "'".$this->db->escapeString($this->empPosition)."',";
          $stQuery .=   "'".$this->db->escapeString($this->placement)."',";
          $stQuery .=   "'".$this->db->escapeString($this->joinDate)."',";
          $stQuery .=   "'".$this->db->escapeString($this->idCardNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->idCardAddress)."',";
          $stQuery .=   "'".$this->db->escapeString($this->currentAddress)."',";
          $stQuery .=   "'".$this->db->escapeString($this->religion)."',";
          $stQuery .=   "'".$this->db->escapeString($this->drivingLicense)."',";
          $stQuery .=   "'".$this->db->escapeString($this->maritalStatus)."',";
          $stQuery .=   " ".$this->empHeight.",";
          $stQuery .=   " ".$this->empWeight.",";
          $stQuery .=   "'".$this->db->escapeString($this->bloodType)."',";
          $stQuery .=   "'".$this->db->escapeString($this->emailAddress)."',";
          $stQuery .=   "'".$this->db->escapeString($this->telpNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->cellNo)."',";
          $stQuery .=   " ".$this->isGlasses.",";
          $stQuery .=   "'".$this->db->escapeString($this->empStatus)."',";
          $stQuery .=   "'".$this->db->escapeString($this->taxNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->bpjsNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->bpjsTkNo)."',";
          $stQuery .=   " ".$this->isActive.",";
          $stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
          $stQuery .=   "'".$this->db->escapeString($this->inputTime)."'";
          // $stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
          // $stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
          $stQuery .= "); "; 
          $this->db->query($stQuery);
          // echo $stQuery; exit();
          /*return $stQuery;
         /* echo $stQuery;*/ 
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd($id)
     {
          if($this->biodataId =="" || $this->biodataId == NULL) 
          { 
               $this->biodataId = ''; 
          } 
          if($this->dept =="" || $this->dept == NULL) 
          { 
               $this->dept = ''; 
          } 
          if($this->placement =="" || $this->placement == NULL) 
          { 
               $this->placement = ''; 
          } 
          if($this->joinDate =="" || $this->joinDate == NULL) 
          { 
               $this->joinDate = '1700-01-01'; 
          } 
          if($this->fullName =="" || $this->fullName == NULL) 
          { 
               $this->fullName = ''; 
          } 
          if($this->placeOfBirth =="" || $this->placeOfBirth == NULL) 
          { 
               $this->placeOfBirth = ''; 
          } 
          if($this->dateOfBirth =="" || $this->dateOfBirth == NULL) 
          { 
               $this->dateOfBirth = '0000-00-00'; 
          } 
          if($this->nationality =="" || $this->nationality == NULL) 
          { 
               $this->nationality = ''; 
          } 
          if($this->ethnic =="" || $this->ethnic == NULL) 
          { 
               $this->ethnic = ''; 
          } 
          if($this->idCardNo =="" || $this->idCardNo == NULL) 
          { 
               $this->idCardNo = ''; 
          } 
          if($this->idCardAddress =="" || $this->idCardAddress == NULL) 
          { 
               $this->idCardAddress = ''; 
          } 
          if($this->currentAddress =="" || $this->currentAddress == NULL) 
          { 
               $this->currentAddress = ''; 
          } 
          if($this->religion =="" || $this->religion == NULL) 
          { 
               $this->religion = ''; 
          } 
          if($this->drivingLicense =="" || $this->drivingLicense == NULL) 
          { 
               $this->drivingLicense = ''; 
          } 
          if($this->maritalStatus =="" || $this->maritalStatus == NULL) 
          { 
               $this->maritalStatus = ''; 
          } 
          if($this->empHeight =="" || $this->empHeight == NULL) 
          { 
               $this->empHeight = 0; 
          } 
          if($this->empWeight =="" || $this->empWeight == NULL) 
          { 
               $this->empWeight = 0; 
          } 
          if($this->bloodType =="" || $this->bloodType == NULL) 
          { 
               $this->bloodType = ''; 
          } 
          if($this->emailAddress =="" || $this->emailAddress == NULL) 
          { 
               $this->emailAddress = ''; 
          } 
          if($this->telpNo =="" || $this->telpNo == NULL) 
          { 
               $this->telpNo = ''; 
          } 
          if($this->cellNo =="" || $this->cellNo == NULL) 
          { 
               $this->cellNo = ''; 
          } 
          if($this->gender =="" || $this->gender == NULL) 
          { 
               $this->gender = ''; 
          } 
          if($this->empStatus =="" || $this->empStatus == NULL) 
          { 
               $this->empStatus = ''; 
          } 
          if($this->taxNo =="" || $this->taxNo == NULL) 
          { 
               $this->taxNo = ''; 
          } 
          if($this->bpjsNo =="" || $this->bpjsNo == NULL) 
          { 
               $this->bpjsNo = ''; 
          } 
          if($this->bpjsTkNo =="" || $this->bpjsTkNo == NULL) 
          { 
               $this->bpjsTkNo = ''; 
          } 
          if($this->picInput =="" || $this->picInput == NULL) 
          { 
               $this->picInput = ''; 
          } 
          if($this->inputTime =="" || $this->inputTime == NULL) 
          { 
               $this->inputTime = '1700-01-01 00:00:00'; 
          } 
          if($this->picEdit =="" || $this->picEdit == NULL) 
          { 
               $this->picEdit = ''; 
          } 
          if($this->editTime =="" || $this->editTime == NULL) 
          { 
               $this->editTime = '1700-01-01 00:00:00'; 
          } 
          if($this->empPosition =="" || $this->empPosition == NULL) 
          { 
               $this->empPosition = ''; 
          } 
          if($this->passportNo =="" || $this->passportNo == NULL) 
          { 
               $this->passportNo = ''; 
          } 
          if($this->isGlasses =="" || $this->isGlasses == NULL) 
          { 
               $this->isGlasses = 0; 
          } 
          // if($this->isActive =="" || $this->isActive == NULL) 
          // { 
          //      $this->isActive = 0; 
          // } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          // $stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
          // $stQuery .=   'dept_id ='.$this->deptId.','; 
          $stQuery .=   "full_name ='".$this->db->escapeString($this->fullName)."', "; 
          $stQuery .=   "place_of_birth ='".$this->db->escapeString($this->placeOfBirth)."', "; 
          $stQuery .=   "date_of_birth ='".$this->db->escapeString($this->dateOfBirth)."', "; 
          $stQuery .=   "gender ='".$this->db->escapeString($this->gender)."', "; 
          $stQuery .=   "ethnic ='".$this->db->escapeString($this->ethnic)."', "; 
          $stQuery .=   "nationality ='".$this->db->escapeString($this->nationality)."', "; 
          $stQuery .=   "dept ='".$this->db->escapeString($this->dept)."', "; 
          $stQuery .=   "emp_position ='".$this->db->escapeString($this->empPosition)."', "; 
          $stQuery .=   "placement ='".$this->db->escapeString($this->placement)."', "; 
          $stQuery .=   "join_date ='".$this->db->escapeString($this->joinDate)."', "; 
          $stQuery .=   "id_card_no ='".$this->db->escapeString($this->idCardNo)."', "; 
          $stQuery .=   "id_card_address ='".$this->db->escapeString($this->idCardAddress)."', "; 
          $stQuery .=   "current_address ='".$this->db->escapeString($this->currentAddress)."', "; 
          $stQuery .=   "religion ='".$this->db->escapeString($this->religion)."', "; 
          $stQuery .=   "driving_license ='".$this->db->escapeString($this->drivingLicense)."', "; 
          $stQuery .=   "marital_status ='".$this->db->escapeString($this->maritalStatus)."', "; 
          $stQuery .=   'emp_height ='.$this->empHeight.','; 
          $stQuery .=   'emp_weight ='.$this->empWeight.','; 
          $stQuery .=   "blood_type ='".$this->db->escapeString($this->bloodType)."', "; 
          $stQuery .=   "email_address ='".$this->db->escapeString($this->emailAddress)."', "; 
          $stQuery .=   "telp_no ='".$this->db->escapeString($this->telpNo)."', "; 
          $stQuery .=   "cell_no ='".$this->db->escapeString($this->cellNo)."', "; 
          $stQuery .=   'is_glasses ='.$this->isGlasses.','; 
          $stQuery .=   "emp_status ='".$this->db->escapeString($this->empStatus)."', "; 
          $stQuery .=   "tax_no ='".$this->db->escapeString($this->taxNo)."', "; 
          $stQuery .=   "bpjs_no ='".$this->db->escapeString($this->bpjsNo)."', "; 
          $stQuery .=   "bpjs_tk_no ='".$this->db->escapeString($this->bpjsTkNo)."', "; 
          // $stQuery .=   'is_active ='.$this->isActive.','; 
          $stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
          $stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "biodata_id = '".$this->db->escapeString($id)."'"; 
          
          $this->db->query($stQuery); 
     }
     /* END UPDATE */
     /* START DELETE */
      public function del($id)
     {
          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "is_active ='0'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "biodata_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }

     public function nonActive($id)
     {
          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "is_active ='0'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "biodata_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }

     public function active($id)
     {
          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "is_active ='1'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "biodata_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
	$stQuery  = "SELECT * FROM ".$this->table." WHERE is_active='1' "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList;      
     }

     public function search($keywords)
     {
     $stQuery  = "SELECT a.*, b.* FROM mt_biodata_01 a , mt_salary b WHERE a.biodata_id = b.biodata_id AND a.is_active = b.is_active AND full_name LIKE '%$keywords%' "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList;      
     }
     public function checkByKtp($ktp)
     {
     $stQuery  = "SELECT * FROM ".$this->table." WHERE  id_card_no = '".$ktp."'AND is_active='1' "; 
     // echo $stQuery;
     // exit();
          $query  = $this->db->query($stQuery); 
          return $query->getRowArray();
      
     }
     public function getAll1()
     {
	$stQuery  = "SELECT biodata_id,full_name FROM ".$this->table." WHERE is_active='1' "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList;      }

     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." ";     
          $stQuery .= "WHERE biodata_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow; 
     }
     function get_biodata()
     {
        $stQuery = "SELECT biodata_id, full_name FROM ".$this->table." WHERE is_active = '1' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();

     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." "; 
          $stQuery .= "WHERE biodata_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          $this->biodataId = $arrayRow['biodata_id']; 
          // $this->company = $arrayRow['company']; 
          $this->dept = $arrayRow['dept']; 
          $this->placement = $arrayRow['placement']; 
          // $this->approveLevel = $arrayRow['approve_level']; 
          // $this->internalId = $arrayRow['internal_id']; 
          // $this->positionLevel = $arrayRow['position_level']; 
          $this->joinDate = $arrayRow['join_date']; 
          $this->fullName = $arrayRow['full_name']; 
          $this->placeOfBirth = $arrayRow['place_of_birth']; 
          $this->dateOfBirth = $arrayRow['date_of_birth']; 
          $this->nationality = $arrayRow['nationality']; 
          $this->ethnic = $arrayRow['ethnic']; 
          $this->idCardNo = $arrayRow['id_card_no']; 
          $this->idCardAddress = $arrayRow['id_card_address']; 
          $this->currentAddress = $arrayRow['current_address']; 
          // $this->residenceStatus = $arrayRow['residence_status']; 
          $this->religion = $arrayRow['religion']; 
          $this->drivingLicense = $arrayRow['driving_license']; 
          $this->maritalStatus = $arrayRow['marital_status']; 
          $this->empHeight = $arrayRow['emp_height']; 
          $this->empWeight = $arrayRow['emp_weight']; 
          $this->bloodType = $arrayRow['blood_type']; 
          $this->emailAddress = $arrayRow['email_address']; 
          $this->telpNo = $arrayRow['telp_no']; 
          $this->cellNo = $arrayRow['cell_no']; 
          $this->gender = $arrayRow['gender']; 
          $this->empStatus = $arrayRow['emp_status']; 
          $this->taxNo = $arrayRow['tax_no']; 
          $this->bpjsNo = $arrayRow['bpjs_no']; 
          $this->bpjsTkNo = $arrayRow['bpjs_tk_no']; 
          $this->picInput = $arrayRow['pic_input']; 
          $this->inputTime = $arrayRow['input_time']; 
          $this->picEdit = $arrayRow['pic_edit']; 
          $this->editTime = $arrayRow['edit_time']; 
          $this->empPosition = $arrayRow['emp_position']; 
          // $this->passportNo = $arrayRow['passport_no']; 
          $this->isGlasses = $arrayRow['is_glasses']; 
          $this->isActive = $arrayRow['is_active']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
          $this->biodataId = ''; 
          $this->company = ''; 
          $this->dept = ''; 
          $this->placement = ''; 
          $this->approveLevel = ''; 
          $this->internalId = ''; 
          $this->positionLevel = 0; 
          $this->joinDate = '1700-01-01'; 
          $this->fullName = ''; 
          $this->placeOfBirth = ''; 
          $this->dateOfBirth = '1700-01-01'; 
          $this->nationality = ''; 
          $this->ethnic = ''; 
          $this->idCardNo = ''; 
          $this->idCardAddress = ''; 
          $this->currentAddress = ''; 
          $this->residenceStatus = ''; 
          $this->religion = ''; 
          $this->drivingLicense = ''; 
          $this->maritalStatus = ''; 
          $this->empHeight = 0; 
          $this->empWeight = 0; 
          $this->bloodType = ''; 
          $this->emailAddress = ''; 
          $this->telpNo = ''; 
          $this->cellNo = ''; 
          $this->gender = ''; 
          $this->empStatus = ''; 
          $this->taxNo = ''; 
          $this->bpjsNo = ''; 
          $this->bpjsTkNo = ''; 
          $this->picInput = ''; 
          $this->inputTime = '1700-01-01 00:00:00'; 
          $this->picEdit = ''; 
          $this->editTime = '1700-01-01 00:00:00'; 
          $this->empPosition = ''; 
          $this->passportNo = ''; 
          $this->isGlasses = 0; 
          $this->isActive = 0; 
     }
     /* END OF RESET VALUES */
     /* ADDED MANUALLY */
     public function generateId($columnId)
     {
          $db = \Config\Database::connect($this->DBGroup); 
          $strSql = "SELECT ";
          $strSql .= " CASE WHEN id_year = curr_ym THEN ";
          $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
          $strSql .= " ELSE ";
          $strSql .= "   CONCAT(curr_ym, '00001') ";
          $strSql .= " END AS doc_id ";
          $strSql .= "FROM ";
          $strSql .= " (SELECT ";
          $strSql .= "   MAX(".$columnId.") fi,";
          $strSql .= "   LEFT(".$columnId.",4) id_year,";
          $strSql .= "   current_date dt,";
          $strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
          $strSql .= "   CONCAT(";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
          $strSql .= "   LPAD(";
          $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
          $strSql .= "    )";
          $strSql .= "   ) curr_ym,";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
          $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
          $strSql .= " FROM ";
          $strSql .= "   ".$this->table." ";
          $strSql .= " GROUP BY ".$columnId.") a ";
          $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
          // return $strSql; exit();

          $query  = $db->query($strSql); 
          $arrayRow = $query->getRowArray(); 
          
          if(!isset($arrayRow))
          {
               $curYM = date('ym');
               $arrayRow['doc_id'] = $curYM.'00001';
          }
          
          return $arrayRow;
     }


     function getIdDuplicate($PTFId)
     {
          $stQuery  = "SELECT biodata_id FROM ".$this->table." ";     
          $stQuery .= "WHERE biodata_id = '".$this->db->escapeString($PTFId)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow; 
     }

     /* START GET DATA BY ID */
     public function loadBioIdByNie($nie)
     {
          $stQuery  = "SELECT biodata_id, full_name, dept FROM mt_biodata_01 WHERE biodata_id = '".$nie."' ";
          $query    = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow;
          // echo $stQuery; exit();
     }
     /* END GET DATA BY ID */
     function get_biodata_active()
     {
        $stQuery = "SELECT biodata_id, full_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_active = '1' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     }
     function get_biodata_foreign()
     {
        $stQuery = "SELECT biodata_id, full_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_active = '0' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     }
}