<?php namespace App\Controllers\Transaction; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Apr 06, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Transaction\M_tr_overtime;

class Tr_overtime extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../v_tr_overtime';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../ins_tr_overtime';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$trOvertime = new M_tr_overtime();
          $data['trOvertime'] = $trOvertime->getById($overtime_id);
          /* ***Using Valid Path */
          $data['actView'] = '../upd_tr_overtime';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$trOvertime = new M_tr_overtime();
     	$trOvertime->resetValues();
     	$trOvertime->setOvertimeId($_POST['overtimeId']);
     	$trOvertime->setBioRecId($_POST['bioRecId']);
     	$trOvertime->setRosterId($_POST['rosterId']);
     	$trOvertime->setClientName($_POST['clientName']);
     	$trOvertime->setYearPeriod($_POST['yearPeriod']);
     	$trOvertime->setMonthPeriod($_POST['monthPeriod']);
     	$trOvertime->setOt1D01($_POST['ot1D01']);
     	$trOvertime->setOt1D02($_POST['ot1D02']);
     	$trOvertime->setOt1D03($_POST['ot1D03']);
     	$trOvertime->setOt1D04($_POST['ot1D04']);
     	$trOvertime->setOt1D05($_POST['ot1D05']);
     	$trOvertime->setOt1D06($_POST['ot1D06']);
     	$trOvertime->setOt1D07($_POST['ot1D07']);
     	$trOvertime->setOt1D08($_POST['ot1D08']);
     	$trOvertime->setOt1D09($_POST['ot1D09']);
     	$trOvertime->setOt1D10($_POST['ot1D10']);
     	$trOvertime->setOt1D11($_POST['ot1D11']);
     	$trOvertime->setOt1D12($_POST['ot1D12']);
     	$trOvertime->setOt1D13($_POST['ot1D13']);
     	$trOvertime->setOt1D14($_POST['ot1D14']);
     	$trOvertime->setOt1D15($_POST['ot1D15']);
     	$trOvertime->setOt1D16($_POST['ot1D16']);
     	$trOvertime->setOt1D17($_POST['ot1D17']);
     	$trOvertime->setOt1D18($_POST['ot1D18']);
     	$trOvertime->setOt1D19($_POST['ot1D19']);
     	$trOvertime->setOt1D20($_POST['ot1D20']);
     	$trOvertime->setOt1D21($_POST['ot1D21']);
     	$trOvertime->setOt1D22($_POST['ot1D22']);
     	$trOvertime->setOt1D23($_POST['ot1D23']);
     	$trOvertime->setOt1D24($_POST['ot1D24']);
     	$trOvertime->setOt1D25($_POST['ot1D25']);
     	$trOvertime->setOt1D26($_POST['ot1D26']);
     	$trOvertime->setOt1D27($_POST['ot1D27']);
     	$trOvertime->setOt1D28($_POST['ot1D28']);
     	$trOvertime->setOt1D29($_POST['ot1D29']);
     	$trOvertime->setOt1D30($_POST['ot1D30']);
     	$trOvertime->setOt1D31($_POST['ot1D31']);
     	$trOvertime->setOt2D01($_POST['ot2D01']);
     	$trOvertime->setOt2D02($_POST['ot2D02']);
     	$trOvertime->setOt2D03($_POST['ot2D03']);
     	$trOvertime->setOt2D04($_POST['ot2D04']);
     	$trOvertime->setOt2D05($_POST['ot2D05']);
     	$trOvertime->setOt2D06($_POST['ot2D06']);
     	$trOvertime->setOt2D07($_POST['ot2D07']);
     	$trOvertime->setOt2D08($_POST['ot2D08']);
     	$trOvertime->setOt2D09($_POST['ot2D09']);
     	$trOvertime->setOt2D10($_POST['ot2D10']);
     	$trOvertime->setOt2D11($_POST['ot2D11']);
     	$trOvertime->setOt2D12($_POST['ot2D12']);
     	$trOvertime->setOt2D13($_POST['ot2D13']);
     	$trOvertime->setOt2D14($_POST['ot2D14']);
     	$trOvertime->setOt2D15($_POST['ot2D15']);
     	$trOvertime->setOt2D16($_POST['ot2D16']);
     	$trOvertime->setOt2D17($_POST['ot2D17']);
     	$trOvertime->setOt2D18($_POST['ot2D18']);
     	$trOvertime->setOt2D19($_POST['ot2D19']);
     	$trOvertime->setOt2D20($_POST['ot2D20']);
     	$trOvertime->setOt2D21($_POST['ot2D21']);
     	$trOvertime->setOt2D22($_POST['ot2D22']);
     	$trOvertime->setOt2D23($_POST['ot2D23']);
     	$trOvertime->setOt2D24($_POST['ot2D24']);
     	$trOvertime->setOt2D25($_POST['ot2D25']);
     	$trOvertime->setOt2D26($_POST['ot2D26']);
     	$trOvertime->setOt2D27($_POST['ot2D27']);
     	$trOvertime->setOt2D28($_POST['ot2D28']);
     	$trOvertime->setOt2D29($_POST['ot2D29']);
     	$trOvertime->setOt2D30($_POST['ot2D30']);
     	$trOvertime->setOt2D31($_POST['ot2D31']);
     	$trOvertime->setOt3D01($_POST['ot3D01']);
     	$trOvertime->setOt3D02($_POST['ot3D02']);
     	$trOvertime->setOt3D03($_POST['ot3D03']);
     	$trOvertime->setOt3D04($_POST['ot3D04']);
     	$trOvertime->setOt3D05($_POST['ot3D05']);
     	$trOvertime->setOt3D06($_POST['ot3D06']);
     	$trOvertime->setOt3D07($_POST['ot3D07']);
     	$trOvertime->setOt3D08($_POST['ot3D08']);
     	$trOvertime->setOt3D09($_POST['ot3D09']);
     	$trOvertime->setOt3D10($_POST['ot3D10']);
     	$trOvertime->setOt3D11($_POST['ot3D11']);
     	$trOvertime->setOt3D12($_POST['ot3D12']);
     	$trOvertime->setOt3D13($_POST['ot3D13']);
     	$trOvertime->setOt3D14($_POST['ot3D14']);
     	$trOvertime->setOt3D15($_POST['ot3D15']);
     	$trOvertime->setOt3D16($_POST['ot3D16']);
     	$trOvertime->setOt3D17($_POST['ot3D17']);
     	$trOvertime->setOt3D18($_POST['ot3D18']);
     	$trOvertime->setOt3D19($_POST['ot3D19']);
     	$trOvertime->setOt3D20($_POST['ot3D20']);
     	$trOvertime->setOt3D21($_POST['ot3D21']);
     	$trOvertime->setOt3D22($_POST['ot3D22']);
     	$trOvertime->setOt3D23($_POST['ot3D23']);
     	$trOvertime->setOt3D24($_POST['ot3D24']);
     	$trOvertime->setOt3D25($_POST['ot3D25']);
     	$trOvertime->setOt3D26($_POST['ot3D26']);
     	$trOvertime->setOt3D27($_POST['ot3D27']);
     	$trOvertime->setOt3D28($_POST['ot3D28']);
     	$trOvertime->setOt3D29($_POST['ot3D29']);
     	$trOvertime->setOt3D30($_POST['ot3D30']);
     	$trOvertime->setOt3D31($_POST['ot3D31']);
     	$trOvertime->setOt4D01($_POST['ot4D01']);
     	$trOvertime->setOt4D02($_POST['ot4D02']);
     	$trOvertime->setOt4D03($_POST['ot4D03']);
     	$trOvertime->setOt4D04($_POST['ot4D04']);
     	$trOvertime->setOt4D05($_POST['ot4D05']);
     	$trOvertime->setOt4D06($_POST['ot4D06']);
     	$trOvertime->setOt4D07($_POST['ot4D07']);
     	$trOvertime->setOt4D08($_POST['ot4D08']);
     	$trOvertime->setOt4D09($_POST['ot4D09']);
     	$trOvertime->setOt4D10($_POST['ot4D10']);
     	$trOvertime->setOt4D11($_POST['ot4D11']);
     	$trOvertime->setOt4D12($_POST['ot4D12']);
     	$trOvertime->setOt4D13($_POST['ot4D13']);
     	$trOvertime->setOt4D14($_POST['ot4D14']);
     	$trOvertime->setOt4D15($_POST['ot4D15']);
     	$trOvertime->setOt4D16($_POST['ot4D16']);
     	$trOvertime->setOt4D17($_POST['ot4D17']);
     	$trOvertime->setOt4D18($_POST['ot4D18']);
     	$trOvertime->setOt4D19($_POST['ot4D19']);
     	$trOvertime->setOt4D20($_POST['ot4D20']);
     	$trOvertime->setOt4D21($_POST['ot4D21']);
     	$trOvertime->setOt4D22($_POST['ot4D22']);
     	$trOvertime->setOt4D23($_POST['ot4D23']);
     	$trOvertime->setOt4D24($_POST['ot4D24']);
     	$trOvertime->setOt4D25($_POST['ot4D25']);
     	$trOvertime->setOt4D26($_POST['ot4D26']);
     	$trOvertime->setOt4D27($_POST['ot4D27']);
     	$trOvertime->setOt4D28($_POST['ot4D28']);
     	$trOvertime->setOt4D29($_POST['ot4D29']);
     	$trOvertime->setOt4D30($_POST['ot4D30']);
     	$trOvertime->setOt4D31($_POST['ot4D31']);
     	$trOvertime->setNightShiftCount($_POST['nightShiftCount']);
     	$trOvertime->setDayShiftCount($_POST['dayShiftCount']);
     	$trOvertime->setOffTotal($_POST['offTotal']);
     	$trOvertime->setEmergencyTotal($_POST['emergencyTotal']);
     	$trOvertime->setStandbyTotal($_POST['standbyTotal']);
     	$trOvertime->setPaidVacationTotal($_POST['paidVacationTotal']);
     	$trOvertime->setPaidPermitTotal($_POST['paidPermitTotal']);
     	$trOvertime->setPermitTotal($_POST['permitTotal']);
     	$trOvertime->setSickTotal($_POST['sickTotal']);
     	$trOvertime->setAlpaTotal($_POST['alpaTotal']);
     	$trOvertime->setAttendTotal($_POST['attendTotal']);
     	$trOvertime->setPhTotal($_POST['phTotal']);
     	$trOvertime->setInPhTotal($_POST['inPhTotal']);
     	$trOvertime->setOutCampTotal($_POST['outCampTotal']);
     	$trOvertime->setExpCampTotal($_POST['expCampTotal']);
     	$trOvertime->setBsOnlyCount($_POST['bsOnlyCount']);
     	$trOvertime->setVacationDays($_POST['vacationDays']);
     	$trOvertime->setUnpaidDays($_POST['unpaidDays']);
     	$trOvertime->setAttendInOff($_POST['attendInOff']);
     	$trOvertime->setVacationTotal($_POST['vacationTotal']);
     	$trOvertime->setIsActive($_POST['isActive']);
     	$trOvertime->setPicProcess($_POST['picProcess']);
     	$trOvertime->setProcessTime($_POST['processTime']);
     	$trOvertime->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['overtimeId'];
     	$trOvertime = new M_tr_overtime();
     	$trOvertime->setObjectById($id);
     	$trOvertime->setOvertimeId($_POST['overtimeId']);
     	$trOvertime->setBioRecId($_POST['bioRecId']);
     	$trOvertime->setRosterId($_POST['rosterId']);
     	$trOvertime->setClientName($_POST['clientName']);
     	$trOvertime->setYearPeriod($_POST['yearPeriod']);
     	$trOvertime->setMonthPeriod($_POST['monthPeriod']);
     	$trOvertime->setOt1D01($_POST['ot1D01']);
     	$trOvertime->setOt1D02($_POST['ot1D02']);
     	$trOvertime->setOt1D03($_POST['ot1D03']);
     	$trOvertime->setOt1D04($_POST['ot1D04']);
     	$trOvertime->setOt1D05($_POST['ot1D05']);
     	$trOvertime->setOt1D06($_POST['ot1D06']);
     	$trOvertime->setOt1D07($_POST['ot1D07']);
     	$trOvertime->setOt1D08($_POST['ot1D08']);
     	$trOvertime->setOt1D09($_POST['ot1D09']);
     	$trOvertime->setOt1D10($_POST['ot1D10']);
     	$trOvertime->setOt1D11($_POST['ot1D11']);
     	$trOvertime->setOt1D12($_POST['ot1D12']);
     	$trOvertime->setOt1D13($_POST['ot1D13']);
     	$trOvertime->setOt1D14($_POST['ot1D14']);
     	$trOvertime->setOt1D15($_POST['ot1D15']);
     	$trOvertime->setOt1D16($_POST['ot1D16']);
     	$trOvertime->setOt1D17($_POST['ot1D17']);
     	$trOvertime->setOt1D18($_POST['ot1D18']);
     	$trOvertime->setOt1D19($_POST['ot1D19']);
     	$trOvertime->setOt1D20($_POST['ot1D20']);
     	$trOvertime->setOt1D21($_POST['ot1D21']);
     	$trOvertime->setOt1D22($_POST['ot1D22']);
     	$trOvertime->setOt1D23($_POST['ot1D23']);
     	$trOvertime->setOt1D24($_POST['ot1D24']);
     	$trOvertime->setOt1D25($_POST['ot1D25']);
     	$trOvertime->setOt1D26($_POST['ot1D26']);
     	$trOvertime->setOt1D27($_POST['ot1D27']);
     	$trOvertime->setOt1D28($_POST['ot1D28']);
     	$trOvertime->setOt1D29($_POST['ot1D29']);
     	$trOvertime->setOt1D30($_POST['ot1D30']);
     	$trOvertime->setOt1D31($_POST['ot1D31']);
     	$trOvertime->setOt2D01($_POST['ot2D01']);
     	$trOvertime->setOt2D02($_POST['ot2D02']);
     	$trOvertime->setOt2D03($_POST['ot2D03']);
     	$trOvertime->setOt2D04($_POST['ot2D04']);
     	$trOvertime->setOt2D05($_POST['ot2D05']);
     	$trOvertime->setOt2D06($_POST['ot2D06']);
     	$trOvertime->setOt2D07($_POST['ot2D07']);
     	$trOvertime->setOt2D08($_POST['ot2D08']);
     	$trOvertime->setOt2D09($_POST['ot2D09']);
     	$trOvertime->setOt2D10($_POST['ot2D10']);
     	$trOvertime->setOt2D11($_POST['ot2D11']);
     	$trOvertime->setOt2D12($_POST['ot2D12']);
     	$trOvertime->setOt2D13($_POST['ot2D13']);
     	$trOvertime->setOt2D14($_POST['ot2D14']);
     	$trOvertime->setOt2D15($_POST['ot2D15']);
     	$trOvertime->setOt2D16($_POST['ot2D16']);
     	$trOvertime->setOt2D17($_POST['ot2D17']);
     	$trOvertime->setOt2D18($_POST['ot2D18']);
     	$trOvertime->setOt2D19($_POST['ot2D19']);
     	$trOvertime->setOt2D20($_POST['ot2D20']);
     	$trOvertime->setOt2D21($_POST['ot2D21']);
     	$trOvertime->setOt2D22($_POST['ot2D22']);
     	$trOvertime->setOt2D23($_POST['ot2D23']);
     	$trOvertime->setOt2D24($_POST['ot2D24']);
     	$trOvertime->setOt2D25($_POST['ot2D25']);
     	$trOvertime->setOt2D26($_POST['ot2D26']);
     	$trOvertime->setOt2D27($_POST['ot2D27']);
     	$trOvertime->setOt2D28($_POST['ot2D28']);
     	$trOvertime->setOt2D29($_POST['ot2D29']);
     	$trOvertime->setOt2D30($_POST['ot2D30']);
     	$trOvertime->setOt2D31($_POST['ot2D31']);
     	$trOvertime->setOt3D01($_POST['ot3D01']);
     	$trOvertime->setOt3D02($_POST['ot3D02']);
     	$trOvertime->setOt3D03($_POST['ot3D03']);
     	$trOvertime->setOt3D04($_POST['ot3D04']);
     	$trOvertime->setOt3D05($_POST['ot3D05']);
     	$trOvertime->setOt3D06($_POST['ot3D06']);
     	$trOvertime->setOt3D07($_POST['ot3D07']);
     	$trOvertime->setOt3D08($_POST['ot3D08']);
     	$trOvertime->setOt3D09($_POST['ot3D09']);
     	$trOvertime->setOt3D10($_POST['ot3D10']);
     	$trOvertime->setOt3D11($_POST['ot3D11']);
     	$trOvertime->setOt3D12($_POST['ot3D12']);
     	$trOvertime->setOt3D13($_POST['ot3D13']);
     	$trOvertime->setOt3D14($_POST['ot3D14']);
     	$trOvertime->setOt3D15($_POST['ot3D15']);
     	$trOvertime->setOt3D16($_POST['ot3D16']);
     	$trOvertime->setOt3D17($_POST['ot3D17']);
     	$trOvertime->setOt3D18($_POST['ot3D18']);
     	$trOvertime->setOt3D19($_POST['ot3D19']);
     	$trOvertime->setOt3D20($_POST['ot3D20']);
     	$trOvertime->setOt3D21($_POST['ot3D21']);
     	$trOvertime->setOt3D22($_POST['ot3D22']);
     	$trOvertime->setOt3D23($_POST['ot3D23']);
     	$trOvertime->setOt3D24($_POST['ot3D24']);
     	$trOvertime->setOt3D25($_POST['ot3D25']);
     	$trOvertime->setOt3D26($_POST['ot3D26']);
     	$trOvertime->setOt3D27($_POST['ot3D27']);
     	$trOvertime->setOt3D28($_POST['ot3D28']);
     	$trOvertime->setOt3D29($_POST['ot3D29']);
     	$trOvertime->setOt3D30($_POST['ot3D30']);
     	$trOvertime->setOt3D31($_POST['ot3D31']);
     	$trOvertime->setOt4D01($_POST['ot4D01']);
     	$trOvertime->setOt4D02($_POST['ot4D02']);
     	$trOvertime->setOt4D03($_POST['ot4D03']);
     	$trOvertime->setOt4D04($_POST['ot4D04']);
     	$trOvertime->setOt4D05($_POST['ot4D05']);
     	$trOvertime->setOt4D06($_POST['ot4D06']);
     	$trOvertime->setOt4D07($_POST['ot4D07']);
     	$trOvertime->setOt4D08($_POST['ot4D08']);
     	$trOvertime->setOt4D09($_POST['ot4D09']);
     	$trOvertime->setOt4D10($_POST['ot4D10']);
     	$trOvertime->setOt4D11($_POST['ot4D11']);
     	$trOvertime->setOt4D12($_POST['ot4D12']);
     	$trOvertime->setOt4D13($_POST['ot4D13']);
     	$trOvertime->setOt4D14($_POST['ot4D14']);
     	$trOvertime->setOt4D15($_POST['ot4D15']);
     	$trOvertime->setOt4D16($_POST['ot4D16']);
     	$trOvertime->setOt4D17($_POST['ot4D17']);
     	$trOvertime->setOt4D18($_POST['ot4D18']);
     	$trOvertime->setOt4D19($_POST['ot4D19']);
     	$trOvertime->setOt4D20($_POST['ot4D20']);
     	$trOvertime->setOt4D21($_POST['ot4D21']);
     	$trOvertime->setOt4D22($_POST['ot4D22']);
     	$trOvertime->setOt4D23($_POST['ot4D23']);
     	$trOvertime->setOt4D24($_POST['ot4D24']);
     	$trOvertime->setOt4D25($_POST['ot4D25']);
     	$trOvertime->setOt4D26($_POST['ot4D26']);
     	$trOvertime->setOt4D27($_POST['ot4D27']);
     	$trOvertime->setOt4D28($_POST['ot4D28']);
     	$trOvertime->setOt4D29($_POST['ot4D29']);
     	$trOvertime->setOt4D30($_POST['ot4D30']);
     	$trOvertime->setOt4D31($_POST['ot4D31']);
     	$trOvertime->setNightShiftCount($_POST['nightShiftCount']);
     	$trOvertime->setDayShiftCount($_POST['dayShiftCount']);
     	$trOvertime->setOffTotal($_POST['offTotal']);
     	$trOvertime->setEmergencyTotal($_POST['emergencyTotal']);
     	$trOvertime->setStandbyTotal($_POST['standbyTotal']);
     	$trOvertime->setPaidVacationTotal($_POST['paidVacationTotal']);
     	$trOvertime->setPaidPermitTotal($_POST['paidPermitTotal']);
     	$trOvertime->setPermitTotal($_POST['permitTotal']);
     	$trOvertime->setSickTotal($_POST['sickTotal']);
     	$trOvertime->setAlpaTotal($_POST['alpaTotal']);
     	$trOvertime->setAttendTotal($_POST['attendTotal']);
     	$trOvertime->setPhTotal($_POST['phTotal']);
     	$trOvertime->setInPhTotal($_POST['inPhTotal']);
     	$trOvertime->setOutCampTotal($_POST['outCampTotal']);
     	$trOvertime->setExpCampTotal($_POST['expCampTotal']);
     	$trOvertime->setBsOnlyCount($_POST['bsOnlyCount']);
     	$trOvertime->setVacationDays($_POST['vacationDays']);
     	$trOvertime->setUnpaidDays($_POST['unpaidDays']);
     	$trOvertime->setAttendInOff($_POST['attendInOff']);
     	$trOvertime->setVacationTotal($_POST['vacationTotal']);
     	$trOvertime->setIsActive($_POST['isActive']);
     	$trOvertime->setPicProcess($_POST['picProcess']);
     	$trOvertime->setProcessTime($_POST['processTime']);
     	$trOvertime->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$trOvertime = new M_tr_overtime();
     	$id = $_POST['overtimeId'];
     	$trOvertime->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$trOvertime = new M_tr_overtime();
     	$rs = $trOvertime->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
