<?php

namespace App\Models\Master;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use CodeIgniter\Model;

class ConfigAllowance extends Model
{
    /* START PRIVATE VARIABLES */
    // protected $myDb = 'db_recruitment';	protected $DBGroup = '';
    protected $table = 'mt_config_allowance';
    protected $primaryKey = 'allowance_mt_id';
    protected $returnType = 'array';

    public function loadConfigAllowance($clientName)
    {
        return $this->where('client_name', $clientName)->findAll();
    }
}
