<?php namespace App\Models\Master; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_dept extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = 'hris';
     protected $table = 'mt_dept';
     protected $primaryKey = 'dept_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $deptId;
     protected $deptCode;
     protected $deptName;
     protected $isActive;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
          parent::__construct();
          $this->db = \Config\Database::connect($this->DBGroup, false);
          $this->deptId = '';
          $this->deptCode = '';
          $this->deptName = '';
          $this->isActive = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setdeptId($adeptId)
     {
          $this->deptId = $adeptId;
     }
     public function getdeptId()
     {
          return $this->deptId;
     }
     public function setdeptCode($adeptCode)
     {
          $this->deptCode = $adeptCode;
     }
     public function getdeptCode()
     {
          return $this->deptCode;
     }
     public function setdeptName($adeptName)
     {
          $this->deptName = $adeptName;
     }
     public function getdeptName()
     {
          return $this->deptName;
     }
     public function setIsActive($aIsActive)
     {
          $this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
          return $this->isActive;
     }
     public function setPicInput($aPicInput)
     {
          $this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
          return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
          $this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
          return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
          $this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
          return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
          $this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
          return $this->editTime;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
          if($this->deptId =="" || $this->deptId == NULL) 
          {
               $this->deptId = ''; 
          }
          if($this->deptCode =="" || $this->deptCode == NULL) 
          {
               $this->deptCode = ''; 
          }
          if($this->deptName =="" || $this->deptName == NULL) 
          {
               $this->deptName = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picInput =="" || $this->picInput == NULL) 
          {
               $this->picInput = ''; 
          }
          if($this->inputTime =="" || $this->inputTime == NULL) 
          {
               $this->inputTime = '1700-01-01 00:00:00'; 
          }
          if($this->picEdit =="" || $this->picEdit == NULL) 
          {
               $this->picEdit = ''; 
          }
          if($this->editTime =="" || $this->editTime == NULL) 
          {
               $this->editTime = '1700-01-01 00:00:00'; 
          }

          $stQuery  = "INSERT INTO ".$this->table." ";
          $stQuery .= "( ";
          // $stQuery .=   "dept_id,"; 
          $stQuery .=   "dept_code,"; 
          $stQuery .=   "dept_name,"; 
          $stQuery .=   "is_Active,";  
          $stQuery .=   "pic_input,"; 
          $stQuery .=   "input_time"; 
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          // $stQuery .=   "'".$this->db->escapeString($this->deptId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->deptCode)."',";
          $stQuery .=   "'".$this->db->escapeString($this->deptName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->isActive)."',";
          $stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
          $stQuery .=   "'".$this->db->escapeString($this->inputTime)."'";
          $stQuery .= "); "; 
          $this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd($id)
     {
          if($this->deptId =="" || $this->deptId == NULL) 
          { 
               $this->deptId = ''; 
          } 
          if($this->deptCode =="" || $this->deptCode == NULL) 
          { 
               $this->deptCode = ''; 
          } 
          if($this->deptName =="" || $this->deptName == NULL) 
          { 
               $this->deptName = ''; 
          } 
          if($this->isActive =="" || $this->isActive == NULL) 
          { 
               $this->isActive = 0; 
          } 
          if($this->picInput =="" || $this->picInput == NULL) 
          { 
               $this->picInput = ''; 
          } 
          if($this->inputTime =="" || $this->inputTime == NULL) 
          { 
               $this->inputTime = '1700-01-01 00:00:00'; 
          } 
          if($this->picEdit =="" || $this->picEdit == NULL) 
          { 
               $this->picEdit = ''; 
          } 
          if($this->editTime =="" || $this->editTime == NULL) 
          { 
               $this->editTime = '1700-01-01 00:00:00'; 
          } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "dept_id ='".$this->db->escapeString($this->deptId)."', "; 
          $stQuery .=   "dept_code ='".$this->db->escapeString($this->deptCode)."', "; 
          $stQuery .=   "dept_name ='".$this->db->escapeString($this->deptName)."', "; 
          $stQuery .=   "is_Active ='".$this->db->escapeString($this->isActive)."',"; 
          $stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."',"; 
          $stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "dept_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }
     /* END UPDATE */
     /* START DELETE */
     public function del($id)
     {
          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   "is_active ='0'"; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   "dept_id = '".$this->db->escapeString($id)."'"; 
          $this->db->query($stQuery); 
     }
     function get_dept()
     {
        $stQuery = "SELECT dept_id, dept_code, dept_name FROM ".$this->table." WHERE is_active = '1' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();

     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
          $stQuery  = "SELECT * FROM ".$this->table." WHERE is_active='1' "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." ";     
          $stQuery .= "WHERE dept_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." "; 
          $stQuery .= "WHERE dept_id = '".$this->db->escapeString($id)."'";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          $this->deptId = $arrayRow['dept_id']; 
          $this->deptCode = $arrayRow['dept_code']; 
          $this->deptName = $arrayRow['dept_name']; 
          $this->picInput = $arrayRow['pic_input']; 
          $this->inputTime = $arrayRow['input_time']; 
          $this->picEdit = $arrayRow['pic_edit']; 
          $this->editTime = $arrayRow['edit_time']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
          $this->deptId = ''; 
          $this->deptCode = ''; 
          $this->deptName = ''; 
          $this->picInput = ''; 
          $this->inputTime = '1700-01-01 00:00:00'; 
          $this->picEdit = ''; 
          $this->editTime = '1700-01-01 00:00:00'; 
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
          $strSql = "SELECT ";
          $strSql .= " CASE WHEN id_year = curr_ym THEN ";
          $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
          $strSql .= " ELSE ";
          $strSql .= "   CONCAT(curr_ym, '00001') ";
          $strSql .= " END AS doc_id ";
          $strSql .= "FROM ";
          $strSql .= " (SELECT ";
          $strSql .= "   MAX(".$columnId.") fi,";
          $strSql .= "   LEFT(".$columnId.",4) id_year,";
          $strSql .= "   current_date dt,";
          $strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
          $strSql .= "   CONCAT(";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
          $strSql .= "   LPAD(";
          $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
          $strSql .= "    )";
          $strSql .= "   ) curr_ym,";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
          $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
          $strSql .= " FROM ";
          $strSql .= "   ".$this->table." ";
          $strSql .= " GROUP BY ".$columnId.") a ";
          $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
          $query  = $this->db->query($strSql); 
          $arrayRow = $query->getRowArray(); 
          if(!isset($arrayRow))
          {
               $curYM = date('ym');
               $arrayRow['doc_id'] = $curYM.'00001';
          }
          return $arrayRow;
     }
     /* END OF ID GENERATOR */
     /* START GET dept ADD MANUAL BY VENNY */
      function get_dept_Active()
     {
        $stQuery = "SELECT dept_id, dept_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_Active = '1' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     } 

     function get_dept_foreign()
     {
        $stQuery = "SELECT dept_id, dept_name FROM ".$this->table." ";
        $stQuery .= "WHERE is_Active = '0' ";
        $query   = $this->db->query($stQuery);
        return $query->getResult();
     }
     /*END GET dept*/
}
