<?php

namespace App\Models\Master;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use CodeIgniter\Model;

class MtAllowance extends Model
{
    /* START PRIVATE VARIABLES */
    protected $DBGroup = '';
    protected $table = 'mt_allowance';
    protected $primaryKey = 'allowance_id';
    protected $returnType = 'array';
    protected $db = null;
    protected $protectFields = false;
    protected $useAutoIncrement = false;
    public    $timestamps       = false;

    protected $allowanceId;
    protected $clientName;
    protected $biodataId;
    protected $empName;
    protected $yearPeriod;
    protected $monthPeriod;
    protected $allowanceName;
    protected $allowanceAmount;
    protected $allowanceType;
    protected $picProcess;
    protected $processTime;
    protected $picUpdate;
    protected $processUpdate;
    /* END PRIVATE VARIABLES */

    /* START CONSTRUCTOR */
    public function __construct()
    {
        parent::__construct();

        $this->allowanceId = 0;
        $this->biodataId = 0;
        $this->clientName = '';
        $this->empName = '';
        $this->yearPeriod = 0;
        $this->monthPeriod = 0;
        $this->allowanceName = '';
        $this->allowanceAmount = 0;
        $this->allowanceType = '';
        $this->picProcess = '';
        $this->processTime = "";
        $this->picUpdate = '';
        $this->processUpdate = "";
    }
    /* END CONSTRUCTOR */
    /* START GENERATE SETTER AND GETTER */
    public function setallowanceId($params)
    {
        $this->allowanceId = $params;
    }
    public function getallowanceId()
    {
        return $this->allowanceId;
    }
    public function setbiodataId($params)
    {
        $this->biodataId = $params;
    }
    public function getbiodataId()
    {
        return $this->biodataId;
    }
    public function setclientName($params)
    {
        $this->clientName = $params;
    }
    public function getclientName()
    {
        return $this->clientName;
    }
    public function setempName($params)
    {
        $this->empName = $params;
    }
    public function getempName()
    {
        return $this->empName;
    }
    public function setyearPeriod($params)
    {
        $this->yearPeriod = $params;
    }
    public function getyearPeriod()
    {
        return $this->yearPeriod;
    }
    public function setmonthPeriod($params)
    {
        $this->monthPeriod = $params;
    }
    public function getmonthPeriod()
    {
        return $this->monthPeriod;
    }
    public function setallowanceName($params)
    {
        $this->allowanceName = $params;
    }
    public function getallowanceName()
    {
        return $this->allowanceName;
    }
    public function setallowanceAmount($params)
    {
        $this->allowanceAmount = $params;
    }
    public function getallowanceAmount()
    {
        return $this->allowanceAmount;
    }
    public function setallowanceType($params)
    {
        $this->allowanceType = $params;
    }
    public function getallowanceType()
    {
        return $this->allowanceType;
    }
    public function setpicProcess($params)
    {
        $this->picProcess = $params;
    }
    public function getpicProcess()
    {
        return $this->picProcess;
    }
    public function setprocessTime($params)
    {
        $this->processTime = $params;
    }
    public function getprocessTime()
    {
        return $this->processTime;
    }
    public function setpicUpdate($params)
    {
        $this->picUpdate = $params;
    }
    public function getpicUpdate()
    {
        return $this->picUpdate;
    }
    public function setprocessUpdate($params)
    {
        $this->processUpdate = $params;
    }
    public function getprocessUpdate()
    {
        return $this->processUpdate;
    }
    /* END GENERATE SETTER AND GETTER */

    /* START INSERT */
    public function ins()
    {
        $data = [
            'allowance_id'     => $this->allowanceId,
            'client_name'      => $this->clientName,
            'biodata_id'       => $this->biodataId,
            'emp_name'         => $this->empName,
            'year_period'      => $this->yearPeriod,
            'month_period'     => $this->monthPeriod,
            'allowance_name'   => $this->allowanceName,
            'allowance_amount' => $this->allowanceAmount,
            // 'allowance_type'   => $this->allowanceType,
            'pic_process'      => $this->picProcess,
            'process_time'     => $this->processTime,
        ];

        return $this->db->table($this->table)->insert($data);
    }
    /* END INSERT */
    public function deleteByIdPeriod($biodataId, $clientName, $year, $month, $sm)
    {
        $this->db->table($this->table)
            ->where('biodata_id', $biodataId)
            ->where('client_name', $clientName)
            ->where('year_period', $year)
            ->where('month_period', $month)
            ->where('payroll_group', $sm)
            ->delete();
    }


    public function generateNumber()
    {
        $db = \Config\Database::connect(); // jangan pakai $this->DBGroup kalau kosong
        $builder = $db->table($this->table);

        // ambil 6 digit tahun+bulan (misal 202511)
        $currYearMonth = date('Ym');

        // cari allowance_id terbesar (numeric) yang masih dalam bulan ini
        $query = $builder->select('allowance_id')
            ->like('allowance_id', $currYearMonth, 'after') // ambil yg prefix-nya bulan ini
            ->orderBy('allowance_id', 'DESC')
            ->limit(1)
            ->get()
            ->getRow();

        if ($query && isset($query->allowance_id)) {
            $lastNo = (int)substr($query->allowance_id, 6);
            $newNo = $currYearMonth . str_pad($lastNo + 1, 4, '0', STR_PAD_LEFT);
        } else {
            $newNo = $currYearMonth . '0001';
        }

        return $newNo;
    }

    public function getLastNumber()
    {
        $db = \Config\Database::connect();
        $prefix = date('Ym'); // contoh 202511

        $row = $db->table($this->table)
            ->select('allowance_id')
            ->like('allowance_id', $prefix, 'after')
            ->orderBy('allowance_id', 'DESC')
            ->limit(1)
            ->get()
            ->getRow();

        if ($row) {
            return (int)substr($row->allowance_id, 6);
        }

        return 0; // belum ada → mulai dari 0001
    }

    public function resetValues()
    {

        $this->allowanceId = 0;
        $this->biodataId = 0;
        $this->clientName = '';
        $this->empName = '';
        $this->yearPeriod = 0;
        $this->monthPeriod = 0;
        $this->allowanceName = '';
        $this->allowanceAmount = 0;
        $this->allowanceType = '';
        $this->picProcess = '';
        $this->processTime = "";
        $this->picUpdate = '';
        $this->processUpdate = "";
    }
    public function selectAllowanceAll($bioRecId, $clientName, $year, $month, $sm)
    {
        return $this->db->table($this->table)
            ->select('allowance_name, allowance_amount')
            ->where('biodata_id', $bioRecId)
            // ->where('client_name', $clientName) // aktifkan jika perlu filter client
            ->where('payroll_group', $sm)
            ->where('year_period', $year)
            ->where('month_period', $month)
            ->get()
            ->getResultArray();
    }

    public function selectAllowanceBySM($bioRecId, $clientName, $year, $month, $sm)
    {
        return $this->db->table($this->table)
            ->select([
                'allowance_name',
                'allowance_amount',
                'payroll_group',
                'remarks'
            ])
            ->where('biodata_id', $bioRecId)
            // ->where('client_name', $clientName)
            ->where('payroll_group', $sm)
            ->where('year_period', $year)
            ->where('month_period', $month)
            ->get()
            ->getResultArray();
    }


    public function getAllowanceTotal($bioRecId, $clientName, $year, $month, $sm)
    {
        // Ambil data allowance sesuai parameter
        $allowanceData = $this->selectAllowanceAll($bioRecId, $clientName, $year, $month, $sm);

        // Inisialisasi total allowance
        $allowanceTotals = [];

        foreach ($allowanceData as $allowance) {
            $name = $allowance['allowance_name'];
            $amount = $allowance['allowance_amount'];
            $allowanceTotals[$name] = ($allowanceTotals[$name] ?? 0) + $amount;
        }

        $thr                = $allowanceTotals['thr'] ?? 0;
        $tunjangan      = $allowanceTotals['tunjangan'] ?? 0;
        $nightShiftBonus      = $allowanceTotals['night_shift_bonus'] ?? 0;
        $transportBonus      = $allowanceTotals['transport_bonus'] ?? 0;
        $attendanceBonus      = $allowanceTotals['attendance_bonus'] ?? 0;
        $adjustIn           = $allowanceTotals['adjustment_in'] ?? 0;
        $adjustOut          = $allowanceTotals['adjustment_out'] ?? 0;
        $workdayAdj         = $allowanceTotals['workday_adj'] ?? 0;
        $debtBurden         = $allowanceTotals['debt_burden'] ?? 0;
        $thrByUser          = $allowanceTotals['thr_by_user'] ?? 0;
        $othersBonusByUser  = $allowanceTotals['others_bonus_by_user'] ?? 0;
        $insentif           = $allowanceTotals['insentif'] ?? 0;
        $otherAllowance     = $allowanceTotals['other_allowance'] ?? 0;

        $bonusTotal = $thr + $tunjangan + $nightShiftBonus + $transportBonus + $attendanceBonus + $insentif + $otherAllowance + $adjustIn + $adjustOut;

        return [
            'bonusTotal' => $bonusTotal,
        ];
    }


    public function updateAllowance($clientName, $biodataId, $year, $month, $allowanceName, $amount, $sm = null)
    {
        // Ambil data allowance berdasarkan parameter
        $allowance = $this->selectAllowanceByValue($biodataId, $clientName, $year, $month, $allowanceName, $sm);
        $userId = session('user_id');
        $now    = date('Y-m-d H:i:s');



        if ($allowance) {

            // Jika amount = 0 → delete (kecuali BSI_Banyuwangi)
            if ($amount == 0) {
                $this->delete($allowance['allowance_id']);
            } else if ($allowance['allowance_amount'] != $amount) {

                // Update existing allowance
                $this->update($allowance['allowance_id'], [
                    'allowance_amount' => $amount,
                    'pic_update'       => $userId,
                    'process_update'   => $now,
                ]);
            }
        } else {

            // Jika tidak ditemukan & amount != 0 → insert record baru
            if ($amount != 0) {

                // Ambil data kontrak
                $bioModel = new MtBiodata01();
                $bio = $bioModel->getDataBio($biodataId);

                $name = $bio['full_name'] ?? '';

                $this->insert([
                    'allowance_id'     => $this->generateNumber(),
                    'emp_name'         => $name,
                    'client_name'      => $clientName,
                    'biodata_id'       => $biodataId,
                    'year_period'      => $year,
                    'month_period'     => $month,
                    'allowance_name'   => $allowanceName,
                    'allowance_amount' => $amount,
                    'pic_process'      => $userId,
                    'payroll_group'    => $sm,
                    'process_time'     => $now,
                ]);
            }
        }
    }


    public function selectAllowanceByValue($biodataId, $clientName, $year, $month, $allowanceName, $sm)
    {
        return $this->where([
            'biodata_id'     => $biodataId,
            'client_name'    => $clientName,
            'year_period'    => $year,
            'month_period'   => $month,
            'allowance_name' => $allowanceName,
            'payroll_group'       => $sm,
        ])
            ->first();
    }
}
