<?php

namespace App\Models\Master;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use CodeIgniter\Model;

class MtBiodata01 extends Model
{
    /* START PRIVATE VARIABLES */
    protected $DBGroup = '';
    protected $table = 'mt_biodata_01';
    protected $primaryKey = 'biodata_id';
    protected $returnType = 'array';
    protected $db = null;

    protected $biodataId;
    protected $deptId;
    protected $fullName;
    protected $firstName;
    protected $middleName;
    protected $lastName;
    protected $placeOfBirth;
    protected $dateOfBirth;
    protected $gender;
    protected $ethnic;
    protected $nationality;
    protected $company;
    protected $dept;
    protected $empPosition;
    protected $passportNo;
    protected $placement;
    protected $approveLevel;
    protected $internalId;
    protected $positionLevel;
    protected $joinDate;
    protected $idCardNo;
    protected $idCardAddress;
    protected $currentAddress;
    protected $residenceStatus;
    protected $religion;
    protected $drivingLicense;
    protected $maritalStatus;
    protected $empHeight;
    protected $empWeight;
    protected $bloodType;
    protected $emailAddress;
    protected $telpNo;
    protected $cellNo;
    protected $isGlasses;
    protected $empStatus;
    protected $taxNo;
    protected $bpjsNo;
    protected $bpjsTkNo;
    protected $isActive;
    protected $picInput;
    protected $inputTime;
    protected $picEdit;
    protected $editTime;
    /* END PRIVATE VARIABLES */
    public function getDataBio($biodataId)
    {
        return $this->where('biodata_id', $biodataId)->first();
    }
}
