<?php

namespace App\Models\Master;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use CodeIgniter\Model;

class ProcessClossing extends Model
{
    /* START PRIVATE VARIABLES */
    protected $DBGroup = '';
    protected $table = 'mt_process_closing';
    protected $primaryKey = 'closing_id';
    protected $allowedFields = [
        'client_name',
        'close_year',
        'close_month',
        'is_active',
        // tambahkan kolom lain yang ingin di-insert/update
    ];
    protected $closingId;
    protected $clientName;
    protected $closeYear;
    protected $closeMonth;
    protected $isActive;
    /* END PRIVATE VARIABLES */
    /* START CONSTRUCTOR */
    public function __construct()
    {
        parent::__construct();
        $this->closingId = 0;
        $this->clientName = '';
        $this->closeYear = 0;
        $this->closeMonth = '';
        $this->isActive = 0;
    }
    /* END CONSTRUCTOR */

    /* START GENERATE SETTER AND GETTER */
    public function setClosingId($aClosingId)
    {
        $this->closingId = $aClosingId;
    }
    public function getClosingId()
    {
        return $this->closingId;
    }
    public function setClientName($aClientName)
    {
        $this->clientName = $aClientName;
    }
    public function getClientName()
    {
        return $this->clientName;
    }
    public function setCloseYear($aCloseYear)
    {
        $this->closeYear = $aCloseYear;
    }
    public function getCloseYear()
    {
        return $this->closeYear;
    }
    public function setCloseMonth($aCloseMonth)
    {
        $this->closeMonth = $aCloseMonth;
    }
    public function getCloseMonth()
    {
        return $this->closeMonth;
    }
    public function setIsActive($aIsActive)
    {
        $this->isActive = $aIsActive;
    }
    public function getIsActive()
    {
        return $this->isActive;
    }
    /* END GENERATE SETTER AND GETTER */
    /* START INSERT */
    public function ins()
    {
        $stQuery  = 'INSERT INTO ' . $this->table . ' ';
        $stQuery .= '( ';
        $stQuery .=   'closing_id,';
        $stQuery .=   'client_name,';
        $stQuery .=   'close_year,';
        $stQuery .=   'close_month,';
        $stQuery .=   'is_active';
        $stQuery .= ') ';
        $stQuery .= 'VALUES ';
        $stQuery .= '( ';
        $stQuery .=   $this->closingId . ',';
        $stQuery .=   '"' . $this->clientName . '",';
        $stQuery .=   $this->closeYear . ',';
        $stQuery .=   '"' . $this->closeMonth . '",';
        $stQuery .=   $this->isActive;
        $stQuery .= '); ';
        $this->db->query($stQuery);
    }
    /* END INSERT */

    /* START ADD MANUALLY */
    public function getCountByClientPeriod($clientName, $yearPeriod, $monthPeriod)
    {
        $sql  = 'SELECT closing_id FROM ' . $this->table;
        $sql .= ' WHERE client_name = "' . $clientName . '" ';
        $sql .= ' AND close_year = "' . $yearPeriod . '" ';
        $sql .= ' AND close_month = "' . $monthPeriod . '" ';
        $sql .= ' AND is_active = 1 ';

        $query = $this->db->query($sql);
        return count($query->getResult()); // ✅ works in all CI4 versions
    }
}
