<?php

namespace App\Models\Master;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use CodeIgniter\Model;
use Config\Database;

class RosterHist extends Model
{
    protected $DBGroup          = '';
    protected $table            = 'mt_roster_hist';
    protected $primaryKey       = 'rh_id';
    protected $allowedFields    = [
        'rh_id',
        'biodata_id',
        'client_name',
        'year_period',
        'month_period',
        'last_day'
    ];
    protected $useTimestamps    = false;
    protected $useAutoIncrement = false;

    /**
     * Ambil data roster berdasarkan biodata_id dan tanggal tertentu (minus 1 bulan)
     */
    public static function getTData($biodataId, $strDate)
    {
        $db = Database::connect();

        $sql = "
            SELECT *
            FROM mt_roster_hist
            WHERE biodata_id = ?
            AND DATE_ADD(?, INTERVAL -1 MONTH) = DATE_FORMAT(CONCAT(year_period, '-', month_period, '-01'), '%Y-%m-%d')
            LIMIT 1
        ";

        $query = $db->query($sql, [$biodataId, $strDate]);
        return $query->getRow(); // hasilnya object
    }

    /**
     * Reset nilai properti model
     */
    public function resetValues()
    {
        $this->attributes = [
            'rh_id' => 0,
            'biodata_id' => 0,
            'client_name' => '',
            'year_period' => 0,
            'month_period' => '',
            'last_day' => 0,
        ];
        return $this;
    }

    /**
     * Hapus data berdasarkan rh_id
     */
    public function deleteById($id)
    {
        return $this->where('rh_id', $id)->delete();
    }
}
