<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_biodata;
use App\Models\Master\M_dept;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use PhpOffice\PhpSpreadsheet\IOFactory;
$session = session();


class Biodata extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/biodata_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $mtDept = new M_dept();
         $data['data_dept'] = $mtDept->get_dept();
         $data['actView'] = 'Master/biodata_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view($biodata_id)
     {
     	$mtBiodata = new M_mt_biodata();
          $mtDept = new M_dept();
          $data['data_dept'] = $mtDept->get_dept();
          $data['mtBiodata'] = $mtBiodata->getById($biodata_id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/biodata_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {

          $localed = 0; 
          
          if($_POST['isActive'] == "Y"){
          $localed = 1; 
          }
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");
          // $isActive = '1';
          /*$db = \Config\Database::connect('hris', false);*/
          $mtBiodata = new M_mt_biodata();
          $headerId = $mtBiodata->generateId('biodata_id')['doc_id'];
          $mtBiodata->resetValues();
          $mtBiodata->setBiodataId($headerId);
          $mtBiodata->setFullName($_POST['fullName']);
          $mtBiodata->setPlaceOfBirth($_POST['placeOfBirth']);
          $mtBiodata->setDateOfBirth($_POST['dateOfBirth']);
          $mtBiodata->setGender($_POST['gender']);
          $mtBiodata->setEthnic($_POST['ethnic']);
          $mtBiodata->setNationality($_POST['nationality']);
          $mtBiodata->setDept($_POST['dept']);
          $mtBiodata->setEmpPosition($_POST['empPosition']);
          $mtBiodata->setPlacement($_POST['placement']);
          $mtBiodata->setJoinDate($_POST['joinDate']);
          $mtBiodata->setIdCardNo($_POST['idCardNo']);
          $mtBiodata->setIdCardAddress($_POST['idCardAddress']);
          $mtBiodata->setCurrentAddress($_POST['currentAddress']);
          $mtBiodata->setReligion($_POST['religion']);
          $mtBiodata->setDrivingLicense($_POST['drivingLicense']);
          $mtBiodata->setMaritalStatus($_POST['maritalStatus']);
          $mtBiodata->setEmpHeight($_POST['empHeight']);
          $mtBiodata->setEmpWeight($_POST['empWeight']);
          $mtBiodata->setBloodType($_POST['bloodType']);
          $mtBiodata->setEmailAddress($_POST['emailAddress']);
          $mtBiodata->setTelpNo($_POST['telpNo']);
          $mtBiodata->setCellNo($_POST['cellNo']);
          $mtBiodata->setIsGlasses($_POST['isGlasses']);
          $mtBiodata->setEmpStatus($_POST['empStatus']);
          $mtBiodata->setTaxNo($_POST['taxNo']);
          $mtBiodata->setBpjsNo($_POST['bpjsNo']);
          $mtBiodata->setBpjsTkNo($_POST['bpjsTkNo']);
          $mtBiodata->setIsActive($_POST['isActive']);
          $mtBiodata->setPicInput($userId);
          $mtBiodata->setInputTime($currDateTm);/*
          $mtBiodata->setPicEdit($userId]);
          $mtBiodata->setEditTime($currDateTm);*/
          $arrayList = $mtBiodata->checkByKtp($_POST['idCardNo']);
           // dd($arrayList['id_card_no']);
          // dd($arrayList[]);
          if ($arrayList > 0) {
            $jsonStatus = ['status' => false, 'message' => 'KTP sudah terdaftar!!'];
           return json_encode($jsonStatus);
          } else {
            $jsonStatus = ['status' => true, 'message' => 'Data Berhasil Ditambahkan!!'] ;
            $mtBiodata->ins();
            return json_encode($jsonStatus);
          }
          /*echo $mtBiodata;*/
     }
     
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
          $localed = 0; 
         
          
     	 $id = $_POST['BiodataId'];
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");
     	  $mtBiodata = new M_mt_biodata();
     	  $mtBiodata->setObjectById($id);
          // $mtBiodata->setFullName($_POST['fullName']);
          $mtBiodata->setPlaceOfBirth($_POST['placeOfBirth']);
          $mtBiodata->setDateOfBirth($_POST['dateOfBirth']);
          $mtBiodata->setGender($_POST['gender']);
          $mtBiodata->setEthnic($_POST['ethnic']);
          $mtBiodata->setNationality($_POST['nationality']);
          $mtBiodata->setDept($_POST['dept']);
          $mtBiodata->setEmpPosition($_POST['empPosition']);
          $mtBiodata->setPlacement($_POST['placement']);
          $mtBiodata->setJoinDate($_POST['joinDate']);
          $mtBiodata->setIdCardNo($_POST['idCardNo']);
          $mtBiodata->setIdCardAddress($_POST['idCardAddress']);
          $mtBiodata->setCurrentAddress($_POST['currentAddress']);
          $mtBiodata->setReligion($_POST['religion']);
          $mtBiodata->setDrivingLicense($_POST['drivingLicense']);
          $mtBiodata->setMaritalStatus($_POST['maritalStatus']);
          $mtBiodata->setEmpHeight($_POST['empHeight']);
          $mtBiodata->setEmpWeight($_POST['empWeight']);
          $mtBiodata->setBloodType($_POST['bloodType']);
          $mtBiodata->setEmailAddress($_POST['emailAddress']);
          $mtBiodata->setTelpNo($_POST['telpNo']);
          $mtBiodata->setCellNo($_POST['cellNo']);
          $mtBiodata->setIsGlasses($_POST['isGlasses']);
          $mtBiodata->setEmpStatus($_POST['empStatus']);
          $mtBiodata->setTaxNo($_POST['taxNo']);
          $mtBiodata->setBpjsNo($_POST['bpjsNo']);
          $mtBiodata->setBpjsTkNo($_POST['bpjsTkNo']);
          /*$mtBiodata->setPicInput($userId);
          $mtBiodata->setInputTime($currDateTm);*/
     	$mtBiodata->setPicEdit($userId);
     	$mtBiodata->setEditTime($currDateTm);
     	$mtBiodata->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
          $mtBiodata = new M_mt_biodata();
          $id = $_POST['id'];
          $mtBiodata->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
          $mtBiodata = new M_mt_biodata();
          $rs = $mtBiodata->getAll();
          return json_encode($rs);
     }
     public function getAll1()
     {
          $mtBiodata = new M_mt_biodata();
          $rs = $mtBiodata->getAll1();
          return json_encode($rs);
     }

     /* END GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('Master/biodata'));
            
        }
     }
     
     public function printBiodata()
     {
     	 // Create new Spreadsheet object

        $mtBiodata = new M_mt_biodata();
        // echo $depart;
        // exit();
        
        // echo ($dept);
        // exit();
        $data = $mtBiodata->getAll();
         $spreadsheet = new Spreadsheet();  

         $spreadsheet->getProperties()->setCreator('Maurice - Web - Android')
            ->setLastModifiedBy('Maurice - Web - Android')
            ->setTitle('Office 2007 XLSX Test Document')
            ->setSubject('Office 2007 XLSX Test Document')
            ->setDescription('Test document for Office 2007 XLSX, generated using PHP classes.')
            ->setKeywords('office 2007 openxml php')
            ->setCategory('Test result file');

        $boldFont = [
            'font' => [
                'bold' => true
                // 'color' => ['argb' => '0000FF'],
            ],
        ];

        $totalStyle = [
            'font' => [
                'bold' => true,
                'color' => ['argb' => '0000FF'],
            ],
        ];

        $allBorderStyle = [
            'borders' => [
                'allBorders' => [
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => ['argb' => '00000000'],
                ],
            ],
        ];

        $outlineBorderStyle = [
            'borders' => [
                'outline' => [
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => ['argb' => '00000000'],
                ],
            ],
        ];

        $topBorderStyle = [
            'borders' => [
                'top' => [
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => ['argb' => '00000000'],
                ],
            ],
        ];

        $bottomBorderStyle = [
            'borders' => [
                'bottom' => [
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => ['argb' => '00000000'],
                ],
            ],
        ];

        $center = array();
        $center['alignment'] = array();
        $center['alignment']['horizontal'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER; 
        $center['alignment']['vertical'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER; 

        $right = array();
        $right['alignment'] = array();
        $right['alignment']['horizontal'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT; 
        $right['alignment']['vertical'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER;

        $left = array();
        $left['alignment'] = array();
        $left['alignment']['horizontal'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_LEFT; 
        $left['alignment']['vertical'] = \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER;

        

        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 1, 'SUMMARY INVOICE PT SANGATI SOERYA SEJAHTERA - PT. Agincourt Resources Martabe Gold Mine');
        $spreadsheet->getActiveSheet()->mergeCells("A1:AC1");
        $spreadsheet->getActiveSheet()->getStyle("A1:AC1")->applyFromArray($center);
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 2, 'PT. PONTIL');
        // $spreadsheet->getActiveSheet()->mergeCells("A2:U2");
        // $spreadsheet->getActiveSheet()->getStyle("A2:U2")->applyFromArray($center);
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 2, 'PERIOD : '.$monthPeriod.'-'.$yearPeriod);
        //$spreadsheet->getActiveSheet()->mergeCells("A2:AC2");
        //$spreadsheet->getActiveSheet()->getStyle("A2:AC2")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("A1:D1")->getFont()->setBold(true)->setSize(16);
        //$spreadsheet->getActiveSheet()->getStyle("A2:D2")->getFont()->setBold(true)->setSize(13);
        //$spreadsheet->getActiveSheet()->getStyle("A3:G5")->getFont()->setBold(true)->setSize(12); 
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 3, 'DATE        : ');
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 4, 'INVOICE NO  : ');
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(0, 5, 'CONTRACT NO : ');        

        /* SET HEADER BG COLOR*/
        $spreadsheet->getActiveSheet()->getStyle('A4:AC4')
            ->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()
            ->setRGB('F2BE6B'); 

        /* START INVOICE TITLE */
        $spreadsheet->getActiveSheet()->getStyle("A4:AC4")->getFont()->setSize(12);

        $spreadsheet->getActiveSheet()->getStyle("A4:A4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("B4:B4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("C4:C4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("D4:D4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("E4:E4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("F4:F4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("G4:G4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("H4:H4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("I4:I4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("J4:J4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("K4:K4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("L4:L4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("M4:M4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("N4:N4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("O4:O4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("P4:P4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("Q4:Q4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("R4:R4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("S4:S4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("T4:T4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("U4:U4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("V4:V4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("W4:W4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("X4:X4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("Y4:Y4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("Z4:Z4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("AA4:AA4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("AB4:AB4")->applyFromArray($allBorderStyle);
        $spreadsheet->getActiveSheet()->getStyle("AC4:AC4")->applyFromArray($allBorderStyle);


        $spreadsheet->getActiveSheet()->getStyle("A4:A4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("B4:B4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("C4:C4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("D4:D4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("F4:F4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("G4:G4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("H4:H4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("I4:I4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("J4:J4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("K4:K4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("L4:L4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("M4:M4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("N4:N4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("O4:O4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("P4:P4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("Q4:Q4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("R4:R4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("S4:S4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("T4:T4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("U4:U4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("V4:V4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("W4:W4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("X4:X4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("Y4:Y4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("Z4:Z4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("AA4:AA4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("AB4:AB4")->applyFromArray($center);
        $spreadsheet->getActiveSheet()->getStyle("AC4:AC4")->applyFromArray($center);

        $spreadsheet->getActiveSheet()->getStyle("B4:B4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("C4:C4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("F4:F4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("G4:G4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("H4:H4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("I4:I4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("J4:J4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("K4:K4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("L4:L4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("M4:M4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("N4:N4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("O4:O4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("P4:P4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("Q4:Q4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("R4:R4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("S4:S4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("T4:T4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("U4:U4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("V4:V4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("W4:W4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("X4:X4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("Y4:Y4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("Z4:Z4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("AA4:AA4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("AB4:AB4")->getAlignment()->setWrapText(true);
        $spreadsheet->getActiveSheet()->getStyle("AC4:AC4")->getAlignment()->setWrapText(true);

        $spreadsheet->getActiveSheet()->getStyle("A4:AC4")->applyFromArray($outlineBorderStyle);

        $spreadsheet->getActiveSheet()->mergeCells("A4:A4");
        $spreadsheet->getActiveSheet()->mergeCells("B4:B4");
        $spreadsheet->getActiveSheet()->mergeCells("C4:C4");
        $spreadsheet->getActiveSheet()->mergeCells("D4:D4");
        $spreadsheet->getActiveSheet()->mergeCells("F4:F4");
        $spreadsheet->getActiveSheet()->mergeCells("G4:G4");
        $spreadsheet->getActiveSheet()->mergeCells("H4:H4");
        $spreadsheet->getActiveSheet()->mergeCells("I4:I4");
        $spreadsheet->getActiveSheet()->mergeCells("J4:J4");
        $spreadsheet->getActiveSheet()->mergeCells("K4:K4");
        $spreadsheet->getActiveSheet()->mergeCells("M4:M4");
        $spreadsheet->getActiveSheet()->mergeCells("N4:N4");
        $spreadsheet->getActiveSheet()->mergeCells("O4:O4");
        $spreadsheet->getActiveSheet()->mergeCells("P4:P4");
        $spreadsheet->getActiveSheet()->mergeCells("Q4:Q4");
        $spreadsheet->getActiveSheet()->mergeCells("R4:R4");
        $spreadsheet->getActiveSheet()->mergeCells("S4:S4");
        $spreadsheet->getActiveSheet()->mergeCells("T4:T4");
        $spreadsheet->getActiveSheet()->mergeCells("U4:U4");
        $spreadsheet->getActiveSheet()->mergeCells("V4:V4");
        $spreadsheet->getActiveSheet()->mergeCells("W4:W4");
        $spreadsheet->getActiveSheet()->mergeCells("X4:X4");
        $spreadsheet->getActiveSheet()->mergeCells("Y4:Y4");
        $spreadsheet->getActiveSheet()->mergeCells("Z4:Z4");
        $spreadsheet->getActiveSheet()->mergeCells("AA4:AA4");
        $spreadsheet->getActiveSheet()->mergeCells("AB4:AB4");
        $spreadsheet->getActiveSheet()->mergeCells("AC4:AC4");

        $total = 0;
        $rounded = 0;
        $gaji = 0;
        $dana = 0;
        

        $spreadsheet->getActiveSheet()
                ->setCellValue('A4', 'NO')
                ->setCellValue('B4', 'BIODATA ID')
                ->setCellValue('C4', 'FULL NAME')
                ->setCellValue('D4', 'Place Of Birth')
                ->setCellValue('E4', 'Date Of Birth')
                ->setCellValue('F4', 'Gender')
                ->setCellValue('G4', 'Ethnic')
                ->setCellValue('H4', 'Nationality')
                ->setCellValue('I4', 'Dept')
                ->setCellValue('J4', 'Position')
                ->setCellValue('K4', 'Placement')
                ->setCellValue('L4', 'Join Date')
                ->setCellValue('M4', 'ID Card Number')
                ->setCellValue('N4', 'Id Card Address')
                ->setCellValue('O4', 'Current Address')
                ->setCellValue('P4', 'Religion')
                ->setCellValue('Q4', 'Driving License')
                ->setCellValue('R4', 'Marital Status')
                ->setCellValue('S4', 'Height')
                ->setCellValue('T4', 'Weight')
                ->setCellValue('U4', 'Blood Type')
                ->setCellValue('V4', 'Email')
                ->setCellValue('W4', 'Telp No')
                ->setCellValue('X4', 'Cell No')
                ->setCellValue('Y4', 'Glasses')
                ->setCellValue('Z4', 'Emp Status')
                ->setCellValue('AA4', 'Tax No')
                ->setCellValue('AB4', 'BPJS No')
                ->setCellValue('AC4', 'BPJS TK No')
                ;

        /* START TOTAL WORK HOUR */     

        $rowIdx = 5;
        $startIdx = $rowIdx; 
        $rowNo = 0;
        $totalbasic = 0;
        $totalott = 0;
        $totalnshift = 0;
        $totaljkkjkm  = 0;
        $totalshift = 0;
        $totalbpjs1 = 0;
        $totalthr = 0;
        $totaldanakonpen = 0;
        $totaljkkjkm = 0;
        $totaljkkjkm1 = 0;
        $totalbpjs = 0;
        $totaljhtjp = 0;
        $totalpph21 = 0;
        $totaladjustmen = 0;
        $totaltotal = 0;
        $totalround = 0;
        $totalgaaji = 0;

        foreach ($data as $row) {
            $rowIdx++;
            $rowNo++;
        

        


            $spreadsheet->getActiveSheet()
                ->setCellValue('A'.$rowIdx, $rowNo)
                ->setCellValue('B'.$rowIdx, $row['biodata_id']) 
                ->setCellValue('C'.$rowIdx, $row['full_name'])
                ->setCellValue('D'.$rowIdx, $row['place_of_birth'])
                ->setCellValue('E'.$rowIdx, $row['date_of_birth'])
                ->setCellValue('F'.$rowIdx, $row['gender'])
                ->setCellValue('G'.$rowIdx, $row['ethnic'])
                ->setCellValue('H'.$rowIdx, $row['nationality'])
                ->setCellValue('I'.$rowIdx, $row['dept'])
                ->setCellValue('J'.$rowIdx, $row['emp_position'])
                ->setCellValue('K'.$rowIdx, $row['placement'])
                ->setCellValue('L'.$rowIdx, $row['join_date'])
                ->setCellValue('M'.$rowIdx, $row['id_card_no'])
                ->setCellValue('N'.$rowIdx, $row['id_card_address'])
                ->setCellValue('O'.$rowIdx, $row['current_address'])
                ->setCellValue('P'.$rowIdx, $row['religion'])
                ->setCellValue('Q'.$rowIdx, $row['driving_license'])
                ->setCellValue('R'.$rowIdx, $row['marital_status'])
                ->setCellValue('S'.$rowIdx, $row['emp_height'])
                ->setCellValue('T'.$rowIdx, $row['emp_weight'])
                ->setCellValue('U'.$rowIdx, $row['blood_type'])
                ->setCellValue('V'.$rowIdx, $row['email_address'])
                ->setCellValue('W'.$rowIdx, $row['telp_no'])
                ->setCellValue('X'.$rowIdx, $row['cell_no'])
                ->setCellValue('Y'.$rowIdx, $row['is_glasses'])
                ->setCellValue('Z'.$rowIdx, $row['emp_status'])
                ->setCellValue('AA'.$rowIdx, $row['tax_no'])
                ->setCellValue('AB'.$rowIdx, $row['bpjs_no'])
                ->setCellValue('AC'.$rowIdx, $row['bpjs_tk_no'])
                ;

            $spreadsheet->getActiveSheet()->getStyle("A".$rowIdx.":AC".$rowIdx)->applyFromArray($outlineBorderStyle);
            $spreadsheet->getActiveSheet()->getStyle("A".$rowIdx.":AC".$rowIdx)->applyFromArray($allBorderStyle);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, $rowIdx, $rowNo);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, $rowIdx, $row['name']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, $rowIdx, $row['job_desc']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, $rowIdx, $row['basic_salary']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(4, $rowIdx, $row['rate']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(5, $rowIdx, $row['normal_d']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(6, $rowIdx, $row['ot_count1']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $rowIdx, $row['ot_count2']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(8, $rowIdx, $row['ot_count3']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(9, $rowIdx, $row['ot_count4']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(10, $rowIdx, $row['worked_hours']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(11, $rowIdx, $row['current_salary']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, $rowIdx, $row['ot_total']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(13, $rowIdx, $row['travel_bonus']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(14, $rowIdx, $gross);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(12, $rowIdx, $row['uplift']);
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(15, $rowIdx, '=IF(K'.$rowIdx.'<=312,((E'.$rowIdx.'*K'.$rowIdx.')*64%),((E'.$rowIdx.'*312)*64%))');
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(7, $rowIdx, '1');
            // $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(16, $rowIdx, $chargeTotal);
            /* SET ROW COLOR */
            if($rowIdx % 2 == 1)
            {
                $spreadsheet->getActiveSheet()->getStyle('A'.$rowIdx.':AC'.$rowIdx)
                    ->getFill()
                    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
                    ->getStartColor()
                    ->setRGB('EAEBAF');             
            } 

        
        $spreadsheet->getActiveSheet()
                ->setCellValue('A1', 'LIST KARYAWAN PT SANGATI SOERYA SEJAHTERA - PT '.'AGINCOURT MARTABE RESOURCES');
    } /* end foreach ($query as $row) */
        
       

        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(2, ($rowIdx+2), "TOTAL");
        // $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(16, ($rowIdx+2), "=SUM(Q".$startIdx.":Q".$rowIdx.")");
        
        /* SET NUMBERS FORMAT*/
        
        unset($allBorderStyle);
        unset($center);
        unset($right);
        unset($left);
        
        $spreadsheet->setActiveSheetIndex(0);
        $datenow = date('Y-m-d');
        $str = 'LISTKARYAWANAGR'.$datenow;
        $fileName = preg_replace('/\s+/', '', $str);

        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$fileName.'.Xlsx"');
        // header('Content-Disposition: attachment;filename="Report Excel.xlsx"');
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');

        // If you're serving to IE over SSL, then the following may be needed
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
        header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header('Pragma: public'); // HTTP/1.0
        /* BY COMPOSER */
        // $writer = new Xlsx($spreadsheet);
        /* OFFLINE/ BY COPY EXCEL FOLDER  */
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->save('php://output');
        exit(0);
     }}
?>
