<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Aug 18, 2020                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_currency_rate;

$session = session();
class Mt_currency_rate extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/currency_view';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/currency_ins';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view($cr_id)
     {
     	$mtCurrency = new M_currency_rate();
          $data['mtCurrency'] = $mtCurrency->getById($cr_id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/currency_upd';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function insData()
     {
          $mtCurrency = new M_currency_rate();

          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");

          // $actived = 0; 
          
          // if($_POST['isActive'] == "Y"){
          // $actived = 1; 
          // }
     	
          $headerId = $mtCurrency->generateId('cr_id')['doc_id'];

     	$mtCurrency->resetValues();
     	$mtCurrency->setCrId($headerId);
     	$mtCurrency->setCrCode($_POST['crCode']);
     	$mtCurrency->setCrCountry($_POST['crCountry']);
          $mtCurrency->setRateValue($_POST['rateValue']);
     	$mtCurrency->setPicData($userId);
     	$mtCurrency->setDataTime($currDateTm);
     	$mtCurrency->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function editData()
     {
     	$id = $_POST['crId'];

     	$mtCurrency = new M_currency_rate();
          $userId = $_SESSION['uId'];
          $currDateTm = date("Y-m-d H:i:s");

          
          // else if($_POST['isLocal'] == "T"){
          // $localed = 0; 
          // }

     	// $mtCurrency->setObjectById($id);
     	// $mtCurrency->setCrId($_POST['crId']);
          $mtCurrency->setCrCode($_POST['crCode']);
          $mtCurrency->setCrCountry($_POST['crCountry']);
          $mtCurrency->setRateValue($_POST['rateValue']);
          $mtCurrency->setPicData($userId);
          $mtCurrency->setDataTime($currDateTm);
     	$mtCurrency->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtCurrency = new M_mt_bank();
     	$id = $_POST['bankId'];
     	$mtCurrency->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtCurrency = new M_currency_rate();
     	$rs = $mtCurrency->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/Mt_currency_rate'));
            
        }
     }
    
}
?>
