<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created date     : Aug 18, 2020                                 *
 *  description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_dept;

$session = session();
class Mt_dept extends BaseController
{
     /* START INdEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/dept_view';
         return view('home', $data);
     }
     /* ENd INdEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = 'Master/dept_ins';
         return view('home', $data);
     }
     /* ENd INPUT FUNCTION */
     /* START UPdATE FUNCTION */
     public function upd_view($dept_id)
     {
          $mtdept = new M_dept();
          $data['mtdept'] = $mtdept->getById($dept_id);
          /* ***Using Valid Path */
          $data['actView'] = 'Master/dept_upd';
          return view('home', $data);
     }
     /* ENd UPdATE FUNCTION */
     /* START INSERT */
     public function insdata()
     {
          $userId = $_SESSION['uId'];
          $currdateTm = date("Y-m-d H:i:s");

          $localed = 1; 
          
          // if($_POST['isActive'] == "Y"){
          // $localed = 1; 
          // }

          $mtdept = new M_dept();
          $mtdept->resetValues();
          // $mtdept->setdeptId($_POST['deptId']);
          // $mtdept->setdeptCode($_POST['deptCode']);
          $mtdept->setdeptName($_POST['deptName']);
          $mtdept->setIsActive($localed);
          $mtdept->setPicInput($userId);
          $mtdept->setInputTime($currdateTm);
          $mtdept->ins();
     }
     /* ENd INSERT */
     /* START UPdATE */
     public function editdata()
     {
          $id = $_POST['deptId'];

          $mtdept = new M_dept();
          $userId = $_SESSION['uId'];
          $currdateTm = date("Y-m-d H:i:s");

          $localed = 0; 
          
          if($_POST['isActive'] == "Y"){
          $localed = 1; 
          }
          // else if($_POST['isActive'] == "T"){
          // $localed = 0; 
          // }

          $mtdept->setObjectById($id);
          $mtdept->setdeptId($_POST['deptId']);
          $mtdept->setdeptCode($_POST['deptCode']);
          $mtdept->setdeptName($_POST['deptName']);
          $mtdept->setIsActive($localed);
          $mtdept->setPicEdit($userId);
          $mtdept->setEditTime($currdateTm);
          $mtdept->upd($id);
     }
     /* ENd UPdATE */
     /* START dELETE */
     public function del()
     {
          $mtdept = new M_dept();
          $id = $_POST['id'];
          $mtdept->del($id);
     }
     /* ENd dELETE */
     /* START GET ALL */
     public function getAll()
     {
          $mtdept = new M_dept();
          $rs = $mtdept->getAll();
          return json_encode($rs); 
     }
     /* ENd GET ALL */
     public function reset()
     {
          /*Clear Session*/
          if (!(isset($_SESSION['unset_userdata']))) {

            return redirect()->to(base_url('master/mt_dept'));
            
        }
     }
    
}
?>
