<?php namespace App\Models\Transaction; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Apr 06, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_tr_timesheet extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = '';
     protected $table = 'tr_timesheet';
     protected $primaryKey = 'ts_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $tsId;
     protected $biodataId;
     protected $badgeNo;
     protected $fullName;
     protected $payrollGroup;
     protected $clientName;
     protected $dept;
     protected $startDate;
     protected $monthProcess;
     protected $yearProcess;
     protected $passDay;
     protected $d01;
     protected $d02;
     protected $d03;
     protected $d04;
     protected $d05;
     protected $d06;
     protected $d07;
     protected $d08;
     protected $d09;
     protected $d10;
     protected $d11;
     protected $d12;
     protected $d13;
     protected $d14;
     protected $d15;
     protected $d16;
     protected $d17;
     protected $d18;
     protected $d19;
     protected $d20;
     protected $d21;
     protected $d22;
     protected $d23;
     protected $d24;
     protected $d25;
     protected $d26;
     protected $d27;
     protected $d28;
     protected $d29;
     protected $d30;
     protected $d31;
     protected $isActive;
     protected $picProcess;
     protected $processTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
          parent::__construct();
          $this->db = \Config\Database::connect($this->DBGroup, false);
          $this->tsId = 0;
          $this->biodataId = '';
          $this->badgeNo = '';
          $this->fullName = '';
          $this->payrollGroup= '';
          $this->clientName = '';
          $this->dept = '';
          $this->startDate = '';
          $this->monthProcess = '';
          $this->yearProcess = 0;
          $this->periodNo = 0;
          $this->passDay = 0;
          $this->d01 = '';
          $this->d02 = '';
          $this->d03 = '';
          $this->d04 = '';
          $this->d05 = '';
          $this->d06 = '';
          $this->d07 = '';
          $this->d08 = '';
          $this->d09 = '';
          $this->d10 = '';
          $this->d11 = '';
          $this->d12 = '';
          $this->d13 = '';
          $this->d14 = '';
          $this->d15 = '';
          $this->d16 = '';
          $this->d17 = '';
          $this->d18 = '';
          $this->d19 = '';
          $this->d20 = '';
          $this->d21 = '';
          $this->d22 = '';
          $this->d23 = '';
          $this->d24 = '';
          $this->d25 = '';
          $this->d26 = '';
          $this->d27 = '';
          $this->d28 = '';
          $this->d29 = '';
          $this->d30 = '';
          $this->d31 = '';
          $this->isActive = 0;
          $this->picProcess = '';
          $this->processTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setTsId($aTsId)
     {
          $this->tsId = $aTsId;
     }
     public function getTsId()
     {
          return $this->tsId;
     }
     public function setBiodataId($aBiodataId)
     {
          $this->biodataId = $aBiodataId;
     }
     public function getBiodataId()
     {
          return $this->biodataId;
     }
     public function setBadgeNo($aBadgeNo)
     {
          $this->badgeNo = $aBadgeNo;
     }
     public function getBadgeNo()
     {
          return $this->badgeNo;
     }
     public function setFullName($aFullName)
     {
          $this->fullName = $aFullName;
     }
     public function getFullName()
     {
          return $this->fullName;
     }
     public function setpayrollGroup($apayrollGroup)
     {
          $this->payrollGroup= $apayrollGroup;
     }
     public function getpayrollGroup()
     {
          return $this->payrollGroup;
     }
     public function setClientName($aClientName)
     {
          $this->clientName = $aClientName;
     }
     public function getClientName()
     {
          return $this->clientName;
     }
     public function setDept($aDept)
     {
          $this->dept = $aDept;
     }
     public function getDept()
     {
          return $this->dept;
     }
     public function setstartDate($astartDate)
     {
          $this->startDate = $astartDate;
     }
     public function getstartDate()
     {
          return $this->startDate;
     }
     public function setMonthProcess($aMonthProcess)
     {
          $this->monthProcess = $aMonthProcess;
     }
     public function getMonthProcess()
     {
          return $this->monthProcess;
     }
     public function setYearProcess($aYearProcess)
     {
          $this->yearProcess = $aYearProcess;
     }
     public function getYearProcess()
     {
          return $this->yearProcess;
     }
     public function setPeriodNo($aPeriodNo)
     {
          $this->periodNo = $aPeriodNo;
     }
     public function getPeriodNo()
     {
          return $this->periodNo;
     }
     public function setPassDay($aPassDay)
     {
          $this->passDay = $aPassDay;
     }
     public function getPassDay()
     {
          return $this->passDay;
     }
     public function setD01($aD01)
     {
          $this->d01 = $aD01;
     }
     public function getD01()
     {
          return $this->d01;
     }
     public function setD02($aD02)
     {
          $this->d02 = $aD02;
     }
     public function getD02()
     {
          return $this->d02;
     }
     public function setD03($aD03)
     {
          $this->d03 = $aD03;
     }
     public function getD03()
     {
          return $this->d03;
     }
     public function setD04($aD04)
     {
          $this->d04 = $aD04;
     }
     public function getD04()
     {
          return $this->d04;
     }
     public function setD05($aD05)
     {
          $this->d05 = $aD05;
     }
     public function getD05()
     {
          return $this->d05;
     }
     public function setD06($aD06)
     {
          $this->d06 = $aD06;
     }
     public function getD06()
     {
          return $this->d06;
     }
     public function setD07($aD07)
     {
          $this->d07 = $aD07;
     }
     public function getD07()
     {
          return $this->d07;
     }
     public function setD08($aD08)
     {
          $this->d08 = $aD08;
     }
     public function getD08()
     {
          return $this->d08;
     }
     public function setD09($aD09)
     {
          $this->d09 = $aD09;
     }
     public function getD09()
     {
          return $this->d09;
     }
     public function setD10($aD10)
     {
          $this->d10 = $aD10;
     }
     public function getD10()
     {
          return $this->d10;
     }
     public function setD11($aD11)
     {
          $this->d11 = $aD11;
     }
     public function getD11()
     {
          return $this->d11;
     }
     public function setD12($aD12)
     {
          $this->d12 = $aD12;
     }
     public function getD12()
     {
          return $this->d12;
     }
     public function setD13($aD13)
     {
          $this->d13 = $aD13;
     }
     public function getD13()
     {
          return $this->d13;
     }
     public function setD14($aD14)
     {
          $this->d14 = $aD14;
     }
     public function getD14()
     {
          return $this->d14;
     }
     public function setD15($aD15)
     {
          $this->d15 = $aD15;
     }
     public function getD15()
     {
          return $this->d15;
     }
     public function setD16($aD16)
     {
          $this->d16 = $aD16;
     }
     public function getD16()
     {
          return $this->d16;
     }
     public function setD17($aD17)
     {
          $this->d17 = $aD17;
     }
     public function getD17()
     {
          return $this->d17;
     }
     public function setD18($aD18)
     {
          $this->d18 = $aD18;
     }
     public function getD18()
     {
          return $this->d18;
     }
     public function setD19($aD19)
     {
          $this->d19 = $aD19;
     }
     public function getD19()
     {
          return $this->d19;
     }
     public function setD20($aD20)
     {
          $this->d20 = $aD20;
     }
     public function getD20()
     {
          return $this->d20;
     }
     public function setD21($aD21)
     {
          $this->d21 = $aD21;
     }
     public function getD21()
     {
          return $this->d21;
     }
     public function setD22($aD22)
     {
          $this->d22 = $aD22;
     }
     public function getD22()
     {
          return $this->d22;
     }
     public function setD23($aD23)
     {
          $this->d23 = $aD23;
     }
     public function getD23()
     {
          return $this->d23;
     }
     public function setD24($aD24)
     {
          $this->d24 = $aD24;
     }
     public function getD24()
     {
          return $this->d24;
     }
     public function setD25($aD25)
     {
          $this->d25 = $aD25;
     }
     public function getD25()
     {
          return $this->d25;
     }
     public function setD26($aD26)
     {
          $this->d26 = $aD26;
     }
     public function getD26()
     {
          return $this->d26;
     }
     public function setD27($aD27)
     {
          $this->d27 = $aD27;
     }
     public function getD27()
     {
          return $this->d27;
     }
     public function setD28($aD28)
     {
          $this->d28 = $aD28;
     }
     public function getD28()
     {
          return $this->d28;
     }
     public function setD29($aD29)
     {
          $this->d29 = $aD29;
     }
     public function getD29()
     {
          return $this->d29;
     }
     public function setD30($aD30)
     {
          $this->d30 = $aD30;
     }
     public function getD30()
     {
          return $this->d30;
     }
     public function setD31($aD31)
     {
          $this->d31 = $aD31;
     }
     public function getD31()
     {
          return $this->d31;
     }
     public function setIsActive($aIsActive)
     {
          $this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
          return $this->isActive;
     }
     public function setPicProcess($aPicProcess)
     {
          $this->picProcess = $aPicProcess;
     }
     public function getPicProcess()
     {
          return $this->picProcess;
     }
     public function setProcessTime($aProcessTime)
     {
          $this->processTime = $aProcessTime;
     }
     public function getProcessTime()
     {
          return $this->processTime;
     }
     public function setbankId($abankId)
     {
          $this->bankId = $abankId;
     }
     public function getbankId()
     {
          return $this->bankId;
     }

     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
          if($this->tsId =="" || $this->tsId == NULL) 
          {
               $this->tsId = 0; 
          }
          if($this->biodataId =="" || $this->biodataId == NULL) 
          {
               $this->biodataId = ''; 
          }
          if($this->badgeNo =="" || $this->badgeNo == NULL) 
          {
               $this->badgeNo = ''; 
          }
          if($this->fullName =="" || $this->fullName == NULL) 
          {
               $this->fullName = ''; 
          }
          if($this->payrollGroup=="" || $this->payrollGroup== NULL) 
          {
               $this->payrollGroup= ''; 
          }
          if($this->clientName =="" || $this->clientName == NULL) 
          {
               $this->clientName = ''; 
          }
          if($this->dept =="" || $this->dept == NULL) 
          {
               $this->dept = ''; 
          }
          if($this->startDate =="" || $this->startDate == NULL) 
          {
               $this->startDate = ''; 
          }
          if($this->monthProcess =="" || $this->monthProcess == NULL) 
          {
               $this->monthProcess = ''; 
          }
          if($this->yearProcess =="" || $this->yearProcess == NULL) 
          {
               $this->yearProcess = 0; 
          }
          if($this->periodNo =="" || $this->periodNo == NULL) 
          {
               $this->periodNo = 0; 
          }
          if($this->passDay =="" || $this->passDay == NULL) 
          {
               $this->passDay = 0; 
          }
          if($this->d01 =="" || $this->d01 == NULL) 
          {
               $this->d01 = ''; 
          }
          if($this->d02 =="" || $this->d02 == NULL) 
          {
               $this->d02 = ''; 
          }
          if($this->d03 =="" || $this->d03 == NULL) 
          {
               $this->d03 = ''; 
          }
          if($this->d04 =="" || $this->d04 == NULL) 
          {
               $this->d04 = ''; 
          }
          if($this->d05 =="" || $this->d05 == NULL) 
          {
               $this->d05 = ''; 
          }
          if($this->d06 =="" || $this->d06 == NULL) 
          {
               $this->d06 = ''; 
          }
          if($this->d07 =="" || $this->d07 == NULL) 
          {
               $this->d07 = ''; 
          }
          if($this->d08 =="" || $this->d08 == NULL) 
          {
               $this->d08 = ''; 
          }
          if($this->d09 =="" || $this->d09 == NULL) 
          {
               $this->d09 = ''; 
          }
          if($this->d10 =="" || $this->d10 == NULL) 
          {
               $this->d10 = ''; 
          }
          if($this->d11 =="" || $this->d11 == NULL) 
          {
               $this->d11 = ''; 
          }
          if($this->d12 =="" || $this->d12 == NULL) 
          {
               $this->d12 = ''; 
          }
          if($this->d13 =="" || $this->d13 == NULL) 
          {
               $this->d13 = ''; 
          }
          if($this->d14 =="" || $this->d14 == NULL) 
          {
               $this->d14 = ''; 
          }
          if($this->d15 =="" || $this->d15 == NULL) 
          {
               $this->d15 = ''; 
          }
          if($this->d16 =="" || $this->d16 == NULL) 
          {
               $this->d16 = ''; 
          }
          if($this->d17 =="" || $this->d17 == NULL) 
          {
               $this->d17 = ''; 
          }
          if($this->d18 =="" || $this->d18 == NULL) 
          {
               $this->d18 = ''; 
          }
          if($this->d19 =="" || $this->d19 == NULL) 
          {
               $this->d19 = ''; 
          }
          if($this->d20 =="" || $this->d20 == NULL) 
          {
               $this->d20 = ''; 
          }
          if($this->d21 =="" || $this->d21 == NULL) 
          {
               $this->d21 = ''; 
          }
          if($this->d22 =="" || $this->d22 == NULL) 
          {
               $this->d22 = ''; 
          }
          if($this->d23 =="" || $this->d23 == NULL) 
          {
               $this->d23 = ''; 
          }
          if($this->d24 =="" || $this->d24 == NULL) 
          {
               $this->d24 = ''; 
          }
          if($this->d25 =="" || $this->d25 == NULL) 
          {
               $this->d25 = ''; 
          }
          if($this->d26 =="" || $this->d26 == NULL) 
          {
               $this->d26 = ''; 
          }
          if($this->d27 =="" || $this->d27 == NULL) 
          {
               $this->d27 = ''; 
          }
          if($this->d28 =="" || $this->d28 == NULL) 
          {
               $this->d28 = ''; 
          }
          if($this->d29 =="" || $this->d29 == NULL) 
          {
               $this->d29 = ''; 
          }
          if($this->d30 =="" || $this->d30 == NULL) 
          {
               $this->d30 = ''; 
          }
          if($this->d31 =="" || $this->d31 == NULL) 
          {
               $this->d31 = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picProcess =="" || $this->picProcess == NULL) 
          {
               $this->picProcess = ''; 
          }
          if($this->processTime =="" || $this->processTime == NULL) 
          {
               $this->processTime = '1700-01-01 00:00:00'; 
          }
	  if($this->bankId =="" || $this->bankId == NULL) 
          {
               $this->bankId = 0; 
          }

          $stQuery  = "REPLACE INTO ".$this->table." ";
          $stQuery .= "( ";
          $stQuery .=   "ts_id,"; 
          $stQuery .=   "biodata_id,"; 
          $stQuery .=   "badge_no,"; 
          $stQuery .=   "full_name,"; 
          $stQuery .=   "payroll_group,"; 
          $stQuery .=   "client_name,"; 
          $stQuery .=   "dept,"; 
          $stQuery .=   "start_date,";
          $stQuery .=   "month_process,"; 
          $stQuery .=   "year_process,"; 
          $stQuery .=   "period_no,"; 
          $stQuery .=   "pass_day,"; 
          $stQuery .=   "d01,"; 
          $stQuery .=   "d02,"; 
          $stQuery .=   "d03,"; 
          $stQuery .=   "d04,"; 
          $stQuery .=   "d05,"; 
          $stQuery .=   "d06,"; 
          $stQuery .=   "d07,"; 
          $stQuery .=   "d08,"; 
          $stQuery .=   "d09,"; 
          $stQuery .=   "d10,"; 
          $stQuery .=   "d11,"; 
          $stQuery .=   "d12,"; 
          $stQuery .=   "d13,"; 
          $stQuery .=   "d14,"; 
          $stQuery .=   "d15,"; 
          $stQuery .=   "d16,"; 
          $stQuery .=   "d17,"; 
          $stQuery .=   "d18,"; 
          $stQuery .=   "d19,"; 
          $stQuery .=   "d20,"; 
          $stQuery .=   "d21,"; 
          $stQuery .=   "d22,"; 
          $stQuery .=   "d23,"; 
          $stQuery .=   "d24,"; 
          $stQuery .=   "d25,"; 
          $stQuery .=   "d26,"; 
          $stQuery .=   "d27,"; 
          $stQuery .=   "d28,"; 
          $stQuery .=   "d29,"; 
          $stQuery .=   "d30,"; 
          $stQuery .=   "d31,"; 
          $stQuery .=   "is_active,"; 
          $stQuery .=   "pic_process,"; 
          $stQuery .=   "process_time,";
	  $stQuery .=   "bank_id";  
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          $stQuery .=   " ".$this->tsId.",";
          $stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->badgeNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->fullName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->payrollGroup)."',";
          $stQuery .=   "'".$this->db->escapeString($this->clientName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->dept)."',";
          $stQuery .=   "'".$this->db->escapeString($this->startDate)."',";
          $stQuery .=   "'".$this->db->escapeString($this->monthProcess)."',";
          $stQuery .=   " ".$this->yearProcess.",";
          $stQuery .=   " ".$this->periodNo.",";
          $stQuery .=   " ".$this->passDay.",";
          $stQuery .=   "'".$this->db->escapeString($this->d01)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d02)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d03)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d04)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d05)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d06)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d07)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d08)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d09)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d10)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d11)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d12)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d13)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d14)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d15)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d16)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d17)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d18)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d19)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d20)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d21)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d22)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d23)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d24)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d25)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d26)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d27)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d28)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d29)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d30)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d31)."',";
          $stQuery .=   " ".$this->isActive.",";
          $stQuery .=   "'".$this->db->escapeString($this->picProcess)."',";
          $stQuery .=   "'".$this->db->escapeString($this->processTime)."',";
	  $stQuery .=   "'".$this->db->escapeString($this->bankId)."'";
          $stQuery .= "); "; 
          echo $stQuery;
	  exit();
          $this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START QUERY INSERT */
     public function getInsQuery()
     {
          if($this->tsId =="" || $this->tsId == NULL) 
          {
               $this->tsId = 0; 
          }
          if($this->biodataId =="" || $this->biodataId == NULL) 
          {
               $this->biodataId = ''; 
          }
          if($this->badgeNo =="" || $this->badgeNo == NULL) 
          {
               $this->badgeNo = ''; 
          }
          if($this->fullName =="" || $this->fullName == NULL) 
          {
               $this->fullName = ''; 
          }
          if($this->payrollBase =="" || $this->payrollBase == NULL) 
          {
               $this->payrollBase = ''; 
          }
          if($this->clientName =="" || $this->clientName == NULL) 
          {
               $this->clientName = ''; 
          }
          if($this->dept =="" || $this->dept == NULL) 
          {
               $this->dept = ''; 
          }
          if($this->monthProcess =="" || $this->monthProcess == NULL) 
          {
               $this->monthProcess = ''; 
          }
          if($this->yearProcess =="" || $this->yearProcess == NULL) 
          {
               $this->yearProcess = 0; 
          }
          if($this->periodNo =="" || $this->periodNo == NULL) 
          {
               $this->periodNo = 0; 
          }
          if($this->passDay =="" || $this->passDay == NULL) 
          {
               $this->passDay = 0; 
          }
          if($this->d01 =="" || $this->d01 == NULL) 
          {
               $this->d01 = ''; 
          }
          if($this->d02 =="" || $this->d02 == NULL) 
          {
               $this->d02 = ''; 
          }
          if($this->d03 =="" || $this->d03 == NULL) 
          {
               $this->d03 = ''; 
          }
          if($this->d04 =="" || $this->d04 == NULL) 
          {
               $this->d04 = ''; 
          }
          if($this->d05 =="" || $this->d05 == NULL) 
          {
               $this->d05 = ''; 
          }
          if($this->d06 =="" || $this->d06 == NULL) 
          {
               $this->d06 = ''; 
          }
          if($this->d07 =="" || $this->d07 == NULL) 
          {
               $this->d07 = ''; 
          }
          if($this->d08 =="" || $this->d08 == NULL) 
          {
               $this->d08 = ''; 
          }
          if($this->d09 =="" || $this->d09 == NULL) 
          {
               $this->d09 = ''; 
          }
          if($this->d10 =="" || $this->d10 == NULL) 
          {
               $this->d10 = ''; 
          }
          if($this->d11 =="" || $this->d11 == NULL) 
          {
               $this->d11 = ''; 
          }
          if($this->d12 =="" || $this->d12 == NULL) 
          {
               $this->d12 = ''; 
          }
          if($this->d13 =="" || $this->d13 == NULL) 
          {
               $this->d13 = ''; 
          }
          if($this->d14 =="" || $this->d14 == NULL) 
          {
               $this->d14 = ''; 
          }
          if($this->d15 =="" || $this->d15 == NULL) 
          {
               $this->d15 = ''; 
          }
          if($this->d16 =="" || $this->d16 == NULL) 
          {
               $this->d16 = ''; 
          }
          if($this->d17 =="" || $this->d17 == NULL) 
          {
               $this->d17 = ''; 
          }
          if($this->d18 =="" || $this->d18 == NULL) 
          {
               $this->d18 = ''; 
          }
          if($this->d19 =="" || $this->d19 == NULL) 
          {
               $this->d19 = ''; 
          }
          if($this->d20 =="" || $this->d20 == NULL) 
          {
               $this->d20 = ''; 
          }
          if($this->d21 =="" || $this->d21 == NULL) 
          {
               $this->d21 = ''; 
          }
          if($this->d22 =="" || $this->d22 == NULL) 
          {
               $this->d22 = ''; 
          }
          if($this->d23 =="" || $this->d23 == NULL) 
          {
               $this->d23 = ''; 
          }
          if($this->d24 =="" || $this->d24 == NULL) 
          {
               $this->d24 = ''; 
          }
          if($this->d25 =="" || $this->d25 == NULL) 
          {
               $this->d25 = ''; 
          }
          if($this->d26 =="" || $this->d26 == NULL) 
          {
               $this->d26 = ''; 
          }
          if($this->d27 =="" || $this->d27 == NULL) 
          {
               $this->d27 = ''; 
          }
          if($this->d28 =="" || $this->d28 == NULL) 
          {
               $this->d28 = ''; 
          }
          if($this->d29 =="" || $this->d29 == NULL) 
          {
               $this->d29 = ''; 
          }
          if($this->d30 =="" || $this->d30 == NULL) 
          {
               $this->d30 = ''; 
          }
          if($this->d31 =="" || $this->d31 == NULL) 
          {
               $this->d31 = ''; 
          }
          if($this->isActive =="" || $this->isActive == NULL) 
          {
               $this->isActive = 0; 
          }
          if($this->picProcess =="" || $this->picProcess == NULL) 
          {
               $this->picProcess = ''; 
          }
          if($this->processTime =="" || $this->processTime == NULL) 
          {
               $this->processTime = '1700-01-01 00:00:00'; 
          }

          $stQuery  = "INSERT INTO ".$this->table." ";
          $stQuery .= "( ";
          $stQuery .=   "ts_id,"; 
          $stQuery .=   "biodata_id,"; 
          $stQuery .=   "badge_no,"; 
          $stQuery .=   "full_name,"; 
          $stQuery .=   "payroll_base,"; 
          $stQuery .=   "client_name,"; 
          $stQuery .=   "dept,"; 
          $stQuery .=   "month_process,"; 
          $stQuery .=   "year_process,"; 
          $stQuery .=   "period_no,"; 
          $stQuery .=   "pass_day,"; 
          $stQuery .=   "d01,"; 
          $stQuery .=   "d02,"; 
          $stQuery .=   "d03,"; 
          $stQuery .=   "d04,"; 
          $stQuery .=   "d05,"; 
          $stQuery .=   "d06,"; 
          $stQuery .=   "d07,"; 
          $stQuery .=   "d08,"; 
          $stQuery .=   "d09,"; 
          $stQuery .=   "d10,"; 
          $stQuery .=   "d11,"; 
          $stQuery .=   "d12,"; 
          $stQuery .=   "d13,"; 
          $stQuery .=   "d14,"; 
          $stQuery .=   "d15,"; 
          $stQuery .=   "d16,"; 
          $stQuery .=   "d17,"; 
          $stQuery .=   "d18,"; 
          $stQuery .=   "d19,"; 
          $stQuery .=   "d20,"; 
          $stQuery .=   "d21,"; 
          $stQuery .=   "d22,"; 
          $stQuery .=   "d23,"; 
          $stQuery .=   "d24,"; 
          $stQuery .=   "d25,"; 
          $stQuery .=   "d26,"; 
          $stQuery .=   "d27,"; 
          $stQuery .=   "d28,"; 
          $stQuery .=   "d29,"; 
          $stQuery .=   "d30,"; 
          $stQuery .=   "d31,"; 
          $stQuery .=   "is_active,"; 
          $stQuery .=   "pic_process,"; 
          $stQuery .=   "process_time"; 
          $stQuery .= ") "; 
          $stQuery .= "VALUES "; 
          $stQuery .= "( "; 
          $stQuery .=   " ".$this->tsId.",";
          $stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
          $stQuery .=   "'".$this->db->escapeString($this->badgeNo)."',";
          $stQuery .=   "'".$this->db->escapeString($this->fullName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->payrollBase)."',";
          $stQuery .=   "'".$this->db->escapeString($this->clientName)."',";
          $stQuery .=   "'".$this->db->escapeString($this->dept)."',";
          $stQuery .=   "'".$this->db->escapeString($this->monthProcess)."',";
          $stQuery .=   " ".$this->yearProcess.",";
          $stQuery .=   " ".$this->periodNo.",";
          $stQuery .=   " ".$this->passDay.",";
          $stQuery .=   "'".$this->db->escapeString($this->d01)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d02)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d03)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d04)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d05)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d06)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d07)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d08)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d09)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d10)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d11)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d12)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d13)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d14)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d15)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d16)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d17)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d18)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d19)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d20)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d21)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d22)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d23)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d24)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d25)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d26)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d27)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d28)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d29)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d30)."',";
          $stQuery .=   "'".$this->db->escapeString($this->d31)."',";
          $stQuery .=   " ".$this->isActive.",";
          $stQuery .=   "'".$this->db->escapeString($this->picProcess)."',";
          $stQuery .=   "'".$this->db->escapeString($this->processTime)."'";
          $stQuery .= "); "; 
          return $stQuery; 
     }
     /* END QUERY INSERT */
     /* START UPDATE */
     public function upd($id)
     {
          if($this->tsId =="" || $this->tsId == NULL) 
          { 
               $this->tsId = 0; 
          } 
          if($this->biodataId =="" || $this->biodataId == NULL) 
          { 
               $this->biodataId = ''; 
          } 
          if($this->badgeNo =="" || $this->badgeNo == NULL) 
          { 
               $this->badgeNo = ''; 
          } 
          if($this->fullName =="" || $this->fullName == NULL) 
          { 
               $this->fullName = ''; 
          } 
          if($this->payrollBase =="" || $this->payrollBase == NULL) 
          { 
               $this->payrollBase = ''; 
          } 
          if($this->clientName =="" || $this->clientName == NULL) 
          { 
               $this->clientName = ''; 
          } 
          if($this->dept =="" || $this->dept == NULL) 
          { 
               $this->dept = ''; 
          } 
          if($this->monthProcess =="" || $this->monthProcess == NULL) 
          { 
               $this->monthProcess = ''; 
          } 
          if($this->yearProcess =="" || $this->yearProcess == NULL) 
          { 
               $this->yearProcess = 0; 
          } 
          if($this->periodNo =="" || $this->periodNo == NULL) 
          { 
               $this->periodNo = 0; 
          } 
          if($this->passDay =="" || $this->passDay == NULL) 
          { 
               $this->passDay = 0; 
          } 
          if($this->d01 =="" || $this->d01 == NULL) 
          { 
               $this->d01 = ''; 
          } 
          if($this->d02 =="" || $this->d02 == NULL) 
          { 
               $this->d02 = ''; 
          } 
          if($this->d03 =="" || $this->d03 == NULL) 
          { 
               $this->d03 = ''; 
          } 
          if($this->d04 =="" || $this->d04 == NULL) 
          { 
               $this->d04 = ''; 
          } 
          if($this->d05 =="" || $this->d05 == NULL) 
          { 
               $this->d05 = ''; 
          } 
          if($this->d06 =="" || $this->d06 == NULL) 
          { 
               $this->d06 = ''; 
          } 
          if($this->d07 =="" || $this->d07 == NULL) 
          { 
               $this->d07 = ''; 
          } 
          if($this->d08 =="" || $this->d08 == NULL) 
          { 
               $this->d08 = ''; 
          } 
          if($this->d09 =="" || $this->d09 == NULL) 
          { 
               $this->d09 = ''; 
          } 
          if($this->d10 =="" || $this->d10 == NULL) 
          { 
               $this->d10 = ''; 
          } 
          if($this->d11 =="" || $this->d11 == NULL) 
          { 
               $this->d11 = ''; 
          } 
          if($this->d12 =="" || $this->d12 == NULL) 
          { 
               $this->d12 = ''; 
          } 
          if($this->d13 =="" || $this->d13 == NULL) 
          { 
               $this->d13 = ''; 
          } 
          if($this->d14 =="" || $this->d14 == NULL) 
          { 
               $this->d14 = ''; 
          } 
          if($this->d15 =="" || $this->d15 == NULL) 
          { 
               $this->d15 = ''; 
          } 
          if($this->d16 =="" || $this->d16 == NULL) 
          { 
               $this->d16 = ''; 
          } 
          if($this->d17 =="" || $this->d17 == NULL) 
          { 
               $this->d17 = ''; 
          } 
          if($this->d18 =="" || $this->d18 == NULL) 
          { 
               $this->d18 = ''; 
          } 
          if($this->d19 =="" || $this->d19 == NULL) 
          { 
               $this->d19 = ''; 
          } 
          if($this->d20 =="" || $this->d20 == NULL) 
          { 
               $this->d20 = ''; 
          } 
          if($this->d21 =="" || $this->d21 == NULL) 
          { 
               $this->d21 = ''; 
          } 
          if($this->d22 =="" || $this->d22 == NULL) 
          { 
               $this->d22 = ''; 
          } 
          if($this->d23 =="" || $this->d23 == NULL) 
          { 
               $this->d23 = ''; 
          } 
          if($this->d24 =="" || $this->d24 == NULL) 
          { 
               $this->d24 = ''; 
          } 
          if($this->d25 =="" || $this->d25 == NULL) 
          { 
               $this->d25 = ''; 
          } 
          if($this->d26 =="" || $this->d26 == NULL) 
          { 
               $this->d26 = ''; 
          } 
          if($this->d27 =="" || $this->d27 == NULL) 
          { 
               $this->d27 = ''; 
          } 
          if($this->d28 =="" || $this->d28 == NULL) 
          { 
               $this->d28 = ''; 
          } 
          if($this->d29 =="" || $this->d29 == NULL) 
          { 
               $this->d29 = ''; 
          } 
          if($this->d30 =="" || $this->d30 == NULL) 
          { 
               $this->d30 = ''; 
          } 
          if($this->d31 =="" || $this->d31 == NULL) 
          { 
               $this->d31 = ''; 
          } 
          if($this->isActive =="" || $this->isActive == NULL) 
          { 
               $this->isActive = 0; 
          } 
          if($this->picProcess =="" || $this->picProcess == NULL) 
          { 
               $this->picProcess = ''; 
          } 
          if($this->processTime =="" || $this->processTime == NULL) 
          { 
               $this->processTime = '1700-01-01 00:00:00'; 
          } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   'ts_id ='.$this->tsId.','; 
          $stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
          $stQuery .=   "badge_no ='".$this->db->escapeString($this->badgeNo)."', "; 
          $stQuery .=   "full_name ='".$this->db->escapeString($this->fullName)."', "; 
          $stQuery .=   "payroll_base ='".$this->db->escapeString($this->payrollBase)."', "; 
          $stQuery .=   "client_name ='".$this->db->escapeString($this->clientName)."', "; 
          $stQuery .=   "dept ='".$this->db->escapeString($this->dept)."', "; 
          $stQuery .=   "month_process ='".$this->db->escapeString($this->monthProcess)."', "; 
          $stQuery .=   'year_process ='.$this->yearProcess.','; 
          $stQuery .=   'period_no ='.$this->periodNo.','; 
          $stQuery .=   'pass_day ='.$this->passDay.','; 
          $stQuery .=   "d01 ='".$this->db->escapeString($this->d01)."', "; 
          $stQuery .=   "d02 ='".$this->db->escapeString($this->d02)."', "; 
          $stQuery .=   "d03 ='".$this->db->escapeString($this->d03)."', "; 
          $stQuery .=   "d04 ='".$this->db->escapeString($this->d04)."', "; 
          $stQuery .=   "d05 ='".$this->db->escapeString($this->d05)."', "; 
          $stQuery .=   "d06 ='".$this->db->escapeString($this->d06)."', "; 
          $stQuery .=   "d07 ='".$this->db->escapeString($this->d07)."', "; 
          $stQuery .=   "d08 ='".$this->db->escapeString($this->d08)."', "; 
          $stQuery .=   "d09 ='".$this->db->escapeString($this->d09)."', "; 
          $stQuery .=   "d10 ='".$this->db->escapeString($this->d10)."', "; 
          $stQuery .=   "d11 ='".$this->db->escapeString($this->d11)."', "; 
          $stQuery .=   "d12 ='".$this->db->escapeString($this->d12)."', "; 
          $stQuery .=   "d13 ='".$this->db->escapeString($this->d13)."', "; 
          $stQuery .=   "d14 ='".$this->db->escapeString($this->d14)."', "; 
          $stQuery .=   "d15 ='".$this->db->escapeString($this->d15)."', "; 
          $stQuery .=   "d16 ='".$this->db->escapeString($this->d16)."', "; 
          $stQuery .=   "d17 ='".$this->db->escapeString($this->d17)."', "; 
          $stQuery .=   "d18 ='".$this->db->escapeString($this->d18)."', "; 
          $stQuery .=   "d19 ='".$this->db->escapeString($this->d19)."', "; 
          $stQuery .=   "d20 ='".$this->db->escapeString($this->d20)."', "; 
          $stQuery .=   "d21 ='".$this->db->escapeString($this->d21)."', "; 
          $stQuery .=   "d22 ='".$this->db->escapeString($this->d22)."', "; 
          $stQuery .=   "d23 ='".$this->db->escapeString($this->d23)."', "; 
          $stQuery .=   "d24 ='".$this->db->escapeString($this->d24)."', "; 
          $stQuery .=   "d25 ='".$this->db->escapeString($this->d25)."', "; 
          $stQuery .=   "d26 ='".$this->db->escapeString($this->d26)."', "; 
          $stQuery .=   "d27 ='".$this->db->escapeString($this->d27)."', "; 
          $stQuery .=   "d28 ='".$this->db->escapeString($this->d28)."', "; 
          $stQuery .=   "d29 ='".$this->db->escapeString($this->d29)."', "; 
          $stQuery .=   "d30 ='".$this->db->escapeString($this->d30)."', "; 
          $stQuery .=   "d31 ='".$this->db->escapeString($this->d31)."', "; 
          $stQuery .=   'is_active ='.$this->isActive.','; 
          $stQuery .=   "pic_process ='".$this->db->escapeString($this->picProcess)."', "; 
          $stQuery .=   "process_time ='".$this->db->escapeString($this->processTime)."' "; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   'ts_id = '.$this->db->escapeString($id).''; 
          $this->db->query($stQuery); 
     }
     public function deleteByIdPeriod($monthProcess, $yearProcess, $startDate)
      {
         $st  = "DELETE FROM ".$this->table." ";
         $st .='WHERE month_process ='.'"'.$monthProcess.'"';
         $st .='AND year_process ='.'"'.$yearProcess.'"';
         $st .='AND start_date ='.'"'.$startDate.'"';
         $this->db->query($st);
      }
     /* END UPDATE */
     /* START QUERY UPDATE */
     public function getUpdQuery($id)
     {
          if($this->tsId =="" || $this->tsId == NULL) 
          { 
               $this->tsId = 0; 
          } 
          if($this->biodataId =="" || $this->biodataId == NULL) 
          { 
               $this->biodataId = ''; 
          } 
          if($this->badgeNo =="" || $this->badgeNo == NULL) 
          { 
               $this->badgeNo = ''; 
          } 
          if($this->fullName =="" || $this->fullName == NULL) 
          { 
               $this->fullName = ''; 
          } 
          if($this->payrollBase =="" || $this->payrollBase == NULL) 
          { 
               $this->payrollBase = ''; 
          } 
          if($this->clientName =="" || $this->clientName == NULL) 
          { 
               $this->clientName = ''; 
          } 
          if($this->dept =="" || $this->dept == NULL) 
          { 
               $this->dept = ''; 
          } 
          if($this->monthProcess =="" || $this->monthProcess == NULL) 
          { 
               $this->monthProcess = ''; 
          } 
          if($this->yearProcess =="" || $this->yearProcess == NULL) 
          { 
               $this->yearProcess = 0; 
          } 
          if($this->periodNo =="" || $this->periodNo == NULL) 
          { 
               $this->periodNo = 0; 
          } 
          if($this->passDay =="" || $this->passDay == NULL) 
          { 
               $this->passDay = 0; 
          } 
          if($this->d01 =="" || $this->d01 == NULL) 
          { 
               $this->d01 = ''; 
          } 
          if($this->d02 =="" || $this->d02 == NULL) 
          { 
               $this->d02 = ''; 
          } 
          if($this->d03 =="" || $this->d03 == NULL) 
          { 
               $this->d03 = ''; 
          } 
          if($this->d04 =="" || $this->d04 == NULL) 
          { 
               $this->d04 = ''; 
          } 
          if($this->d05 =="" || $this->d05 == NULL) 
          { 
               $this->d05 = ''; 
          } 
          if($this->d06 =="" || $this->d06 == NULL) 
          { 
               $this->d06 = ''; 
          } 
          if($this->d07 =="" || $this->d07 == NULL) 
          { 
               $this->d07 = ''; 
          } 
          if($this->d08 =="" || $this->d08 == NULL) 
          { 
               $this->d08 = ''; 
          } 
          if($this->d09 =="" || $this->d09 == NULL) 
          { 
               $this->d09 = ''; 
          } 
          if($this->d10 =="" || $this->d10 == NULL) 
          { 
               $this->d10 = ''; 
          } 
          if($this->d11 =="" || $this->d11 == NULL) 
          { 
               $this->d11 = ''; 
          } 
          if($this->d12 =="" || $this->d12 == NULL) 
          { 
               $this->d12 = ''; 
          } 
          if($this->d13 =="" || $this->d13 == NULL) 
          { 
               $this->d13 = ''; 
          } 
          if($this->d14 =="" || $this->d14 == NULL) 
          { 
               $this->d14 = ''; 
          } 
          if($this->d15 =="" || $this->d15 == NULL) 
          { 
               $this->d15 = ''; 
          } 
          if($this->d16 =="" || $this->d16 == NULL) 
          { 
               $this->d16 = ''; 
          } 
          if($this->d17 =="" || $this->d17 == NULL) 
          { 
               $this->d17 = ''; 
          } 
          if($this->d18 =="" || $this->d18 == NULL) 
          { 
               $this->d18 = ''; 
          } 
          if($this->d19 =="" || $this->d19 == NULL) 
          { 
               $this->d19 = ''; 
          } 
          if($this->d20 =="" || $this->d20 == NULL) 
          { 
               $this->d20 = ''; 
          } 
          if($this->d21 =="" || $this->d21 == NULL) 
          { 
               $this->d21 = ''; 
          } 
          if($this->d22 =="" || $this->d22 == NULL) 
          { 
               $this->d22 = ''; 
          } 
          if($this->d23 =="" || $this->d23 == NULL) 
          { 
               $this->d23 = ''; 
          } 
          if($this->d24 =="" || $this->d24 == NULL) 
          { 
               $this->d24 = ''; 
          } 
          if($this->d25 =="" || $this->d25 == NULL) 
          { 
               $this->d25 = ''; 
          } 
          if($this->d26 =="" || $this->d26 == NULL) 
          { 
               $this->d26 = ''; 
          } 
          if($this->d27 =="" || $this->d27 == NULL) 
          { 
               $this->d27 = ''; 
          } 
          if($this->d28 =="" || $this->d28 == NULL) 
          { 
               $this->d28 = ''; 
          } 
          if($this->d29 =="" || $this->d29 == NULL) 
          { 
               $this->d29 = ''; 
          } 
          if($this->d30 =="" || $this->d30 == NULL) 
          { 
               $this->d30 = ''; 
          } 
          if($this->d31 =="" || $this->d31 == NULL) 
          { 
               $this->d31 = ''; 
          } 
          if($this->isActive =="" || $this->isActive == NULL) 
          { 
               $this->isActive = 0; 
          } 
          if($this->picProcess =="" || $this->picProcess == NULL) 
          { 
               $this->picProcess = ''; 
          } 
          if($this->processTime =="" || $this->processTime == NULL) 
          { 
               $this->processTime = '1700-01-01 00:00:00'; 
          } 

          $stQuery  = "UPDATE ".$this->table." "; 
          $stQuery .= "SET "; 
          $stQuery .=   'ts_id ='.$this->tsId.','; 
          $stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
          $stQuery .=   "badge_no ='".$this->db->escapeString($this->badgeNo)."', "; 
          $stQuery .=   "full_name ='".$this->db->escapeString($this->fullName)."', "; 
          $stQuery .=   "payroll_base ='".$this->db->escapeString($this->payrollBase)."', "; 
          $stQuery .=   "client_name ='".$this->db->escapeString($this->clientName)."', "; 
          $stQuery .=   "dept ='".$this->db->escapeString($this->dept)."', "; 
          $stQuery .=   "month_process ='".$this->db->escapeString($this->monthProcess)."', "; 
          $stQuery .=   'year_process ='.$this->yearProcess.','; 
          $stQuery .=   'period_no ='.$this->periodNo.','; 
          $stQuery .=   'pass_day ='.$this->passDay.','; 
          $stQuery .=   "d01 ='".$this->db->escapeString($this->d01)."', "; 
          $stQuery .=   "d02 ='".$this->db->escapeString($this->d02)."', "; 
          $stQuery .=   "d03 ='".$this->db->escapeString($this->d03)."', "; 
          $stQuery .=   "d04 ='".$this->db->escapeString($this->d04)."', "; 
          $stQuery .=   "d05 ='".$this->db->escapeString($this->d05)."', "; 
          $stQuery .=   "d06 ='".$this->db->escapeString($this->d06)."', "; 
          $stQuery .=   "d07 ='".$this->db->escapeString($this->d07)."', "; 
          $stQuery .=   "d08 ='".$this->db->escapeString($this->d08)."', "; 
          $stQuery .=   "d09 ='".$this->db->escapeString($this->d09)."', "; 
          $stQuery .=   "d10 ='".$this->db->escapeString($this->d10)."', "; 
          $stQuery .=   "d11 ='".$this->db->escapeString($this->d11)."', "; 
          $stQuery .=   "d12 ='".$this->db->escapeString($this->d12)."', "; 
          $stQuery .=   "d13 ='".$this->db->escapeString($this->d13)."', "; 
          $stQuery .=   "d14 ='".$this->db->escapeString($this->d14)."', "; 
          $stQuery .=   "d15 ='".$this->db->escapeString($this->d15)."', "; 
          $stQuery .=   "d16 ='".$this->db->escapeString($this->d16)."', "; 
          $stQuery .=   "d17 ='".$this->db->escapeString($this->d17)."', "; 
          $stQuery .=   "d18 ='".$this->db->escapeString($this->d18)."', "; 
          $stQuery .=   "d19 ='".$this->db->escapeString($this->d19)."', "; 
          $stQuery .=   "d20 ='".$this->db->escapeString($this->d20)."', "; 
          $stQuery .=   "d21 ='".$this->db->escapeString($this->d21)."', "; 
          $stQuery .=   "d22 ='".$this->db->escapeString($this->d22)."', "; 
          $stQuery .=   "d23 ='".$this->db->escapeString($this->d23)."', "; 
          $stQuery .=   "d24 ='".$this->db->escapeString($this->d24)."', "; 
          $stQuery .=   "d25 ='".$this->db->escapeString($this->d25)."', "; 
          $stQuery .=   "d26 ='".$this->db->escapeString($this->d26)."', "; 
          $stQuery .=   "d27 ='".$this->db->escapeString($this->d27)."', "; 
          $stQuery .=   "d28 ='".$this->db->escapeString($this->d28)."', "; 
          $stQuery .=   "d29 ='".$this->db->escapeString($this->d29)."', "; 
          $stQuery .=   "d30 ='".$this->db->escapeString($this->d30)."', "; 
          $stQuery .=   "d31 ='".$this->db->escapeString($this->d31)."', "; 
          $stQuery .=   'is_active ='.$this->isActive.','; 
          $stQuery .=   "pic_process ='".$this->db->escapeString($this->picProcess)."', "; 
          $stQuery .=   "process_time ='".$this->db->escapeString($this->processTime)."' "; 
          $stQuery .= 'WHERE '; 
          $stQuery .=   'ts_id = '.$this->db->escapeString($id).''; 
          return $stQuery; 
     }
     /* END QUERY UPDATE */
     /* START DELETE */
     public function del($id)
     {
          $stQuery  = "DELETE FROM ".$this->table." ";      
          $stQuery .= "WHERE ts_id = ".$this->db->escapeString($id)."";
          $db->query($stQuery); 
     }
	
     function getSM()
     {
          $stQuery = "SELECT * FROM tr_slip WHERE year_period = '".$this->db->escapeString($this->yearProcess)."' GROUP BY payroll_group;";
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }
     
     function getBiodataIdBySM($payrollGroup)
     {
          $stQuery = "SELECT a.*,b.*,c.*,d.* FROM tr_slip a, mt_biodata_01 b, mt_salary c, mt_bank d WHERE a.biodata_id = b.biodata_id AND a.biodata_id = c.biodata_id AND a.bank_id = d.bank_id AND a.year_period = '".$this->db->escapeString($this->yearProcess)."' AND a.payroll_group = '".$payrollGroup."' GROUP BY a.biodata_id;";
           //echo $stQuery;
           //exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     function getDataByBiodataId($bioId,$SM)
     {
          $stQuery = "SELECT * FROM tr_slip WHERE year_period = '2022' AND payroll_group = '".$SM."' AND biodata_id = '".$bioId."';";
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     function Proses()
     {
          $stQuery = "SELECT a.*,b.monthly,daily ,c.emp_position ,c.marital_status FROM tr_timesheet a , mt_salary b, mt_biodata_01 c WHERE a.biodata_id=b.biodata_id AND a.biodata_id=c.biodata_id AND a.month_process = '".$this->db->escapeString($this->monthProcess)."' AND a.year_process = '".$this->db->escapeString($this->yearProcess)."' AND a.start_date = '".$this->db->escapeString($this->startDate)."'";
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }
     function Proses2()
     {
          $stQuery = "SELECT a.*,b.monthly,daily ,c.emp_position ,c.marital_status, FROM tr_timesheet a , mt_salary b, mt_biodata_01 c WHERE a.biodata_id=b.biodata_id AND a.biodata_id=c.biodata_id AND a.month_process = '".$this->db->escapeString($this->monthProcess)."' AND a.year_process = '".$this->db->escapeString($this->yearProcess)."'";
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     function Summary()
     {
          $stQuery = "SELECT * FROM tr_slip a LEFT JOIN mt_salary c ON a.biodata_id=c.biodata_id LEFT JOIN mt_bank d ON c.bank_id=d.bank_id WHERE a.month_period = '".$this->db->escapeString($this->monthProcess)."' AND a.year_period = '".$this->db->escapeString($this->yearProcess)."' AND a.payroll_group = '".$this->db->escapeString($this->payrollGroup)."' AND a.dept = '".$this->db->escapeString($this->dept)."'";
          $query = $this->db->query($stQuery)->getResultArray();
         /* return $query;*/
          // echo $stQuery;
          // exit();
          return $query;
     }
     function Print1()
     {
          $stQuery = "SELECT a.*,b.*,c.*,d.*,e.* FROM tr_timesheet a , tr_slip b, tr_overtime c, mt_salary d, mt_biodata_01 e WHERE a.ts_id=b.ts_id AND a.biodata_id=d.biodata_id AND a.ts_id=c.roster_id AND a.biodata_id = e.biodata_id AND a.month_process = '".$this->db->escapeString($this->monthProcess)."' AND a.year_process = '".$this->db->escapeString($this->yearProcess)."' ";
          $query = $this->db->query($stQuery)->getResultArray();
         /* return $query;*/
          echo $stQuery;
exit();
          return $query;
          /*return $query;*/
     }
     function getAllData()
     {
          $stQuery = "SELECT slip_id,full_name,dept,position FROM tr_slip WHERE month_period = '".$this->db->escapeString($this->monthProcess)."' AND year_period = '".$this->db->escapeString($this->yearProcess)."'AND payroll_group = '".$this->db->escapeString($this->payrollGroup)."'";
          $query = $this->db->query($stQuery)->getResultArray();
	  //echo $stQuery;
	  //exit();

          return $query;
     }
     function getAlldeptData()
     {
          $stQuery = "SELECT slip_id,full_name,dept,position FROM tr_slip WHERE month_period = '".$this->db->escapeString($this->monthProcess)."' AND year_period = '".$this->db->escapeString($this->yearProcess)."'AND payroll_group = '".$this->db->escapeString($this->payrollGroup)."' AND dept = '".$this->db->escapeString($this->dept)."'";
          $query = $this->db->query($stQuery)->getResultArray();
	  //echo $stQuery;
	  //exit();
          return $query;
     }

     function formlist()
     {
          $stQuery = "SELECT COUNT(*) AS total_karyawan,SUM(totalgaji) AS total FROM tr_slip WHERE month_period = '".$this->db->escapeString($this->monthProcess)."' AND year_period = '".$this->db->escapeString($this->yearProcess)."'AND payroll_group = '".$this->db->escapeString($this->payrollGroup)."' ";
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }
     function invoice()
     {
          $stQuery = "SELECT dept,COUNT(*) AS totalempl,SUM(wdtotal) AS totalwork,SUM(gajipokok) AS gajipokok, SUM(totalot) AS overtime, SUM(tunjangan) AS tunjangan FROM tr_slip WHERE month_period = '".$this->db->escapeString($this->monthProcess)."' AND year_period = '".$this->db->escapeString($this->yearProcess)."' AND payroll_group = '".$this->db->escapeString($this->payrollGroup)."' GROUP BY dept ";
          // echo $stQuery;
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }
     function Print($ts_id)
     {
          $stQuery = "SELECT a.*,b.*,c.*,d.*,e.tax_no FROM tr_timesheet a , tr_slip b, tr_overtime c, mt_salary d, mt_biodata_01 e WHERE a.ts_id=b.ts_id AND a.biodata_id=d.biodata_id AND a.ts_id=c.roster_id AND a.biodata_id = e.biodata_id AND a.ts_id = '".$this->db->escapeString($ts_id)."'";
          $query = $this->db->query($stQuery)->getRowArray();
          return $query;
          // $this->db->query($query); 
          // return $query;
     }
     function baca()
     {
          $stQuery = "SELECT b.*,a.start_date FROM tr_slip b, tr_timesheet a WHERE a.ts_id=b.ts_id AND a.month_process = '".$this->db->escapeString($this->monthProcess)."' AND a.year_process = '".$this->db->escapeString($this->yearProcess)."' AND a.start_date = '".$this->db->escapeString($this->startDate)."'";
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     function getSlipById()
     {
          $stQuery = "SELECT * FROM tr_slip WHERE slip_id = ".$this->db->escapeString($slipId)."";
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
          $stQuery  = "SELECT * FROM ".$this->table." "; 
          $query  = $this->db->query($stQuery); 
          $arrayList = $query->getResultArray(); 
          return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." ";     
          $stQuery .= "WHERE ts_id = ".$this->db->escapeString($id)."";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." "; 
          $stQuery .= "WHERE ts_id = ".$this->db->escapeString($id)."";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          $this->tsId = $arrayRow['ts_id']; 
          $this->biodataId = $arrayRow['biodata_id']; 
          $this->badgeNo = $arrayRow['badge_no']; 
          $this->fullName = $arrayRow['full_name']; 
          $this->payrollBase = $arrayRow['payroll_base']; 
          $this->clientName = $arrayRow['client_name']; 
          $this->dept = $arrayRow['dept']; 
          $this->monthProcess = $arrayRow['month_process']; 
          $this->yearProcess = $arrayRow['year_process']; 
          $this->periodNo = $arrayRow['period_no']; 
          $this->passDay = $arrayRow['pass_day']; 
          $this->d01 = $arrayRow['d01']; 
          $this->d02 = $arrayRow['d02']; 
          $this->d03 = $arrayRow['d03']; 
          $this->d04 = $arrayRow['d04']; 
          $this->d05 = $arrayRow['d05']; 
          $this->d06 = $arrayRow['d06']; 
          $this->d07 = $arrayRow['d07']; 
          $this->d08 = $arrayRow['d08']; 
          $this->d09 = $arrayRow['d09']; 
          $this->d10 = $arrayRow['d10']; 
          $this->d11 = $arrayRow['d11']; 
          $this->d12 = $arrayRow['d12']; 
          $this->d13 = $arrayRow['d13']; 
          $this->d14 = $arrayRow['d14']; 
          $this->d15 = $arrayRow['d15']; 
          $this->d16 = $arrayRow['d16']; 
          $this->d17 = $arrayRow['d17']; 
          $this->d18 = $arrayRow['d18']; 
          $this->d19 = $arrayRow['d19']; 
          $this->d20 = $arrayRow['d20']; 
          $this->d21 = $arrayRow['d21']; 
          $this->d22 = $arrayRow['d22']; 
          $this->d23 = $arrayRow['d23']; 
          $this->d24 = $arrayRow['d24']; 
          $this->d25 = $arrayRow['d25']; 
          $this->d26 = $arrayRow['d26']; 
          $this->d27 = $arrayRow['d27']; 
          $this->d28 = $arrayRow['d28']; 
          $this->d29 = $arrayRow['d29']; 
          $this->d30 = $arrayRow['d30']; 
          $this->d31 = $arrayRow['d31']; 
          $this->isActive = $arrayRow['is_active']; 
          $this->picProcess = $arrayRow['pic_process']; 
          $this->processTime = $arrayRow['process_time']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
          $this->tsId = 0; 
          $this->biodataId = ''; 
          $this->badgeNo = ''; 
          $this->fullName = ''; 
          $this->payrollBase = ''; 
          $this->clientName = ''; 
          $this->dept = ''; 
          $this->monthProcess = ''; 
          $this->yearProcess = 0; 
          $this->periodNo = 0; 
          $this->passDay = 0; 
          $this->d01 = ''; 
          $this->d02 = ''; 
          $this->d03 = ''; 
          $this->d04 = ''; 
          $this->d05 = ''; 
          $this->d06 = ''; 
          $this->d07 = ''; 
          $this->d08 = ''; 
          $this->d09 = ''; 
          $this->d10 = ''; 
          $this->d11 = ''; 
          $this->d12 = ''; 
          $this->d13 = ''; 
          $this->d14 = ''; 
          $this->d15 = ''; 
          $this->d16 = ''; 
          $this->d17 = ''; 
          $this->d18 = ''; 
          $this->d19 = ''; 
          $this->d20 = ''; 
          $this->d21 = ''; 
          $this->d22 = ''; 
          $this->d23 = ''; 
          $this->d24 = ''; 
          $this->d25 = ''; 
          $this->d26 = ''; 
          $this->d27 = ''; 
          $this->d28 = ''; 
          $this->d29 = ''; 
          $this->d30 = ''; 
          $this->d31 = ''; 
          $this->isActive = 0; 
          $this->picProcess = ''; 
          $this->processTime = '1700-01-01 00:00:00'; 
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
          $strSql = "SELECT ";
          $strSql .= " CASE WHEN id_year = curr_ym THEN ";
          $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
          $strSql .= " ELSE ";
          $strSql .= "   CONCAT(curr_ym, '00001') ";
          $strSql .= " END AS doc_id ";
          $strSql .= "FROM ";
          $strSql .= " (SELECT ";
          $strSql .= "   MAX(".$columnId.") fi,";
          $strSql .= "   LEFT(".$columnId.",4) id_year,";
          $strSql .= "   current_date dt,";
          $strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
          $strSql .= "   CONCAT(";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
          $strSql .= "   LPAD(";
          $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
          $strSql .= "    )";
          $strSql .= "   ) curr_ym,";
          $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
          $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
          $strSql .= " FROM ";
          $strSql .= "   ".$this->table." ";
          $strSql .= " GROUP BY ".$columnId.") a ";
          $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
          $query  = $this->db->query($strSql); 
          $arrayRow = $query->getRowArray(); 
          if(!isset($arrayRow))
          {
               $curYM = date('ym');
               $arrayRow['doc_id'] = $curYM.'00001';
          }
          return $arrayRow;
     }
     /* END OF ID GENERATOR */
}
