<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_biodata_03;

class Mt_biodata_03 extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../v_mt_biodata_03';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../ins_mt_biodata_03';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$mtBiodata03 = new M_mt_biodata_03();
          $data['mtBiodata03'] = $mtBiodata03->getById($experience_id);
          /* ***Using Valid Path */
          $data['actView'] = '../upd_mt_biodata_03';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$mtBiodata03 = new M_mt_biodata_03();
     	$mtBiodata03->resetValues();
     	$mtBiodata03->setExperienceId($_POST['experienceId']);
     	$mtBiodata03->setBiodataId($_POST['biodataId']);
     	$mtBiodata03->setCompanyName($_POST['companyName']);
     	$mtBiodata03->setWorkYear($_POST['workYear']);
     	$mtBiodata03->setWorkPeriod($_POST['workPeriod']);
     	$mtBiodata03->setJobPosition($_POST['jobPosition']);
     	$mtBiodata03->setJobDesc($_POST['jobDesc']);
     	$mtBiodata03->setMovingReason($_POST['movingReason']);
     	$mtBiodata03->setPicInput($_POST['picInput']);
     	$mtBiodata03->setInputTime($_POST['inputTime']);
     	$mtBiodata03->setPicEdit($_POST['picEdit']);
     	$mtBiodata03->setEditTime($_POST['editTime']);
     	$mtBiodata03->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['experienceId'];
     	$mtBiodata03 = new M_mt_biodata_03();
     	$mtBiodata03->setObjectById($id);
     	$mtBiodata03->setExperienceId($_POST['experienceId']);
     	$mtBiodata03->setBiodataId($_POST['biodataId']);
     	$mtBiodata03->setCompanyName($_POST['companyName']);
     	$mtBiodata03->setWorkYear($_POST['workYear']);
     	$mtBiodata03->setWorkPeriod($_POST['workPeriod']);
     	$mtBiodata03->setJobPosition($_POST['jobPosition']);
     	$mtBiodata03->setJobDesc($_POST['jobDesc']);
     	$mtBiodata03->setMovingReason($_POST['movingReason']);
     	$mtBiodata03->setPicInput($_POST['picInput']);
     	$mtBiodata03->setInputTime($_POST['inputTime']);
     	$mtBiodata03->setPicEdit($_POST['picEdit']);
     	$mtBiodata03->setEditTime($_POST['editTime']);
     	$mtBiodata03->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtBiodata03 = new M_mt_biodata_03();
     	$id = $_POST['experienceId'];
     	$mtBiodata03->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtBiodata03 = new M_mt_biodata_03();
     	$rs = $mtBiodata03->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
