<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_biodata_01;

class Mt_biodata_01 extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../v_mt_biodata_01';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../ins_mt_biodata_01';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$mtBiodata01 = new M_mt_biodata_01();
          $data['mtBiodata01'] = $mtBiodata01->getById($biodata_id);
          /* ***Using Valid Path */
          $data['actView'] = '../upd_mt_biodata_01';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$mtBiodata01 = new M_mt_biodata_01();
     	$mtBiodata01->resetValues();
     	$mtBiodata01->setBiodataId($_POST['biodataId']);
     	$mtBiodata01->setDeptId($_POST['deptId']);
     	$mtBiodata01->setFullName($_POST['fullName']);
     	$mtBiodata01->setFirstName($_POST['firstName']);
     	$mtBiodata01->setMiddleName($_POST['middleName']);
     	$mtBiodata01->setLastName($_POST['lastName']);
     	$mtBiodata01->setPlaceOfBirth($_POST['placeOfBirth']);
     	$mtBiodata01->setDateOfBirth($_POST['dateOfBirth']);
     	$mtBiodata01->setGender($_POST['gender']);
     	$mtBiodata01->setEthnic($_POST['ethnic']);
     	$mtBiodata01->setNationality($_POST['nationality']);
     	$mtBiodata01->setCompany($_POST['company']);
     	$mtBiodata01->setDept($_POST['dept']);
     	$mtBiodata01->setEmpPosition($_POST['empPosition']);
     	$mtBiodata01->setPassportNo($_POST['passportNo']);
     	$mtBiodata01->setPlacement($_POST['placement']);
     	$mtBiodata01->setApproveLevel($_POST['approveLevel']);
     	$mtBiodata01->setInternalId($_POST['internalId']);
     	$mtBiodata01->setPositionLevel($_POST['positionLevel']);
     	$mtBiodata01->setJoinDate($_POST['joinDate']);
     	$mtBiodata01->setIdCardNo($_POST['idCardNo']);
     	$mtBiodata01->setIdCardAddress($_POST['idCardAddress']);
     	$mtBiodata01->setCurrentAddress($_POST['currentAddress']);
     	$mtBiodata01->setResidenceStatus($_POST['residenceStatus']);
     	$mtBiodata01->setReligion($_POST['religion']);
     	$mtBiodata01->setDrivingLicense($_POST['drivingLicense']);
     	$mtBiodata01->setMaritalStatus($_POST['maritalStatus']);
     	$mtBiodata01->setEmpHeight($_POST['empHeight']);
     	$mtBiodata01->setEmpWeight($_POST['empWeight']);
     	$mtBiodata01->setBloodType($_POST['bloodType']);
     	$mtBiodata01->setEmailAddress($_POST['emailAddress']);
     	$mtBiodata01->setTelpNo($_POST['telpNo']);
     	$mtBiodata01->setCellNo($_POST['cellNo']);
     	$mtBiodata01->setIsGlasses($_POST['isGlasses']);
     	$mtBiodata01->setEmpStatus($_POST['empStatus']);
     	$mtBiodata01->setTaxNo($_POST['taxNo']);
     	$mtBiodata01->setBpjsNo($_POST['bpjsNo']);
     	$mtBiodata01->setBpjsTkNo($_POST['bpjsTkNo']);
     	$mtBiodata01->setIsActive($_POST['isActive']);
     	$mtBiodata01->setPicInput($_POST['picInput']);
     	$mtBiodata01->setInputTime($_POST['inputTime']);
     	$mtBiodata01->setPicEdit($_POST['picEdit']);
     	$mtBiodata01->setEditTime($_POST['editTime']);
     	$mtBiodata01->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['biodataId'];
     	$mtBiodata01 = new M_mt_biodata_01();
     	$mtBiodata01->setObjectById($id);
     	$mtBiodata01->setBiodataId($_POST['biodataId']);
     	$mtBiodata01->setDeptId($_POST['deptId']);
     	$mtBiodata01->setFullName($_POST['fullName']);
     	$mtBiodata01->setFirstName($_POST['firstName']);
     	$mtBiodata01->setMiddleName($_POST['middleName']);
     	$mtBiodata01->setLastName($_POST['lastName']);
     	$mtBiodata01->setPlaceOfBirth($_POST['placeOfBirth']);
     	$mtBiodata01->setDateOfBirth($_POST['dateOfBirth']);
     	$mtBiodata01->setGender($_POST['gender']);
     	$mtBiodata01->setEthnic($_POST['ethnic']);
     	$mtBiodata01->setNationality($_POST['nationality']);
     	$mtBiodata01->setCompany($_POST['company']);
     	$mtBiodata01->setDept($_POST['dept']);
     	$mtBiodata01->setEmpPosition($_POST['empPosition']);
     	$mtBiodata01->setPassportNo($_POST['passportNo']);
     	$mtBiodata01->setPlacement($_POST['placement']);
     	$mtBiodata01->setApproveLevel($_POST['approveLevel']);
     	$mtBiodata01->setInternalId($_POST['internalId']);
     	$mtBiodata01->setPositionLevel($_POST['positionLevel']);
     	$mtBiodata01->setJoinDate($_POST['joinDate']);
     	$mtBiodata01->setIdCardNo($_POST['idCardNo']);
     	$mtBiodata01->setIdCardAddress($_POST['idCardAddress']);
     	$mtBiodata01->setCurrentAddress($_POST['currentAddress']);
     	$mtBiodata01->setResidenceStatus($_POST['residenceStatus']);
     	$mtBiodata01->setReligion($_POST['religion']);
     	$mtBiodata01->setDrivingLicense($_POST['drivingLicense']);
     	$mtBiodata01->setMaritalStatus($_POST['maritalStatus']);
     	$mtBiodata01->setEmpHeight($_POST['empHeight']);
     	$mtBiodata01->setEmpWeight($_POST['empWeight']);
     	$mtBiodata01->setBloodType($_POST['bloodType']);
     	$mtBiodata01->setEmailAddress($_POST['emailAddress']);
     	$mtBiodata01->setTelpNo($_POST['telpNo']);
     	$mtBiodata01->setCellNo($_POST['cellNo']);
     	$mtBiodata01->setIsGlasses($_POST['isGlasses']);
     	$mtBiodata01->setEmpStatus($_POST['empStatus']);
     	$mtBiodata01->setTaxNo($_POST['taxNo']);
     	$mtBiodata01->setBpjsNo($_POST['bpjsNo']);
     	$mtBiodata01->setBpjsTkNo($_POST['bpjsTkNo']);
     	$mtBiodata01->setIsActive($_POST['isActive']);
     	$mtBiodata01->setPicInput($_POST['picInput']);
     	$mtBiodata01->setInputTime($_POST['inputTime']);
     	$mtBiodata01->setPicEdit($_POST['picEdit']);
     	$mtBiodata01->setEditTime($_POST['editTime']);
     	$mtBiodata01->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtBiodata01 = new M_mt_biodata_01();
     	$id = $_POST['biodataId'];
     	$mtBiodata01->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtBiodata01 = new M_mt_biodata_01();
     	$rs = $mtBiodata01->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
