<?php namespace App\Models\Transaction; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Oct 05, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_rp_db extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = 'hris';
     protected $table = 'rp_db';
     protected $primaryKey = 'db_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $dbId;
     protected $in;
     protected $out;
     protected $shiftDay;
     protected $poPh;
     protected $workDay;
     protected $dateProcess;
     protected $startDate;
     protected $totalOt;
     protected $endDate;
     protected $biodataId;
     protected $tsId;
     protected $slipId;
     protected $ot1;
     protected $ot2;
     protected $ot3;
     protected $ot4;
     protected $normalTime;
     protected $dept;
     protected $tunjangan;
     protected $total_ot_value;
     protected $tunjanganSiang;
     protected $tunjanganMalam;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
        parent::__construct();
        $this->db = \Config\Database::connect($this->DBGroup, false);
          $this->dbId = 0;
          $this->in = 0;
          $this->out = 0;
          $this->shiftDay = '';
          $this->poPh = '';
          $this->workDay = '';
          $this->dateProcess = 0;
          $this->startDate = 0;
          $this->endDate = 0;
          $this->biodataId = 0;
          $this->tsId = 0;
          $this->slipId = 0;
          $this->totalOt = 0;
          $this->ot1 = 0;
          $this->ot2 = 0;
          $this->ot3 = 0;
          $this->ot4 = 0;
          $this->normalTime = 0;
          $this->dept = '';
          $this->tunjangan = 0;
          $this->total_ot_value = 0;
          $this->tunjanganSiang = 0;
          $this->tunjanganMalam = 0;
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setDbId($aDbId)
     {
        $this->dbId = $aDbId;
     }
     public function getDbId()
     {
        return $this->dbId;
     }
     public function setIn($aIn)
     {
        $this->in = $aIn;
     }
     public function getIn()
     {
        return $this->in;
     }
     public function setOut($aOut)
     {
        $this->out = $aOut;
     }
     public function getOut()
     {
        return $this->out;
     }
     public function setShiftDay($aShiftDay)
     {
        $this->shiftDay = $aShiftDay;
     }
     public function getShiftDay()
     {
        return $this->shiftDay;
     }
     public function setPoPh($aPoPh)
     {
        $this->poPh = $aPoPh;
     }
     public function getPoPh()
     {
        return $this->poPh;
     }
     public function setWorkDay($aWorkDay)
     {
        $this->workDay = $aWorkDay;
     }
     public function getWorkDay()
     {
        return $this->workDay;
     }
     public function setDateProcess($aDateProcess)
     {
        $this->dateProcess = $aDateProcess;
     }
     public function getDateProcess()
     {
        return $this->dateProcess;
     }
     public function setstartDate($astartDate)
     {
        $this->startDate = $astartDate;
     }
     public function getstartDate()
     {
        return $this->startDate;
     }
     public function setendDate($aendDate)
     {
        $this->endDate = $aendDate;
     }
     public function getendDate()
     {
        return $this->endDate;
     }
     public function setBiodataId($aBiodataId)
     {
        $this->biodataId = $aBiodataId;
     }
     public function getBiodataId()
     {
        return $this->biodataId;
     }
     public function setTsId($aTsId)
     {
        $this->tsId = $aTsId;
     }
     public function getTsId()
     {
        return $this->tsId;
     }
     public function setSlipId($aSlipId)
     {
        $this->slipId = $aSlipId;
     }
     public function getSlipId()
     {
        return $this->slipId;
     }
     public function settotalOt($atotalOt)
     {
          $this->totalOt = $atotalOt;
     }
     public function gettotalOt()
     {
          return $this->totalOt;
     }
     public function setot1($aot1)
     {
          $this->ot1 = $aot1;
     }
     public function getot1()
     {
          return $this->ot1;
     }
     public function setot2($aot2)
     {
          $this->ot2 = $aot2;
     }
     public function getot2()
     {
          return $this->ot2;
     }
     public function setot3($aot3)
     {
          $this->ot3 = $aot3;
     }
     public function getot3()
     {
          return $this->ot3;
     }
     public function setot4($aot4)
     {
          $this->ot4 = $aot4;
     }
     public function getot4()
     {
          return $this->ot4;
     }
     public function setnormalTime($anormalTime)
     {
          $this->normalTime = $anormalTime;
     }
     public function getnormalTime()
     {
          return $this->normalTime;
     }
     public function setDept($aDept)
     {
          $this->dept = $aDept;
     }
     public function getDept()
     {
          return $this->dept;
     }
     public function settunjangan($atunjangan)
     {
          $this->tunjangan = $atunjangan;
     }
     public function gettunjangan()
     {
          return $this->tunjangan;
     }
     public function settotal_ot_value($atotal_ot_value)
     {
          $this->total_ot_value = $atotal_ot_value;
     }
     public function gettotal_ot_value()
     {
          return $this->total_ot_value;
     }
     public function settunjanganSiang($atunjanganSiang)
     {
          $this->tunjanganSiang = $atunjanganSiang;
     }
     public function gettunjanganSiang()
     {
          return $this->tunjanganSiang;
     }
     public function settunjanganMalam($atunjanganMalam)
     {
          $this->tunjanganMalam = $atunjanganMalam;
     }
     public function gettunjanganMalam()
     {
          return $this->tunjanganMalam;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
        if($this->dbId =="" || $this->dbId == NULL) 
        {
            $this->dbId = 0; 
        }
        if($this->in =="" || $this->in == NULL) 
        {
            $this->in = 0; 
        }
        if($this->out =="" || $this->out == NULL) 
        {
            $this->out = 0; 
        }
        if($this->shiftDay =="" || $this->shiftDay == NULL) 
        {
            $this->shiftDay = ''; 
        }
        if($this->poPh =="" || $this->poPh == NULL) 
        {
            $this->poPh = ''; 
        }
        if($this->workDay =="" || $this->workDay == NULL) 
        {
            $this->workDay = ''; 
        }
        if($this->dateProcess =="" || $this->dateProcess == NULL) 
        {
            $this->dateProcess = 0; 
        }
        if($this->startDate =="" || $this->startDate == NULL) 
        {
            $this->startDate = 0; 
        }
        if($this->endDate =="" || $this->endDate == NULL) 
        {
            $this->endDate = 0; 
        }
        if($this->biodataId =="" || $this->biodataId == NULL) 
        {
            $this->biodataId = 0; 
        }
        if($this->tsId =="" || $this->tsId == NULL) 
        {
            $this->tsId = 0; 
        }
        if($this->slipId =="" || $this->slipId == NULL) 
        {
            $this->slipId = 0; 
        }
          if($this->totalOt =="" || $this->totalOt == NULL) 
          {
               $this->totalOt = 0; 
          }
          if($this->ot1 =="" || $this->ot1 == NULL) 
          {
               $this->ot1 = 0; 
          }
          if($this->ot2 =="" || $this->ot2 == NULL) 
          {
               $this->ot2 = 0; 
          }
          if($this->ot3 =="" || $this->ot3 == NULL) 
          {
               $this->ot3 = 0; 
          }
          if($this->ot4 =="" || $this->ot4 == NULL) 
          {
               $this->ot4 = 0; 
          }
          if($this->normalTime =="" || $this->normalTime == NULL) 
          {
               $this->normalTime = 0; 
          }
          if($this->dept =="" || $this->dept == NULL) 
          {
               $this->dept = ''; 
          }
          if($this->tunjangan =="" || $this->tunjangan == NULL) 
          {
               $this->tunjangan = 0; 
          }
          if($this->total_ot_value =="" || $this->total_ot_value == NULL) 
          {
               $this->total_ot_value = 0; 
          }
          if($this->tunjanganSiang =="" || $this->tunjanganSiang == NULL) 
          {
               $this->tunjanganSiang = 0; 
          }
          if($this->tunjanganMalam =="" || $this->tunjanganMalam == NULL) 
          {
               $this->tunjanganMalam = 0; 
          }

        $stQuery  = "REPLACE INTO ".$this->table." ";
        $stQuery .= "( ";
        $stQuery .=   "db_id,"; 
        $stQuery .=   "in_db,"; 
        $stQuery .=   "out_db,"; 
        $stQuery .=   "shift_day,"; 
        $stQuery .=   "po_ph,"; 
        $stQuery .=   "work_day,"; 
        $stQuery .=   "date_process,"; 
        $stQuery .=   "biodata_id,"; 
        $stQuery .=   "ts_id,"; 
        $stQuery .=   "slip_id,";
          $stQuery .=   "total_ot,";
          $stQuery .=   "ot_1,";
          $stQuery .=   "ot_2,";
          $stQuery .=   "ot_3,";
          $stQuery .=   "ot_4,";
          $stQuery .=   "normal_time,";
          $stQuery .=   "dept,";
          $stQuery .=   "tunjangan,";
          $stQuery .=   "total_ot_value,"; 
          $stQuery .=   "tunjangan_siang,";
          $stQuery .=   "tunjangan_malam";
        $stQuery .= ") "; 
        $stQuery .= "VALUES "; 
        $stQuery .= "( "; 
        $stQuery .=   " ".$this->dbId.",";
        $stQuery .=   " ".$this->in.",";
        $stQuery .=   " ".$this->out.",";
        $stQuery .=   "'".$this->db->escapeString($this->shiftDay)."',";
        $stQuery .=   "'".$this->db->escapeString($this->poPh)."',";
        $stQuery .=   "'".$this->db->escapeString($this->workDay)."',";
        $stQuery .=   " ".$this->dateProcess.",";
        $stQuery .=   " ".$this->biodataId.",";
        $stQuery .=   " ".$this->tsId.",";
        $stQuery .=   " ".$this->slipId.",";
          $stQuery .=   " ".$this->totalOt.",";
          $stQuery .=   " ".$this->ot1.",";
          $stQuery .=   " ".$this->ot2.",";
          $stQuery .=   " ".$this->ot3.",";
          $stQuery .=   " ".$this->ot4.",";
          $stQuery .=   " ".$this->normalTime.",";
          $stQuery .=   " '".$this->dept."',";
          $stQuery .=   " '".$this->tunjangan."',";
          $stQuery .=   " '".$this->total_ot_value."',";
          $stQuery .=   " '".$this->tunjanganSiang."',";
          $stQuery .=   " '".$this->tunjanganMalam."'";
        $stQuery .= "); "; 
          // echo $stQuery;
          // exit();
        $this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START QUERY INSERT */
     public function getInsQuery()
     {
        if($this->dbId =="" || $this->dbId == NULL) 
        {
            $this->dbId = 0; 
        }
        if($this->in =="" || $this->in == NULL) 
        {
            $this->in = 0; 
        }
        if($this->out =="" || $this->out == NULL) 
        {
            $this->out = 0; 
        }
        if($this->shiftDay =="" || $this->shiftDay == NULL) 
        {
            $this->shiftDay = ''; 
        }
        if($this->poPh =="" || $this->poPh == NULL) 
        {
            $this->poPh = ''; 
        }
        if($this->workDay =="" || $this->workDay == NULL) 
        {
            $this->workDay = ''; 
        }
        if($this->dateProcess =="" || $this->dateProcess == NULL) 
        {
            $this->dateProcess = 0; 
        }
        if($this->startDate =="" || $this->startDate == NULL) 
        {
            $this->startDate = 0; 
        }
        if($this->endDate =="" || $this->endDate == NULL) 
        {
            $this->endDate = 0; 
        }
        if($this->biodataId =="" || $this->biodataId == NULL) 
        {
            $this->biodataId = 0; 
        }
        if($this->tsId =="" || $this->tsId == NULL) 
        {
            $this->tsId = 0; 
        }
        if($this->slipId =="" || $this->slipId == NULL) 
        {
            $this->slipId = 0; 
        }

        $stQuery  = "REPLACE INTO ".$this->table." ";
        $stQuery .= "( ";
        // $stQuery .=   "db_id,"; 
        $stQuery .=   "in,"; 
        $stQuery .=   "out,"; 
        $stQuery .=   "shift_day,"; 
        $stQuery .=   "po_ph,"; 
        $stQuery .=   "work_day,"; 
        $stQuery .=   "date_process,"; 
        $stQuery .=   "month_process,"; 
        $stQuery .=   "year_process,"; 
        $stQuery .=   "biodata_id,"; 
        $stQuery .=   "ts_id,"; 
        $stQuery .=   "slip_id"; 
        $stQuery .= ") "; 
        $stQuery .= "VALUES "; 
        $stQuery .= "( "; 
        // $stQuery .=   " ".$this->dbId.",";
        $stQuery .=   " ".$this->in.",";
        $stQuery .=   " ".$this->out.",";
        $stQuery .=   "'".$this->db->escapeString($this->shiftDay)."',";
        $stQuery .=   "'".$this->db->escapeString($this->poPh)."',";
        $stQuery .=   "'".$this->db->escapeString($this->workDay)."',";
        $stQuery .=   " ".$this->dateProcess.",";
        $stQuery .=   " ".$this->startDate.",";
        $stQuery .=   " ".$this->endDate.",";
        $stQuery .=   " ".$this->biodataId.",";
        $stQuery .=   " ".$this->tsId.",";
        $stQuery .=   " ".$this->slipId."";
        $stQuery .= "); "; 
        return $stQuery; 
     }
     /* END QUERY INSERT */
     /* START UPDATE */
     public function upd($id)
     {
        if($this->dbId =="" || $this->dbId == NULL) 
          {
               $this->dbId = 0; 
          }
          if($this->in =="" || $this->in == NULL) 
          {
               $this->in = 0; 
          }
          if($this->out =="" || $this->out == NULL) 
          {
               $this->out = 0; 
          }
          if($this->shiftDay =="" || $this->shiftDay == NULL) 
          {
               $this->shiftDay = ''; 
          }
          if($this->poPh =="" || $this->poPh == NULL) 
          {
               $this->poPh = ''; 
          }
          if($this->workDay =="" || $this->workDay == NULL) 
          {
               $this->workDay = ''; 
          }
          if($this->dateProcess =="" || $this->dateProcess == NULL) 
          {
               $this->dateProcess = 0; 
          }
          if($this->startDate =="" || $this->startDate == NULL) 
          {
               $this->startDate = 0; 
          }
          if($this->endDate =="" || $this->endDate == NULL) 
          {
               $this->endDate = 0; 
          }
          if($this->biodataId =="" || $this->biodataId == NULL) 
          {
               $this->biodataId = 0; 
          }
          if($this->tsId =="" || $this->tsId == NULL) 
          {
               $this->tsId = 0; 
          }
          if($this->slipId =="" || $this->slipId == NULL) 
          {
               $this->slipId = 0; 
          }
          if($this->totalOt =="" || $this->totalOt == NULL) 
          {
               $this->totalOt = 0; 
          }
          if($this->ot1 =="" || $this->ot1 == NULL) 
          {
               $this->ot1 = 0; 
          }
          if($this->ot2 =="" || $this->ot2 == NULL) 
          {
               $this->ot2 = 0; 
          }
          if($this->ot3 =="" || $this->ot3 == NULL) 
          {
               $this->ot3 = 0; 
          }
          if($this->ot4 =="" || $this->ot4 == NULL) 
          {
               $this->ot4 = 0; 
          }
          if($this->normalTime =="" || $this->normalTime == NULL) 
          {
               $this->normalTime = 0; 
          }
          if($this->dept =="" || $this->dept == NULL) 
          {
               $this->dept = ''; 
          }
          if($this->tunjangan =="" || $this->tunjangan == NULL) 
          {
               $this->tunjangan = 0; 
          }
          if($this->total_ot_value =="" || $this->total_ot_value == NULL) 
          {
               $this->total_ot_value = 0; 
          }
          if($this->tunjanganSiang =="" || $this->tunjanganSiang == NULL) 
          {
               $this->tunjanganSiang = 0; 
          }
          if($this->tunjanganMalam =="" || $this->tunjanganMalam == NULL) 
          {
               $this->tunjanganMalam = 0; 
          }

        $stQuery  = "UPDATE ".$this->table." "; 
        $stQuery .= "SET "; 
        // $stQuery .=   'db_id ='.$this->dbId.','; 
        $stQuery .=   'in_db ='.$this->in.','; 
        $stQuery .=   'out_db ='.$this->out.','; 
        $stQuery .=   "shift_day ='".$this->db->escapeString($this->shiftDay)."', "; 
        $stQuery .=   "po_ph ='".$this->db->escapeString($this->poPh)."', "; 
        $stQuery .=   "work_day ='".$this->db->escapeString($this->workDay)."', "; 
        $stQuery .=   'date_process ='.$this->dateProcess.',';
        $stQuery .=   'biodata_id ='.$this->biodataId.','; 
        $stQuery .=   'ts_id ='.$this->tsId.','; 
        $stQuery .=   "slip_id =".$this->slipId.", "; 
          $stQuery .=   "total_ot =".$this->totalOt.", "; 
          $stQuery .=   "ot_1 =".$this->ot1.", "; 
          $stQuery .=   "ot_2 =".$this->ot2.", "; 
          $stQuery .=   "ot_3 =".$this->ot3.", "; 
          $stQuery .=   "ot_4 =".$this->ot4.", ";      
          $stQuery .=   "normal_time =".$this->normalTime.", "; 
          $stQuery .=   "dept ='".$this->dept."', "; 
          $stQuery .=   "tunjangan =".$this->tunjangan.", "; 
          $stQuery .=   "total_ot_value =".$this->total_ot_value.", "; 
          $stQuery .=   "tunjangan_malam =".$this->tunjanganMalam.", "; 
          $stQuery .=   "tunjangan_siang =".$this->tunjanganSiang." "; 
        $stQuery .= 'WHERE '; 
        $stQuery .=   'db_id = '.$this->db->escapeString($id).''; 
          // echo $stQuery;
          // exit();
        $this->db->query($stQuery); 
     }
     /* END UPDATE */

     public function insertData($data)
     {
          // $this->db->transBegin();
          $builder = $this->db->table($this->table);
          $builder->replace($data);
          // $this->db->close();
          // $this->db->initialize();
          // $this->db->transComplete();
          return true;
     }
     /* START QUERY UPDATE */
     public function getUpdQuery($id)
     {
        if($this->dbId =="" || $this->dbId == NULL) 
        { 
            $this->dbId = 0; 
        } 
        if($this->in =="" || $this->in == NULL) 
        { 
            $this->in = 0; 
        } 
        if($this->out =="" || $this->out == NULL) 
        { 
            $this->out = 0; 
        } 
        if($this->shiftDay =="" || $this->shiftDay == NULL) 
        { 
            $this->shiftDay = ''; 
        } 
        if($this->poPh =="" || $this->poPh == NULL) 
        { 
            $this->poPh = ''; 
        } 
        if($this->workDay =="" || $this->workDay == NULL) 
        { 
            $this->workDay = ''; 
        } 
        if($this->dateProcess =="" || $this->dateProcess == NULL) 
        { 
            $this->dateProcess = 0; 
        } 
        if($this->startDate =="" || $this->startDate == NULL) 
        { 
            $this->startDate = 0; 
        } 
        if($this->endDate =="" || $this->endDate == NULL) 
        { 
            $this->endDate = 0; 
        } 
        if($this->biodataId =="" || $this->biodataId == NULL) 
        { 
            $this->biodataId = 0; 
        } 
        if($this->tsId =="" || $this->tsId == NULL) 
        { 
            $this->tsId = 0; 
        } 
        if($this->slipId =="" || $this->slipId == NULL) 
        { 
            $this->slipId = 0; 
        } 

        $stQuery  = "UPDATE ".$this->table." "; 
        $stQuery .= "SET "; 
        $stQuery .=   'db_id ='.$this->dbId.','; 
        $stQuery .=   'in ='.$this->in.','; 
        $stQuery .=   'out ='.$this->out.','; 
        $stQuery .=   "shift_day ='".$this->db->escapeString($this->shiftDay)."', "; 
        $stQuery .=   "po_ph ='".$this->db->escapeString($this->poPh)."', "; 
        $stQuery .=   "work_day ='".$this->db->escapeString($this->workDay)."', "; 
        $stQuery .=   'date_process ='.$this->dateProcess.','; 
        $stQuery .=   'month_process ='.$this->startDate.','; 
        $stQuery .=   'year_process ='.$this->endDate.','; 
        $stQuery .=   'biodata_id ='.$this->biodataId.','; 
        $stQuery .=   'ts_id ='.$this->tsId.','; 
        $stQuery .=   "slip_id =".$this->slipId." "; 
        $stQuery .= 'WHERE '; 
        $stQuery .=   'db_id = '.$this->db->escapeString($id).''; 
        return $stQuery; 
     }
     /* END QUERY UPDATE */
     /* START DELETE */
     public function del($id)
     {
        $stQuery  = "DELETE FROM ".$this->table." ";      
        $stQuery .= "WHERE db_id = ".$this->db->escapeString($id)."";
        $db->query($stQuery); 
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
        $stQuery  = "SELECT * FROM ".$this->table." "; 
        $query  = $this->db->query($stQuery); 
        $arrayList = $query->getResultArray(); 
        return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
        $stQuery  = "SELECT * FROM ".$this->table." ";     
        $stQuery .= "WHERE db_id = ".$this->db->escapeString($id)."";
        $query  = $this->db->query($stQuery); 
        $arrayRow = $query->getRowArray(); 
        return $arrayRow; 
     }

     // public function getDataDbId($bioId, $dateProcess)
     // {
     //      $stQuery  = "SELECT db_id FROM ".$this->table." ";     
     //      $stQuery .= "WHERE biodata_id = ".$bioId." AND date_process = '".$dateProcess."'";
     //      $query  = $this->db->query($stQuery); 
     //      $arrayRow = $query->getRowArray(); 
     //      return $arrayRow; 
     // }

     public function getDataDbByDate($id)
     {
          $stQuery  = "SELECT * FROM ".$this->table." WHERE date_process BETWEEN '".$this->startDate."' AND '".$this->endDate."' AND biodata_id = '".$id."' ORDER BY date_process;";
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     public function getDateProcessSM($month, $year, $SM)
     {
          $stQuery = "SELECT date_process FROM tr_slip WHERE month_period = '$month' AND year_period = '$year' AND payroll_group = '$SM' LIMIT 1";
          $query  = $this->db->query($stQuery); 
          $arrayRow = $query->getRowArray(); 
          return $arrayRow;
     }

     public function getSlipIdByDate()
     {
          $stQuery  = "SELECT a.*,SUM(work_day) AS total_wd, MIN(date_process) AS mindate, MAX(date_process) AS maxdate ,b.full_name,b.dept,b.emp_position AS position FROM rp_db a, mt_biodata_01 b  WHERE date_process BETWEEN '".$this->startDate."' AND '".$this->endDate."' AND a.biodata_id = b.biodata_id  group BY a.biodata_id ;";   
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     public function getSlipIdByDateSM($SM, $month)
     {
          $stQuery  = "SELECT a.*,SUM(work_day) AS total_wd, MIN(a.date_process) AS mindate, MAX(a.date_process) AS maxdate ,b.full_name,b.dept,b.emp_position AS position FROM rp_db a, mt_biodata_01 b, tr_slip c  WHERE a.date_process BETWEEN '".$this->startDate."' AND '".$this->endDate."' AND a.biodata_id = b.biodata_id AND a.slip_id = c.slip_id AND payroll_group = '$SM' AND month_period = '$month'  group BY a.biodata_id ORDER BY c.ts_id;";   
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getResultArray();
          return $query;
     }

     public function getDataBySlipId($Id)
     {
          $stQuery = "SELECT a.*,b.*,c.*,d.*,e.* FROM tr_slip a, mt_salary b, tr_timesheet c, mt_biodata_01 d, mt_bank e WHERE a.biodata_id = b.biodata_id AND a.ts_id = c.ts_id AND a.biodata_id = d.biodata_id AND a.bank_id = e.bank_id AND a.slip_id ='".$Id."';";
          // echo $stQuery;
          // exit();
         $query = $this->db->query($stQuery)->getResultArray();
          return $query; 
     }

     public function countData($id)
     {
          $stQuery  = "SELECT COUNT(*) AS countId FROM ".$this->table." WHERE date_process BETWEEN '".$this->startDate."' AND '".$this->endDate."' AND slip_id = '".$id."';";
          // echo $stQuery;
          // exit();
          $query = $this->db->query($stQuery)->getRowArray();
          return $query;
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
        $stQuery  = "SELECT * FROM ".$this->table." "; 
        $stQuery .= "WHERE db_id = ".$this->db->escapeString($id)."";
        $query  = $this->db->query($stQuery); 
        $arrayRow = $query->getRowArray(); 
        $this->dbId = $arrayRow['db_id']; 
        $this->in = $arrayRow['in']; 
        $this->out = $arrayRow['out']; 
        $this->shiftDay = $arrayRow['shift_day']; 
        $this->poPh = $arrayRow['po_ph']; 
        $this->workDay = $arrayRow['work_day']; 
        $this->dateProcess = $arrayRow['date_process']; 
        $this->startDate = $arrayRow['month_process']; 
        $this->endDate = $arrayRow['year_process']; 
        $this->biodataId = $arrayRow['biodata_id']; 
        $this->tsId = $arrayRow['ts_id']; 
        $this->slipId = $arrayRow['slip_id']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
        $this->dbId = 0;
          $this->in = 0;
          $this->out = 0;
          $this->shiftDay = '';
          $this->poPh = '';
          $this->workDay = '';
          $this->dateProcess = 0;
          $this->startDate = 0;
          $this->endDate = 0;
          $this->biodataId = 0;
          $this->tsId = 0;
          $this->slipId = 0;
          $this->totalOt = 0;
          $this->ot1 = 0;
          $this->ot2 = 0;
          $this->ot3 = 0;
          $this->ot4 = 0;
          $this->normalTime = 0;
          $this->dept = '';
          $this->tunjangan = 0;
          $this->total_ot_value = 0;
          $this->tunjanganSiang = 0;
          $this->tunjanganMalam = 0;
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
        $strSql = "SELECT ";
        $strSql .= " CASE WHEN id_year = curr_ym THEN ";
        $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
        $strSql .= " ELSE ";
        $strSql .= "   CONCAT(curr_ym, '00001') ";
        $strSql .= " END AS doc_id ";
        $strSql .= "FROM ";
        $strSql .= " (SELECT ";
        $strSql .= "   MAX(".$columnId.") fi,";
        $strSql .= "   LEFT(".$columnId.",4) id_year,";
        $strSql .= "   current_date dt,";
        $strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
        $strSql .= "   CONCAT(";
        $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
        $strSql .= "   LPAD(";
        $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
        $strSql .= "    )";
        $strSql .= "   ) curr_ym,";
        $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
        $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
        $strSql .= " FROM ";
        $strSql .= "   ".$this->table." ";
        $strSql .= " GROUP BY ".$columnId.") a ";
        $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
          // echo $strSql;
          // exit();
        $query  = $this->db->query($strSql); 
        $arrayRow = $query->getRowArray(); 
        if(!isset($arrayRow))
        {
            $curYM = date('ym');
            $arrayRow['doc_id'] = $curYM.'00001';
        }
        return $arrayRow;
     }
     /* END OF ID GENERATOR */
}
