<?php

namespace App\Models\Transaction;

/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Apr 06, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/

use App\Helpers\ConfigurationHelper;
use CodeIgniter\Model;

class SalarySlip extends Model
{
    /* START PRIVATE VARIABLES */
    protected $DBGroup = '';
    protected $table = 'tr_slip';
    protected $primaryKey = 'slip_id';
    protected $returnType = 'array';
    protected $db = null;

    protected $slipId;
    protected $biodataId;
    protected $tsId;
    protected $yearPeriod;
    protected $monthPeriod;
    protected $slipPeriod;
    protected $dateProcess;
    protected $fullName;
    protected $clientName;
    protected $dept;
    protected $position;
    protected $maritalStatus;
    protected $workTotal;
    protected $stand_by_count;
    protected $baseWage;
    protected $dailyCount;
    protected $dailyWage;
    protected $normalTime;
    protected $otCount1;
    protected $otCount2;
    protected $otCount3;
    protected $otCount4;
    protected $ot1;
    protected $ot2;
    protected $ot3;
    protected $ot4;
    protected $variableBonus;
    protected $allowance01;
    protected $allowance02;
    protected $allowance03;
    protected $allowance04;
    protected $allowance05;
    protected $adjustment;
    protected $thr;
    protected $bpjs;
    protected $jk;
    protected $jkk;
    protected $jkm;
    protected $jp;
    protected $jht;
    protected $empBpjs;
    protected $empJp;
    protected $empJht;
    protected $nonTaxAllowance;
    protected $ptkpTotal;
    protected $irregularTax;
    protected $regularTax;
    protected $salaryStatus;
    protected $bs_prorate;
    protected $grossEarn;
    protected $picEdit;
    protected $editTime;
    protected $picInput;
    protected $inputTime;
    protected $jkkjkm;
    protected $jhtjp;
    protected $totalot;
    protected $gaji;
    protected $pph21;
    protected $totalgaji;
    protected $round;
    protected $wdTotal;
    protected $tunjangan;
    protected $gajipokok;
    protected $unpaid;
    protected $taxreg;
    protected $taxnonreg;
    protected $taxpenalty;
    protected $payrollGroup;
    protected $bankId;
    protected $statusRemarks;
    protected $tunjanganJabatan;
    protected $potonganAbsensi;
    protected $netto;
    protected $bonusNonReg;
    protected $Brutto;
    protected $isEnd;
    protected $checkEnd;
    /* END PRIVATE VARIABLES */
    /* START CONSTRUCTOR */
    public function __construct()
    {
        parent::__construct();
        $this->db = \Config\Database::connect($this->DBGroup, false);
        $this->slipId = 0;
        $this->biodataId = '';
        $this->tsId = 0;
        $this->yearPeriod = 0;
        $this->monthPeriod = '';
        $this->slipPeriod = 0;
        $this->dateProcess = '1700-01-01';
        $this->fullName = '';
        $this->clientName = '';
        $this->dept = '';
        $this->position = '';
        $this->maritalStatus = '';
        $this->workTotal = 0;
        $this->stand_by_count = 0;
        $this->baseWage = 0;
        $this->dailyCount = 0;
        $this->dailyWage = 0;
        $this->normalTime = 0;
        $this->otCount1 = 0;
        $this->otCount2 = 0;
        $this->otCount3 = 0;
        $this->otCount4 = 0;
        $this->ot1 = 0;
        $this->ot2 = 0;
        $this->ot3 = 0;
        $this->ot4 = 0;
        $this->variableBonus = 0;
        $this->allowance01 = 0;
        $this->allowance02 = 0;
        $this->allowance03 = 0;
        $this->allowance04 = 0;
        $this->allowance05 = 0;
        $this->adjustment = 0;
        $this->thr = 0;
        $this->bpjs = 0;
        $this->jk = 0;
        $this->jkk = 0;
        $this->jkm = 0;
        $this->jp = 0;
        $this->jht = 0;
        $this->empBpjs = 0;
        $this->empJp = 0;
        $this->empJht = 0;
        $this->nonTaxAllowance = 0;
        $this->ptkpTotal = 0;
        $this->irregularTax = 0;
        $this->regularTax = 0;
        $this->salaryStatus = '';
        $this->bs_prorate = '';
        $this->grossEarn = 0;
        $this->picEdit = '';
        $this->editTime = '1700-01-01 00:00:00';
        $this->picInput = '';
        $this->inputTime = '1700-01-01 00:00:00';
        $this->jkkjkm = 0;
        $this->jhtjp = 0;
        $this->totalot = 0;
        $this->gaji = 0;
        $this->pph21 = 0;
        $this->totalgaji = 0;
        $this->round = 0;
        $this->wdTotal = 0;
        $this->tunjangan = 0;
        $this->gajipokok = 0;
        $this->unpaid = 0;
        $this->taxreg = 0;
        $this->taxnonreg = 0;
        $this->taxpenalty = 0;
        $this->payrollGroup = '';
        $this->bankId = 0;
        $this->statusRemarks = "";
        $this->tunjanganJabatan = 0;
        $this->potonganAbsensi = 0;
        $this->netto = 0;
        $this->bonusNonReg = 0;
        $this->Brutto = 0;
        $this->isEnd = 0;
        $this->checkEnd = '';
    }
    /* END CONSTRUCTOR */

    /* START GENERATE SETTER AND GETTER */
    public function setSlipId($aSlipId)
    {
        $this->slipId = $aSlipId;
    }
    public function getSlipId()
    {
        return $this->slipId;
    }
    public function setBiodataId($aBiodataId)
    {
        $this->biodataId = $aBiodataId;
    }
    public function getBiodataId()
    {
        return $this->biodataId;
    }
    public function setClientName($param)
    {
        $this->clientName = $param;
    }
    public function getClientName()
    {
        return $this->clientName;
    }
    public function setTsId($aTsId)
    {
        $this->tsId = $aTsId;
    }
    public function getTsId()
    {
        return $this->tsId;
    }
    public function setYearPeriod($aYearPeriod)
    {
        $this->yearPeriod = $aYearPeriod;
    }
    public function getYearPeriod()
    {
        return $this->yearPeriod;
    }
    public function setMonthPeriod($aMonthPeriod)
    {
        $this->monthPeriod = $aMonthPeriod;
    }
    public function getMonthPeriod()
    {
        return $this->monthPeriod;
    }
    public function setSlipPeriod($aSlipPeriod)
    {
        $this->slipPeriod = $aSlipPeriod;
    }
    public function getSlipPeriod()
    {
        return $this->slipPeriod;
    }
    public function setdateProcess($adateProcess)
    {
        $this->dateProcess = $adateProcess;
    }
    public function getdateProcess()
    {
        return $this->dateProcess;
    }
    public function setFullName($aFullName)
    {
        $this->fullName = $aFullName;
    }
    public function getFullName()
    {
        return $this->fullName;
    }
    public function setDept($aDept)
    {
        $this->dept = $aDept;
    }
    public function getDept()
    {
        return $this->dept;
    }
    public function setPosition($aPosition)
    {
        $this->position = $aPosition;
    }
    public function getPosition()
    {
        return $this->position;
    }
    public function setMaritalStatus($aMaritalStatus)
    {
        $this->maritalStatus = $aMaritalStatus;
    }
    public function getMaritalStatus()
    {
        return $this->maritalStatus;
    }
    public function setWorkTotal($aWorkTotal)
    {
        $this->workTotal = $aWorkTotal;
    }
    public function getWorkTotal()
    {
        return $this->workTotal;
    }
    public function setstand_by_count($astand_by_count)
    {
        $this->stand_by_count = $astand_by_count;
    }
    public function getstand_by_count()
    {
        return $this->stand_by_count;
    }
    public function setBaseWage($aBaseWage)
    {
        $this->baseWage = $aBaseWage;
    }
    public function getBaseWage()
    {
        return $this->baseWage;
    }
    public function setDailyCount($aDailyCount)
    {
        $this->dailyCount = $aDailyCount;
    }
    public function getDailyCount()
    {
        return $this->dailyCount;
    }
    public function setDailyWage($aDailyWage)
    {
        $this->dailyWage = $aDailyWage;
    }
    public function getDailyWage()
    {
        return $this->dailyWage;
    }
    public function setNormalTime($aNormalTime)
    {
        $this->normalTime = $aNormalTime;
    }
    public function getNormalTime()
    {
        return $this->normalTime;
    }
    public function setOtCount1($aotCount1)
    {
        $this->otCount1 = $aotCount1;
    }
    public function getOtCount1()
    {
        return $this->otCount1;
    }
    public function setOtCount2($aotCount2)
    {
        $this->otCount2 = $aotCount2;
    }
    public function getOtCount2()
    {
        return $this->otCount2;
    }
    public function setOtCount3($aotCount3)
    {
        $this->otCount3 = $aotCount3;
    }
    public function getOtCount3()
    {
        return $this->otCount3;
    }
    public function setOtCount4($aotCount4)
    {
        $this->otCount4 = $aotCount4;
    }
    public function getOtCount4()
    {
        return $this->otCount4;
    }

    public function setOt1($aot1)
    {
        $this->ot1 = $aot1;
    }
    public function getOt1()
    {
        return $this->ot1;
    }
    public function setOt2($aot2)
    {
        $this->ot2 = $aot2;
    }
    public function getOt2()
    {
        return $this->ot2;
    }
    public function setOt3($aot3)
    {
        $this->ot3 = $aot3;
    }
    public function getOt3()
    {
        return $this->ot3;
    }
    public function setOt4($aot4)
    {
        $this->ot4 = $aot4;
    }
    public function getOt4()
    {
        return $this->ot4;
    }
    public function setVariableBonus($aVariableBonus)
    {
        $this->variableBonus = $aVariableBonus;
    }
    public function getVariableBonus()
    {
        return $this->variableBonus;
    }
    public function setAllowance01($aAllowance01)
    {
        $this->allowance01 = $aAllowance01;
    }
    public function getAllowance01()
    {
        return $this->allowance01;
    }
    public function setAllowance02($aAllowance02)
    {
        $this->allowance02 = $aAllowance02;
    }
    public function getAllowance02()
    {
        return $this->allowance02;
    }
    public function setAllowance03($aAllowance03)
    {
        $this->allowance03 = $aAllowance03;
    }
    public function getAllowance03()
    {
        return $this->allowance03;
    }
    public function setAllowance04($aAllowance04)
    {
        $this->allowance04 = $aAllowance04;
    }
    public function getAllowance04()
    {
        return $this->allowance04;
    }
    public function setAllowance05($aAllowance05)
    {
        $this->allowance05 = $aAllowance05;
    }
    public function getAllowance05()
    {
        return $this->allowance05;
    }
    public function setAdjustment($aAdjustment)
    {
        $this->adjustment = $aAdjustment;
    }
    public function getAdjustment()
    {
        return $this->adjustment;
    }
    public function setThr($aThr)
    {
        $this->thr = $aThr;
    }
    public function getThr()
    {
        return $this->thr;
    }
    public function setBpjs($aBpjs)
    {
        $this->bpjs = $aBpjs;
    }
    public function getBpjs()
    {
        return $this->bpjs;
    }
    public function setJk($aJk)
    {
        $this->jk = $aJk;
    }
    public function getJk()
    {
        return $this->jk;
    }
    public function setJkk($aJkk)
    {
        $this->jkk = $aJkk;
    }
    public function getJkk()
    {
        return $this->jkk;
    }
    public function setJkm($aJkm)
    {
        $this->jkm = $aJkm;
    }
    public function getJkm()
    {
        return $this->jkm;
    }
    public function setJp($aJp)
    {
        $this->jp = $aJp;
    }
    public function getJp()
    {
        return $this->jp;
    }
    public function setJht($aJht)
    {
        $this->jht = $aJht;
    }
    public function getJht()
    {
        return $this->jht;
    }
    public function setEmpBpjs($aEmpBpjs)
    {
        $this->empBpjs = $aEmpBpjs;
    }
    public function getEmpBpjs()
    {
        return $this->empBpjs;
    }
    public function setEmpJp($aEmpJp)
    {
        $this->empJp = $aEmpJp;
    }
    public function getEmpJp()
    {
        return $this->empJp;
    }
    public function setEmpJht($aEmpJht)
    {
        $this->empJht = $aEmpJht;
    }
    public function getEmpJht()
    {
        return $this->empJht;
    }
    public function setNonTaxAllowance($aNonTaxAllowance)
    {
        $this->nonTaxAllowance = $aNonTaxAllowance;
    }
    public function getNonTaxAllowance()
    {
        return $this->nonTaxAllowance;
    }
    public function setPtkpTotal($aPtkpTotal)
    {
        $this->ptkpTotal = $aPtkpTotal;
    }
    public function getPtkpTotal()
    {
        return $this->ptkpTotal;
    }
    public function setIrregularTax($aIrregularTax)
    {
        $this->irregularTax = $aIrregularTax;
    }
    public function getIrregularTax()
    {
        return $this->irregularTax;
    }
    public function setRegularTax($aRegularTax)
    {
        $this->regularTax = $aRegularTax;
    }
    public function getRegularTax()
    {
        return $this->regularTax;
    }
    public function setSalaryStatus($aSalaryStatus)
    {
        $this->salaryStatus = $aSalaryStatus;
    }
    public function getSalaryStatus()
    {
        return $this->salaryStatus;
    }
    public function setbs_prorate($abs_prorate)
    {
        $this->bs_prorate = $abs_prorate;
    }
    public function getbs_prorate()
    {
        return $this->bs_prorate;
    }
    public function setGrossEarn($aGrossEarn)
    {
        $this->grossEarn = $aGrossEarn;
    }
    public function getGrossEarn()
    {
        return $this->grossEarn;
    }
    public function setPicEdit($aPicEdit)
    {
        $this->picEdit = $aPicEdit;
    }
    public function getPicEdit()
    {
        return $this->picEdit;
    }
    public function setEditTime($aEditTime)
    {
        $this->editTime = $aEditTime;
    }
    public function getEditTime()
    {
        return $this->editTime;
    }
    public function setPicInput($aPicInput)
    {
        $this->picInput = $aPicInput;
    }
    public function getPicInput()
    {
        return $this->picInput;
    }
    public function setInputTime($aInputTime)
    {
        $this->inputTime = $aInputTime;
    }
    public function getInputTime()
    {
        return $this->inputTime;
    }
    public function setjkkjkm($ajkkjkm)
    {
        $this->jkkjkm = $ajkkjkm;
    }
    public function getjkkjkm()
    {
        return $this->jkkjkm;
    }
    public function setJhtjp($aJhtjp)
    {
        $this->jhtjp = $aJhtjp;
    }
    public function getJhtjp()
    {
        return $this->jhtjp;
    }
    public function settotalot($atotalot)
    {
        $this->totalot = $atotalot;
    }
    public function gettotalot()
    {
        return $this->totalot;
    }
    public function setgaji($agaji)
    {
        $this->gaji = $agaji;
    }
    public function getgaji()
    {
        return $this->gaji;
    }
    public function setpph21($apph21)
    {
        $this->pph21 = $apph21;
    }
    public function getpph21()
    {
        return $this->pph21;
    }
    public function settotalgaji($atotalgaji)
    {
        $this->totalgaji = $atotalgaji;
    }
    public function gettotalgaji()
    {
        return $this->totalgaji;
    }
    public function setround($around)
    {
        $this->round = $around;
    }
    public function getround()
    {
        return $this->round;
    }
    public function setwdTotal($awdTotal)
    {
        $this->wdTotal = $awdTotal;
    }
    public function getwdTotal()
    {
        return $this->wdTotal;
    }
    public function settunjangan($atunjangan)
    {
        $this->tunjangan = $atunjangan;
    }
    public function gettunjangan()
    {
        return $this->tunjangan;
    }
    public function setgajipokok($agajipokok)
    {
        $this->gajipokok = $agajipokok;
    }
    public function getgajipokok()
    {
        return $this->gajipokok;
    }
    public function setunpaid($aunpaid)
    {
        $this->unpaid = $aunpaid;
    }
    public function getunpaid()
    {
        return $this->unpaid;
    }
    public function settaxreg($ataxreg)
    {
        $this->taxreg = $ataxreg;
    }
    public function gettaxreg()
    {
        return $this->taxreg;
    }
    public function settaxnonreg($ataxnonreg)
    {
        $this->taxnonreg = $ataxnonreg;
    }
    public function gettaxnonreg()
    {
        return $this->taxnonreg;
    }
    public function settaxpenalty($ataxpenalty)
    {
        $this->taxpenalty = $ataxpenalty;
    }
    public function gettaxpenalty()
    {
        return $this->taxpenalty;
    }
    public function setpayrollGroup($apayrollGroup)
    {
        $this->payrollGroup = $apayrollGroup;
    }
    public function getpayrollGroup()
    {
        return $this->payrollGroup;
    }
    public function setbankId($abankId)
    {
        $this->bankId = $abankId;
    }
    public function getbankId()
    {
        return $this->bankId;
    }
    public function settunjanganJabatan($atunjanganJabatan)
    {
        $this->tunjanganJabatan = $atunjanganJabatan;
    }
    public function gettunjanganJabatan()
    {
        return $this->tunjanganJabatan;
    }
    public function setpotonganAbsensi($apotonganAbsensi)
    {
        $this->potonganAbsensi = $apotonganAbsensi;
    }
    public function getpotonganAbsensi()
    {
        return $this->potonganAbsensi;
    }
    public function setstatusRemarks($astatusRemarks)
    {
        $this->statusRemarks = $astatusRemarks;
    }
    public function getstatusRemarks()
    {
        return $this->statusRemarks;
    }
    public function setnetto($anetto)
    {
        $this->netto = $anetto;
    }
    public function getnetto()
    {
        return $this->netto;
    }
    public function setBrutto($aBrutto)
    {
        $this->Brutto = $aBrutto;
    }
    public function getBrutto()
    {
        return $this->Brutto;
    }
    public function setbonusNonReg($abonusNonReg)
    {
        $this->bonusNonReg = $abonusNonReg;
    }
    public function getbonusNonReg()
    {
        return $this->bonusNonReg;
    }
    public function setcheckEnd($acheckEnd)
    {
        $this->checkEnd = $acheckEnd;
    }
    public function getcheckEnd()
    {
        return $this->checkEnd;
    }
    public function setisEnd($aisEnd)
    {
        $this->isEnd = $aisEnd;
    }
    public function getisEnd()
    {
        return $this->isEnd;
    }

    /* END GENERATE SETTER AND GETTER */
    /* START INSERT */
    public function ins()
    {
        $db = \Config\Database::connect();

        // Pastikan semua field punya nilai default
        $this->slipId                = $this->slipId ?? 0;
        $this->biodataId             = $this->biodataId ?? '';
        $this->tsId                  = $this->tsId ?? 0;
        $this->yearPeriod            = $this->yearPeriod ?? 0;
        $this->monthPeriod           = $this->monthPeriod ?? '';
        $this->dateProcess           = $this->dateProcess ?? '0000-00-00';
        $this->fullName              = $this->fullName ?? '';
        $this->dept                  = $this->dept ?? '';
        $this->clientName            = $this->clientName ?? '';
        $this->positionName          = $this->position ?? '';
        $this->normalTime            = $this->normalTime ?? 0;
        $this->otCount1              = $this->otCount1 ?? 0;
        $this->otCount2              = $this->otCount2 ?? 0;
        $this->otCount3              = $this->otCount3 ?? 0;
        $this->otCount4              = $this->otCount4 ?? 0;
        $this->ot1                   = $this->ot1 ?? 0;
        $this->ot2                   = $this->ot2 ?? 0;
        $this->ot3                   = $this->ot3 ?? 0;
        $this->ot4                   = $this->ot4 ?? 0;
        $this->empJp                 = $this->empJp ?? 0;
        $this->empJht                = $this->empJht ?? 0;
        $this->inputTime             = $this->inputTime ?? date('Y-m-d H:i:s');
        $this->editTime              = $this->editTime ?? date('Y-m-d H:i:s');
        // $this->overtimeTotal         = $this->overtimeTotal ?? 0;


        // $this->isEnd                 = $this->isEnd ?? 0;
        // $this->checkFinal            = $this->checkFinal ?? '';
        // $this->gajiPokok             = $this->gajiPokok ?? 0;
        // $this->allowanceTotal        = $this->allowanceTotal ?? 0;
        // susun data untuk insert
        $data = [
            'slip_id'                => $this->slipId,
            'biodata_id'             => $this->biodataId,
            'ts_id'                  => $this->tsId,
            'year_period'            => $this->yearPeriod,
            'month_period'           => $this->monthPeriod,
            'slip_period'           => $this->slipPeriod,
            'marital_status'           => $this->maritalStatus,
            'date_process'           => $this->dateProcess,
            'full_name'              => $this->fullName,
            'dept'                   => $this->dept,
            'client_name'            => $this->clientName,
            'position'               => $this->position,
            'bs_prorate'            => $this->bs_prorate,
            'base_wage'            => $this->baseWage,
            'daily_wage'            => $this->dailyWage,
            'normal_time'            => $this->normalTime,
            'ot_1'                   => $this->ot1,
            'ot_2'                   => $this->ot2,
            'ot_3'                   => $this->ot3,
            'ot_4'                   => $this->ot4,
            'ot_count1'              => $this->otCount1,
            'ot_count2'              => $this->otCount2,
            'ot_count3'              => $this->otCount3,
            'ot_count4'              => $this->otCount4,
            'bpjs'                   => $this->bpjs,
            'jkkjkm'                 => $this->jkkjkm,
            'jht'                    => $this->jht,
            'jp'                     => $this->jp,
            'emp_bpjs'               => $this->empBpjs,
            'emp_jht'                => $this->empJht,
            'emp_jp'                 => $this->empJp,
            'unpaid'                 => $this->unpaid,
            'potongan_absensi'       => $this->potonganAbsensi,
            'ptkp_total'             => $this->ptkpTotal,
            'non_tax_allowance'      => $this->nonTaxAllowance,
            // 'is_end'                 => $this->isEnd,
            // 'check_final'            => $this->checkFinal,
            'pic_input'            => $this->picInput,
            'input_time'             => $this->inputTime,
            'edit_time'              => $this->editTime,
        ];

        // insert ke database pakai Query Builder
        $db->table($this->table)->insert($data);
        return $db->affectedRows() > 0;
    }

    /* END INSERT */
    /* START QUERY INSERT */
    public function getInsQuery()
    {
        if ($this->slipId == "" || $this->slipId == NULL) {
            $this->slipId = 0;
        }
        if ($this->biodataId == "" || $this->biodataId == NULL) {
            $this->biodataId = '';
        }
        if ($this->tsId == "" || $this->tsId == NULL) {
            $this->tsId = 0;
        }
        if ($this->yearPeriod == "" || $this->yearPeriod == NULL) {
            $this->yearPeriod = 0;
        }
        if ($this->monthPeriod == "" || $this->monthPeriod == NULL) {
            $this->monthPeriod = '';
        }
        if ($this->slipPeriod == "" || $this->slipPeriod == NULL) {
            $this->slipPeriod = 0;
        }
        if ($this->fullName == "" || $this->fullName == NULL) {
            $this->fullName = '';
        }
        if ($this->dept == "" || $this->dept == NULL) {
            $this->dept = '';
        }
        if ($this->position == "" || $this->position == NULL) {
            $this->position = '';
        }
        if ($this->maritalStatus == "" || $this->maritalStatus == NULL) {
            $this->maritalStatus = '';
        }
        if ($this->workTotal == "" || $this->workTotal == NULL) {
            $this->workTotal = 0;
        }
        if ($this->stand_by_count == "" || $this->stand_by_count == NULL) {
            $this->stand_by_count = 0;
        }
        if ($this->baseWage == "" || $this->baseWage == NULL) {
            $this->baseWage = 0;
        }
        if ($this->dailyCount == "" || $this->dailyCount == NULL) {
            $this->dailyCount = 0;
        }
        if ($this->dailyWage == "" || $this->dailyWage == NULL) {
            $this->dailyWage = 0;
        }
        if ($this->variableBonus == "" || $this->variableBonus == NULL) {
            $this->variableBonus = 0;
        }
        if ($this->allowance01 == "" || $this->allowance01 == NULL) {
            $this->allowance01 = 0;
        }
        if ($this->allowance02 == "" || $this->allowance02 == NULL) {
            $this->allowance02 = 0;
        }
        if ($this->allowance03 == "" || $this->allowance03 == NULL) {
            $this->allowance03 = 0;
        }
        if ($this->allowance04 == "" || $this->allowance04 == NULL) {
            $this->allowance04 = 0;
        }
        if ($this->allowance05 == "" || $this->allowance05 == NULL) {
            $this->allowance05 = 0;
        }
        if ($this->adjustment == "" || $this->adjustment == NULL) {
            $this->adjustment = 0;
        }
        if ($this->thr == "" || $this->thr == NULL) {
            $this->thr = 0;
        }
        if ($this->bpjs == "" || $this->bpjs == NULL) {
            $this->bpjs = 0;
        }
        if ($this->jk == "" || $this->jk == NULL) {
            $this->jk = 0;
        }
        if ($this->jkk == "" || $this->jkk == NULL) {
            $this->jkk = 0;
        }
        if ($this->jkm == "" || $this->jkm == NULL) {
            $this->jkm = 0;
        }
        if ($this->jp == "" || $this->jp == NULL) {
            $this->jp = 0;
        }
        if ($this->jht == "" || $this->jht == NULL) {
            $this->jht = 0;
        }
        if ($this->empBpjs == "" || $this->empBpjs == NULL) {
            $this->empBpjs = 0;
        }
        if ($this->empJp == "" || $this->empJp == NULL) {
            $this->empJp = 0;
        }
        if ($this->empJht == "" || $this->empJht == NULL) {
            $this->empJht = 0;
        }
        if ($this->nonTaxAllowance == "" || $this->nonTaxAllowance == NULL) {
            $this->nonTaxAllowance = 0;
        }
        if ($this->ptkpTotal == "" || $this->ptkpTotal == NULL) {
            $this->ptkpTotal = 0;
        }
        if ($this->irregularTax == "" || $this->irregularTax == NULL) {
            $this->irregularTax = 0;
        }
        if ($this->regularTax == "" || $this->regularTax == NULL) {
            $this->regularTax = 0;
        }
        if ($this->salaryStatus == "" || $this->salaryStatus == NULL) {
            $this->salaryStatus = '';
        }
        if ($this->bs_prorate == "" || $this->bs_prorate == NULL) {
            $this->bs_prorate = '';
        }
        if ($this->grossEarn == "" || $this->grossEarn == NULL) {
            $this->grossEarn = 0;
        }
        if ($this->picEdit == "" || $this->picEdit == NULL) {
            $this->picEdit = '';
        }
        if ($this->editTime == "" || $this->editTime == NULL) {
            $this->editTime = '1700-01-01 00:00:00';
        }
        if ($this->picInput == "" || $this->picInput == NULL) {
            $this->picInput = '';
        }
        if ($this->inputTime == "" || $this->inputTime == NULL) {
            $this->inputTime = '1700-01-01 00:00:00';
        }

        $stQuery  = "INSERT INTO " . $this->table . " ";
        $stQuery .= "( ";
        $stQuery .=   "slip_id,";
        $stQuery .=   "biodata_id,";
        $stQuery .=   "ts_id,";
        $stQuery .=   "year_period,";
        $stQuery .=   "month_period,";
        $stQuery .=   "slip_period,";
        $stQuery .=   "full_name,";
        $stQuery .=   "dept,";
        $stQuery .=   "position,";
        $stQuery .=   "marital_status,";
        $stQuery .=   "work_total,";
        $stQuery .=   "stand_by_count,";
        $stQuery .=   "base_wage,";
        $stQuery .=   "daily_count,";
        $stQuery .=   "daily_wage,";
        $stQuery .=   "variable_bonus,";
        $stQuery .=   "allowance_01,";
        $stQuery .=   "allowance_02,";
        $stQuery .=   "allowance_03,";
        $stQuery .=   "allowance_04,";
        $stQuery .=   "allowance_05,";
        $stQuery .=   "adjustment,";
        $stQuery .=   "thr,";
        $stQuery .=   "bpjs,";
        $stQuery .=   "jk,";
        $stQuery .=   "jkk,";
        $stQuery .=   "jkm,";
        $stQuery .=   "jp,";
        $stQuery .=   "jht,";
        $stQuery .=   "emp_bpjs,";
        $stQuery .=   "emp_jp,";
        $stQuery .=   "emp_jht,";
        $stQuery .=   "non_tax_allowance,";
        $stQuery .=   "ptkp_total,";
        $stQuery .=   "irregular_tax,";
        $stQuery .=   "regular_tax,";
        $stQuery .=   "salary_status,";
        $stQuery .=   "bs_prorate,";
        $stQuery .=   "gross_earn,";
        $stQuery .=   "pic_edit,";
        $stQuery .=   "edit_time,";
        $stQuery .=   "pic_input,";
        $stQuery .=   "input_time";
        $stQuery .= ") ";
        $stQuery .= "VALUES ";
        $stQuery .= "( ";
        $stQuery .=   " " . $this->slipId . ",";
        $stQuery .=   "'" . $this->biodataId . "',";
        $stQuery .=   " " . $this->tsId . ",";
        $stQuery .=   " " . $this->yearPeriod . ",";
        $stQuery .=   "'" . $this->monthPeriod . "',";
        $stQuery .=   " " . $this->slipPeriod . ",";
        $stQuery .=   "'" . $this->fullName . "',";
        $stQuery .=   "'" . $this->dept . "',";
        $stQuery .=   "'" . $this->position . "',";
        $stQuery .=   "'" . $this->maritalStatus . "',";
        $stQuery .=   " " . $this->workTotal . ",";
        $stQuery .=   "'" . $this->stand_by_count . "',";
        $stQuery .=   " " . $this->baseWage . ",";
        $stQuery .=   " " . $this->dailyCount . ",";
        $stQuery .=   " " . $this->dailyWage . ",";
        $stQuery .=   " " . $this->variableBonus . ",";
        $stQuery .=   " " . $this->allowance01 . ",";
        $stQuery .=   " " . $this->allowance02 . ",";
        $stQuery .=   " " . $this->allowance03 . ",";
        $stQuery .=   " " . $this->allowance04 . ",";
        $stQuery .=   " " . $this->allowance05 . ",";
        $stQuery .=   " " . $this->adjustment . ",";
        $stQuery .=   " " . $this->thr . ",";
        $stQuery .=   " " . $this->bpjs . ",";
        $stQuery .=   " " . $this->jk . ",";
        $stQuery .=   " " . $this->jkk . ",";
        $stQuery .=   " " . $this->jkm . ",";
        $stQuery .=   " " . $this->jp . ",";
        $stQuery .=   " " . $this->jht . ",";
        $stQuery .=   " " . $this->empBpjs . ",";
        $stQuery .=   " " . $this->empJp . ",";
        $stQuery .=   " " . $this->empJht . ",";
        $stQuery .=   " " . $this->nonTaxAllowance . ",";
        $stQuery .=   " " . $this->ptkpTotal . ",";
        $stQuery .=   " " . $this->irregularTax . ",";
        $stQuery .=   " " . $this->regularTax . ",";
        $stQuery .=   "'" . $this->salaryStatus . "',";
        $stQuery .=   "'" . $this->bs_prorate . "',";
        $stQuery .=   " " . $this->grossEarn . ",";
        $stQuery .=   "'" . $this->picEdit . "',";
        $stQuery .=   "'" . $this->editTime . "',";
        $stQuery .=   "'" . $this->picInput . "',";
        $stQuery .=   "'" . $this->inputTime . "'";
        $stQuery .= "); ";
        return $stQuery;
    }
    public function updates($tsId)
    {
        if ($this->slipId == "" || $this->slipId == NULL) {
            $this->slipId = 0;
        }
        if ($this->biodataId == "" || $this->biodataId == NULL) {
            $this->biodataId = '';
        }
        if ($this->tsId == "" || $this->tsId == NULL) {
            $this->tsId = 0;
        }
        if ($this->yearPeriod == "" || $this->yearPeriod == NULL) {
            $this->yearPeriod = 0;
        }
        if ($this->monthPeriod == "" || $this->monthPeriod == NULL) {
            $this->monthPeriod = '';
        }
        if ($this->slipPeriod == "" || $this->slipPeriod == NULL) {
            $this->slipPeriod = 0;
        }
        if ($this->dateProcess == "" || $this->dateProcess == NULL) {
            $this->dateProcess = '1700-01-01';
        }
        if ($this->fullName == "" || $this->fullName == NULL) {
            $this->fullName = '';
        }
        if ($this->dept == "" || $this->dept == NULL) {
            $this->dept = '';
        }
        if ($this->position == "" || $this->position == NULL) {
            $this->position = '';
        }
        if ($this->maritalStatus == "" || $this->maritalStatus == NULL) {
            $this->maritalStatus = '';
        }
        if ($this->workTotal == "" || $this->workTotal == NULL) {
            $this->workTotal = 0;
        }
        if ($this->stand_by_count == "" || $this->stand_by_count == NULL) {
            $this->stand_by_count = 0;
        }
        if ($this->baseWage == "" || $this->baseWage == NULL) {
            $this->baseWage = 0;
        }
        if ($this->dailyCount == "" || $this->dailyCount == NULL) {
            $this->dailyCount = 0;
        }
        if ($this->dailyWage == "" || $this->dailyWage == NULL) {
            $this->dailyWage = 0;
        }
        if ($this->normalTime == "" || $this->normalTime == NULL) {
            $this->normalTime = 0;
        }
        if ($this->otCount1 == "" || $this->otCount1 == NULL) {
            $this->otCount1 = 0;
        }
        if ($this->otCount2 == "" || $this->otCount2 == NULL) {
            $this->otCount2 = 0;
        }
        if ($this->otCount3 == "" || $this->otCount3 == NULL) {
            $this->otCount3 = 0;
        }
        if ($this->otCount4 == "" || $this->otCount4 == NULL) {
            $this->otCount4 = 0;
        }
        if ($this->ot1 == "" || $this->ot1 == NULL) {
            $this->ot1 = 0;
        }
        if ($this->ot2 == "" || $this->ot2 == NULL) {
            $this->ot2 = 0;
        }
        if ($this->ot2 == "" || $this->ot2 == NULL) {
            $this->ot2 = 0;
        }
        if ($this->ot3 == "" || $this->ot3 == NULL) {
            $this->ot3 = 0;
        }
        if ($this->ot4 == "" || $this->ot4 == NULL) {
            $this->ot4 = 0;
        }
        if ($this->variableBonus == "" || $this->variableBonus == NULL) {
            $this->variableBonus = 0;
        }
        if ($this->allowance01 == "" || $this->allowance01 == NULL) {
            $this->allowance01 = 0;
        }
        if ($this->allowance02 == "" || $this->allowance02 == NULL) {
            $this->allowance02 = 0;
        }
        if ($this->allowance03 == "" || $this->allowance03 == NULL) {
            $this->allowance03 = 0;
        }
        if ($this->allowance04 == "" || $this->allowance04 == NULL) {
            $this->allowance04 = 0;
        }
        if ($this->allowance05 == "" || $this->allowance05 == NULL) {
            $this->allowance05 = 0;
        }
        if ($this->adjustment == "" || $this->adjustment == NULL) {
            $this->adjustment = 0;
        }
        if ($this->thr == "" || $this->thr == NULL) {
            $this->thr = 0;
        }
        if ($this->bpjs == "" || $this->bpjs == NULL) {
            $this->bpjs = 0;
        }
        if ($this->jk == "" || $this->jk == NULL) {
            $this->jk = 0;
        }
        if ($this->jkk == "" || $this->jkk == NULL) {
            $this->jkk = 0;
        }
        if ($this->jkm == "" || $this->jkm == NULL) {
            $this->jkm = 0;
        }
        if ($this->jp == "" || $this->jp == NULL) {
            $this->jp = 0;
        }
        if ($this->jht == "" || $this->jht == NULL) {
            $this->jht = 0;
        }
        if ($this->empBpjs == "" || $this->empBpjs == NULL) {
            $this->empBpjs = 0;
        }
        if ($this->empJp == "" || $this->empJp == NULL) {
            $this->empJp = 0;
        }
        if ($this->empJht == "" || $this->empJht == NULL) {
            $this->empJht = 0;
        }
        if ($this->nonTaxAllowance == "" || $this->nonTaxAllowance == NULL) {
            $this->nonTaxAllowance = 0;
        }
        if ($this->ptkpTotal == "" || $this->ptkpTotal == NULL) {
            $this->ptkpTotal = 0;
        }
        if ($this->irregularTax == "" || $this->irregularTax == NULL) {
            $this->irregularTax = 0;
        }
        if ($this->regularTax == "" || $this->regularTax == NULL) {
            $this->regularTax = 0;
        }
        if ($this->salaryStatus == "" || $this->salaryStatus == NULL) {
            $this->salaryStatus = '';
        }
        if ($this->bs_prorate == "" || $this->bs_prorate == NULL) {
            $this->bs_prorate = '';
        }
        if ($this->grossEarn == "" || $this->grossEarn == NULL) {
            $this->grossEarn = 0;
        }
        if ($this->picEdit == "" || $this->picEdit == NULL) {
            $this->picEdit = '';
        }
        if ($this->editTime == "" || $this->editTime == NULL) {
            $this->editTime = '1700-01-01 00:00:00';
        }
        if ($this->picInput == "" || $this->picInput == NULL) {
            $this->picInput = '';
        }
        if ($this->inputTime == "" || $this->inputTime == NULL) {
            $this->inputTime = '1700-01-01 00:00:00';
        }
        if ($this->jkkjkm == "" || $this->jkkjkm == NULL) {
            $this->jkkjkm = 0;
        }
        if ($this->jhtjp == "" || $this->jhtjp == NULL) {
            $this->jhtjp = 0;
        }
        if ($this->totalot == "" || $this->totalot == NULL) {
            $this->totalot = 0;
        }
        if ($this->gaji == "" || $this->gaji == NULL) {
            $this->gaji = 0;
        }
        if ($this->pph21 == "" || $this->pph21 == NULL) {
            $this->pph21 = 0;
        }
        if ($this->totalgaji == "" || $this->totalgaji == NULL) {
            $this->totalgaji = 0;
        }
        if ($this->round == "" || $this->round == NULL) {
            $this->round = 0;
        }
        if ($this->payrollGroup == "" || $this->payrollGroup == NULL) {
            $this->payrollGroup = '';
        }
        if ($this->bankId == "" || $this->bankId == NULL) {
            $this->bankId = 0;
        }
        if ($this->tunjanganJabatan == "" || $this->tunjanganJabatan == NULL) {
            $this->tunjanganJabatan = 0;
        }



        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'biodata_id ="' . $this->biodataId . '",';
        $stQuery .=   'ts_id =' . $this->tsId . ',';
        $stQuery .=   'year_period =' . $this->yearPeriod . ',';
        $stQuery .=   'month_period ="' . $this->monthPeriod . '",';
        $stQuery .=   'slip_period ="' . $this->slipPeriod . '",';
        $stQuery .=   'date_process ="' . $this->dateProcess . '",';
        $stQuery .=   'full_name ="' . $this->fullName . '",';
        $stQuery .=   'position ="' . $this->position . '",';
        $stQuery .=   'dept ="' . $this->dept . '",';
        $stQuery .=   'normal_time ="' . $this->normalTime . '",';
        $stQuery .=   'ot_count1 ="' . $this->otCount1 . '",';
        $stQuery .=   'ot_count2 ="' . $this->otCount2 . '",';
        $stQuery .=   'ot_count3 ="' . $this->otCount3 . '",';
        $stQuery .=   'ot_count4 ="' . $this->otCount4 . '",';
        $stQuery .=   'ot1 ="' . $this->ot1 . '",';
        $stQuery .=   'ot2 ="' . $this->ot2 . '",';
        $stQuery .=   'ot3 ="' . $this->ot3 . '",';
        $stQuery .=   'ot4 ="' . $this->ot4 . '",';
        $stQuery .=   'work_total =' . $this->workTotal . ',';
        $stQuery .=   'allowance_01 =' . $this->allowance01 . ',';
        $stQuery .=   'allowance_02 =' . $this->allowance02 . ',';
        $stQuery .=   'bpjs =' . $this->bpjs . ',';
        $stQuery .=   'jkk =' . $this->jkk . ',';
        $stQuery .=   'jkm =' . $this->jkm . ',';
        $stQuery .=   'jp =' . $this->jp . ',';
        $stQuery .=   'jht =' . $this->jht . ',';
        $stQuery .=   'emp_bpjs =' . $this->empBpjs . ',';
        $stQuery .=   'emp_jp =' . $this->empJp . ',';
        $stQuery .=   'emp_jht =' . $this->empJht . ',';
        $stQuery .=   'pic_edit ="' . $this->picInput . '",';
        $stQuery .=   'edit_time ="' . $this->inputTime . '",';
        $stQuery .=   'jkkjkm =' . $this->jkkjkm . ',';
        $stQuery .=   'jhtjp =' . $this->jhtjp . ',';
        $stQuery .=   'totalot =' . $this->totalot . ',';
        $stQuery .=   'gaji =' . $this->gaji . ',';
        $stQuery .=   'gajipokok =' . $this->gajipokok . ',';
        $stQuery .=   'pph21 =' . $this->pph21 . ',';
        $stQuery .=   'totalgaji =' . $this->totalgaji . ',';
        $stQuery .=   "round ='" . $this->round . "', ";
        $stQuery .=   "payroll_group ='" . $this->payrollGroup . "', ";
        $stQuery .=   "bank_id ='" . $this->bankId . "' ";
        $stQuery .= "WHERE ";
        $stQuery .=   'ts_id = ' . $tsId . '';
        // echo $stQuery;
        // exit(); 
        $this->db->query($stQuery);
    }

    public function Rep($ts_id)
    {
        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'brutto =' . $this->Brutto . ',';
        $stQuery .=   'totalot =' . $this->totalot . ',';
        $stQuery .=   'gaji =' . $this->gaji . ',';
        $stQuery .=   'pph21 =' . $this->pph21 . ',';
        $stQuery .=   'totalgaji =' . $this->totalgaji . ',';
        $stQuery .=   'wdtotal =' . $this->wdTotal . ',';
        $stQuery .=   'tunjangan =' . $this->tunjangan . ',';
        // $stQuery .=   'gajipokok ='.$this->gajipokok.',';
        $stQuery .=   'unpaid =' . $this->unpaid . ',';
        $stQuery .=   'tax_reg =' . $this->taxreg . ',';
        $stQuery .=   'tax_non_reg =' . $this->taxnonreg . ',';
        $stQuery .=   'tax_penalty =' . $this->taxpenalty . ',';
        $stQuery .=   "round ='" . $this->round . "', ";
        $stQuery .=   "tunjangan_jabatan ='" . $this->tunjanganJabatan . "', ";
        $stQuery .=   "potongan_absensi ='" . $this->potonganAbsensi . "', ";
        $stQuery .=   "netto ='" . $this->netto . "', ";
        $stQuery .=   "bonus_non_reg ='" . $this->bonusNonReg . "', ";
        $stQuery .=   "check_final ='" . $this->checkFinal . "' ";
        $stQuery .= "WHERE ";
        $stQuery .=   'ts_id = ' . $ts_id . '';
        // echo $stQuery;
        // exit(); 
        $this->db->query($stQuery);
    }
    public function validasiBpjs($id, $month, $year, $date)
    {
        $stQuery = " SELECT bpjs BPJS, jht JHT, emp_jp JP, jkkjkm JKKJKM FROM tr_slip WHERE biodata_id = '" . $id . "' AND month_period = $month AND year_period = $year AND slip_period < $date;";
        $query = $this->db->query($stQuery)->getRowArray();
        // echo $stQuery;
        // exit();
        return $query;
    }

    public function UpdTunjangan($ts_id)
    {
        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'jkkjkm =' . $this->jkkjkm . ',';
        $stQuery .=   'bpjs =' . $this->bpjs . ',';
        $stQuery .=   'emp_jht =' . $this->empJht . ',';
        $stQuery .=   'emp_jp =' . $this->empJp . ',';
        $stQuery .=   'emp_bpjs =' . $this->empBpjs . ',';
        $stQuery .=   'jht =' . $this->jht . ',';
        $stQuery .=   'jhtjp =' . $this->jhtjp . '';
        $stQuery .= " WHERE ";
        $stQuery .=   'ts_id = ' . $ts_id . '';
        // echo $stQuery;
        // exit(); 
        $this->db->query($stQuery);
    }
    /* END QUERY INSERT */
    /* START UPDATE */
    public function upd($slipId)
    {
        if ($this->slipId == "" || $this->slipId == NULL) {
            $this->slipId = 0;
        }
        if ($this->fullName == "" || $this->fullName == NULL) {
            $this->fullName = '';
        }
        if ($this->allowance03 == "" || $this->allowance03 == NULL) {
            $this->allowance03 = 0;
        }
        if ($this->adjustment == "" || $this->adjustment == NULL) {
            $this->adjustment = 0;
        }
        if ($this->statusRemarks == "" || $this->statusRemarks == NULL) {
            $this->statusRemarks = "";
        }
        if ($this->thr == "" || $this->thr == NULL) {
            $this->thr = 0;
        }
        if ($this->picEdit == "" || $this->picEdit == NULL) {
            $this->picEdit = '';
        }
        if ($this->editTime == "" || $this->editTime == NULL) {
            $this->editTime = '1700-01-01 00:00:00';
        }

        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'slip_id =' . $this->slipId . ',';
        $stQuery .=   "full_name ='" . $this->fullName . "', ";
        $stQuery .=   'allowance_03 =' . $this->allowance03 . ',';
        $stQuery .=   'adjustment =' . $this->adjustment . ',';
        $stQuery .=   'thr =' . $this->thr . ',';
        $stQuery .=   "status_remarks ='" . $this->statusRemarks . "',";
        $stQuery .=   "pic_edit ='" . $this->picEdit . "', ";
        $stQuery .=   "edit_time ='" . $this->editTime . "' ";
        $stQuery .= 'WHERE ';
        $stQuery .=   'slip_id = ' . $this->slipId . '';
        // echo $stQuery;
        // exit();
        $this->db->query($stQuery);
    }
    /* END UPDATE */

    function getDueDate($id)
    {
        $stQuery = "SELECT slip_id, full_name, due_date FROM tr_slip WHERE slip_id = $id";
        $query = $this->db->query($stQuery)->getRowArray();
        return $query;
    }

    public function updateDueDate($SM,  $startDate, $month, $year, $dueDate)
    {
        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'due_date ="' . $dueDate . '"';
        $stQuery .= ' WHERE ';
        $stQuery .=   'payroll_group = "' . $SM . '" AND slip_period = "' . $startDate . '" AND month_period = "' . $month . '" AND year_period =' . $year;
        // echo $stQuery;
        // exit();
        $this->db->query($stQuery);
    }

    /* START QUERY UPDATE */
    public function getUpdQuery($id)
    {
        if ($this->slipId == "" || $this->slipId == NULL) {
            $this->slipId = 0;
        }
        if ($this->biodataId == "" || $this->biodataId == NULL) {
            $this->biodataId = '';
        }
        if ($this->tsId == "" || $this->tsId == NULL) {
            $this->tsId = 0;
        }
        if ($this->yearPeriod == "" || $this->yearPeriod == NULL) {
            $this->yearPeriod = 0;
        }
        if ($this->monthPeriod == "" || $this->monthPeriod == NULL) {
            $this->monthPeriod = '';
        }
        if ($this->slipPeriod == "" || $this->slipPeriod == NULL) {
            $this->slipPeriod = 0;
        }
        if ($this->fullName == "" || $this->fullName == NULL) {
            $this->fullName = '';
        }
        if ($this->dept == "" || $this->dept == NULL) {
            $this->dept = '';
        }
        if ($this->position == "" || $this->position == NULL) {
            $this->position = '';
        }
        if ($this->maritalStatus == "" || $this->maritalStatus == NULL) {
            $this->maritalStatus = '';
        }
        if ($this->workTotal == "" || $this->workTotal == NULL) {
            $this->workTotal = 0;
        }
        if ($this->stand_by_count == "" || $this->stand_by_count == NULL) {
            $this->stand_by_count = 0;
        }
        if ($this->baseWage == "" || $this->baseWage == NULL) {
            $this->baseWage = 0;
        }
        if ($this->dailyCount == "" || $this->dailyCount == NULL) {
            $this->dailyCount = 0;
        }
        if ($this->dailyWage == "" || $this->dailyWage == NULL) {
            $this->dailyWage = 0;
        }
        if ($this->variableBonus == "" || $this->variableBonus == NULL) {
            $this->variableBonus = 0;
        }
        if ($this->allowance01 == "" || $this->allowance01 == NULL) {
            $this->allowance01 = 0;
        }
        if ($this->allowance02 == "" || $this->allowance02 == NULL) {
            $this->allowance02 = 0;
        }
        if ($this->allowance03 == "" || $this->allowance03 == NULL) {
            $this->allowance03 = 0;
        }
        if ($this->allowance04 == "" || $this->allowance04 == NULL) {
            $this->allowance04 = 0;
        }
        if ($this->allowance05 == "" || $this->allowance05 == NULL) {
            $this->allowance05 = 0;
        }
        if ($this->adjustment == "" || $this->adjustment == NULL) {
            $this->adjustment = 0;
        }
        if ($this->thr == "" || $this->thr == NULL) {
            $this->thr = 0;
        }
        if ($this->bpjs == "" || $this->bpjs == NULL) {
            $this->bpjs = 0;
        }
        if ($this->jk == "" || $this->jk == NULL) {
            $this->jk = 0;
        }
        if ($this->jkk == "" || $this->jkk == NULL) {
            $this->jkk = 0;
        }
        if ($this->jkm == "" || $this->jkm == NULL) {
            $this->jkm = 0;
        }
        if ($this->jp == "" || $this->jp == NULL) {
            $this->jp = 0;
        }
        if ($this->jht == "" || $this->jht == NULL) {
            $this->jht = 0;
        }
        if ($this->empBpjs == "" || $this->empBpjs == NULL) {
            $this->empBpjs = 0;
        }
        if ($this->empJp == "" || $this->empJp == NULL) {
            $this->empJp = 0;
        }
        if ($this->empJht == "" || $this->empJht == NULL) {
            $this->empJht = 0;
        }
        if ($this->nonTaxAllowance == "" || $this->nonTaxAllowance == NULL) {
            $this->nonTaxAllowance = 0;
        }
        if ($this->ptkpTotal == "" || $this->ptkpTotal == NULL) {
            $this->ptkpTotal = 0;
        }
        if ($this->irregularTax == "" || $this->irregularTax == NULL) {
            $this->irregularTax = 0;
        }
        if ($this->regularTax == "" || $this->regularTax == NULL) {
            $this->regularTax = 0;
        }
        if ($this->salaryStatus == "" || $this->salaryStatus == NULL) {
            $this->salaryStatus = '';
        }
        if ($this->bs_prorate == "" || $this->bs_prorate == NULL) {
            $this->bs_prorate = '';
        }
        if ($this->grossEarn == "" || $this->grossEarn == NULL) {
            $this->grossEarn = 0;
        }
        if ($this->picEdit == "" || $this->picEdit == NULL) {
            $this->picEdit = '';
        }
        if ($this->editTime == "" || $this->editTime == NULL) {
            $this->editTime = '1700-01-01 00:00:00';
        }
        if ($this->picInput == "" || $this->picInput == NULL) {
            $this->picInput = '';
        }
        if ($this->inputTime == "" || $this->inputTime == NULL) {
            $this->inputTime = '1700-01-01 00:00:00';
        }

        $stQuery  = "UPDATE " . $this->table . " ";
        $stQuery .= "SET ";
        $stQuery .=   'slip_id =' . $this->slipId . ',';
        $stQuery .=   "biodata_id ='" . $this->biodataId . "', ";
        $stQuery .=   'ts_id =' . $this->tsId . ',';
        $stQuery .=   'year_period =' . $this->yearPeriod . ',';
        $stQuery .=   "month_period ='" . $this->monthPeriod . "', ";
        $stQuery .=   'slip_period =' . $this->slipPeriod . ',';
        $stQuery .=   "full_name ='" . $this->fullName . "', ";
        $stQuery .=   "dept ='" . $this->dept . "', ";
        $stQuery .=   "position ='" . $this->position . "', ";
        $stQuery .=   "marital_status ='" . $this->maritalStatus . "', ";
        $stQuery .=   'work_total =' . $this->workTotal . ',';
        $stQuery .=   "stand_by_count ='" . $this->stand_by_count . "', ";
        $stQuery .=   'base_wage =' . $this->baseWage . ',';
        $stQuery .=   'daily_count =' . $this->dailyCount . ',';
        $stQuery .=   'daily_wage =' . $this->dailyWage . ',';
        $stQuery .=   'variable_bonus =' . $this->variableBonus . ',';
        $stQuery .=   'allowance_01 =' . $this->allowance01 . ',';
        $stQuery .=   'allowance_02 =' . $this->allowance02 . ',';
        $stQuery .=   'allowance_03 =' . $this->allowance03 . ',';
        $stQuery .=   'allowance_04 =' . $this->allowance04 . ',';
        $stQuery .=   'allowance_05 =' . $this->allowance05 . ',';
        $stQuery .=   'adjustment =' . $this->adjustment . ',';
        $stQuery .=   'thr =' . $this->thr . ',';
        $stQuery .=   'bpjs =' . $this->bpjs . ',';
        $stQuery .=   'jk =' . $this->jk . ',';
        $stQuery .=   'jkk =' . $this->jkk . ',';
        $stQuery .=   'jkm =' . $this->jkm . ',';
        $stQuery .=   'jp =' . $this->jp . ',';
        $stQuery .=   'jht =' . $this->jht . ',';
        $stQuery .=   'emp_bpjs =' . $this->empBpjs . ',';
        $stQuery .=   'emp_jp =' . $this->empJp . ',';
        $stQuery .=   'emp_jht =' . $this->empJht . ',';
        $stQuery .=   'non_tax_allowance =' . $this->nonTaxAllowance . ',';
        $stQuery .=   'ptkp_total =' . $this->ptkpTotal . ',';
        $stQuery .=   'irregular_tax =' . $this->irregularTax . ',';
        $stQuery .=   'regular_tax =' . $this->regularTax . ',';
        $stQuery .=   "salary_status ='" . $this->salaryStatus . "', ";
        $stQuery .=   "bs_prorate ='" . $this->bs_prorate . "', ";
        $stQuery .=   'gross_earn =' . $this->grossEarn . ',';
        $stQuery .=   "pic_edit ='" . $this->picEdit . "', ";
        $stQuery .=   "edit_time ='" . $this->editTime . "', ";
        $stQuery .=   "pic_input ='" . $this->picInput . "', ";
        $stQuery .=   "input_time ='" . $this->inputTime . "' ";
        $stQuery .= 'WHERE ';
        $stQuery .=   'slip_id = ' . $id . '';
        return $stQuery;
    }

    function getSlipById($slipId)
    {
        $stQuery = "SELECT * FROM tr_slip WHERE slip_id = " . $slipId . "";
        $query = $this->db->query($stQuery)->getRowArray();
        // echo $stQuery;
        // exit();
        return $query;
    }

    function getValidasiData($startDate, $tahun, $bulan, $sm)
    {
        $stQuery = "SELECT * FROM tr_slip WHERE slip_period = " . $startDate . " AND month_period = '" . $bulan . "' AND year_period = " . $tahun . "";
        if ($sm != 'all') {
            $stQuery .= " AND payroll_group = '" . $sm . "'";
        }
        $query = $this->db->query($stQuery)->getResultArray();
        // echo $stQuery;
        // exit();
        return $query;
    }
    /* END QUERY UPDATE */
    /* START DELETE */
    public function del($id)
    {
        $stQuery  = "DELETE FROM " . $this->table . " ";
        $stQuery .= "WHERE slip_id = " . $id . "";
        $this->db->query($stQuery);
    }
    /* END DELETE */
    /* START GET ALL DATA */
    public function getAll()
    {
        $stQuery  = "SELECT * FROM " . $this->table . " ";
        $query  = $this->db->query($stQuery);
        $arrayList = $query->getResultArray();
        return $arrayList;
    }
    /* END GET ALL DATA */
    /* START GET DATA BY ID */
    public function getById($id)
    {
        $stQuery  = "SELECT * FROM " . $this->table . " ";
        $stQuery .= "WHERE slip_id = " . $id . "";
        $query  = $this->db->query($stQuery);
        $arrayRow = $query->getRowArray();
        return $arrayRow;
    }

    public function getTotalPajak($biodata_id, $start_date, $end_date)
    {
        $stQuery  = "SELECT SUM(pph21) pph21 FROM `db_hris_daily`.`tr_slip` WHERE biodata_id='" . $biodata_id . "' AND 
                         due_date BETWEEN '" . $start_date . "' AND '" . $end_date . "'";

        $query  = $this->db->query($stQuery);
        $arrayRow = $query->getRowArray();
        return $arrayRow;
    }

    /* END GET DATA BY ID */
    /* START GET OBJECT DATA BY ID */
    public function setObjectById($id)
    {
        $stQuery  = "SELECT * FROM " . $this->table . " ";
        $stQuery .= "WHERE slip_id = " . $id . "";
        $query  = $this->db->query($stQuery);
        $arrayRow = $query->getRowArray();
        $this->slipId = $arrayRow['slip_id'];
        $this->biodataId = $arrayRow['biodata_id'];
        $this->tsId = $arrayRow['ts_id'];
        $this->yearPeriod = $arrayRow['year_period'];
        $this->monthPeriod = $arrayRow['month_period'];
        $this->slipPeriod = $arrayRow['slip_period'];
        $this->fullName = $arrayRow['full_name'];
        $this->dept = $arrayRow['dept'];
        $this->position = $arrayRow['position'];
        $this->maritalStatus = $arrayRow['marital_status'];
        $this->workTotal = $arrayRow['work_total'];
        $this->stand_by_count = $arrayRow['stand_by_count'];
        $this->baseWage = $arrayRow['base_wage'];
        $this->dailyCount = $arrayRow['daily_count'];
        $this->dailyWage = $arrayRow['daily_wage'];
        $this->variableBonus = $arrayRow['variable_bonus'];
        $this->allowance01 = $arrayRow['allowance_01'];
        $this->allowance02 = $arrayRow['allowance_02'];
        $this->allowance03 = $arrayRow['allowance_03'];
        $this->allowance04 = $arrayRow['allowance_04'];
        $this->allowance05 = $arrayRow['allowance_05'];
        $this->adjustment = $arrayRow['adjustment'];
        $this->thr = $arrayRow['thr'];
        $this->bpjs = $arrayRow['bpjs'];
        $this->jk = $arrayRow['jk'];
        $this->jkk = $arrayRow['jkk'];
        $this->jkm = $arrayRow['jkm'];
        $this->jp = $arrayRow['jp'];
        $this->jht = $arrayRow['jht'];
        $this->empBpjs = $arrayRow['emp_bpjs'];
        $this->empJp = $arrayRow['emp_jp'];
        $this->empJht = $arrayRow['emp_jht'];
        $this->nonTaxAllowance = $arrayRow['non_tax_allowance'];
        $this->ptkpTotal = $arrayRow['ptkp_total'];
        $this->irregularTax = $arrayRow['irregular_tax'];
        $this->regularTax = $arrayRow['regular_tax'];
        $this->salaryStatus = $arrayRow['salary_status'];
        $this->bs_prorate = $arrayRow['bs_prorate'];
        $this->grossEarn = $arrayRow['gross_earn'];
        $this->picEdit = $arrayRow['pic_edit'];
        $this->editTime = $arrayRow['edit_time'];
        $this->picInput = $arrayRow['pic_input'];
        $this->inputTime = $arrayRow['input_time'];
    }
    /* END GET OBJECT DATA BY ID */
    /* START OF RESET VALUES */
    public function resetValues()
    {
        $this->slipId = 0;
        $this->biodataId = '';
        $this->tsId = 0;
        $this->yearPeriod = 0;
        $this->monthPeriod = '';
        $this->slipPeriod = 0;
        $this->fullName = '';
        $this->dept = '';
        $this->position = '';
        $this->maritalStatus = '';
        $this->workTotal = 0;
        $this->stand_by_count = 0;
        $this->baseWage = 0;
        $this->dailyCount = 0;
        $this->dailyWage = 0;
        $this->variableBonus = 0;
        $this->allowance01 = 0;
        $this->allowance02 = 0;
        $this->allowance03 = 0;
        $this->allowance04 = 0;
        $this->allowance05 = 0;
        $this->adjustment = 0;
        $this->thr = 0;
        $this->bpjs = 0;
        $this->jk = 0;
        $this->jkk = 0;
        $this->jkm = 0;
        $this->jp = 0;
        $this->jht = 0;
        $this->empBpjs = 0;
        $this->empJp = 0;
        $this->empJht = 0;
        $this->nonTaxAllowance = 0;
        $this->ptkpTotal = 0;
        $this->irregularTax = 0;
        $this->regularTax = 0;
        $this->salaryStatus = '';
        $this->bs_prorate = '';
        $this->grossEarn = 0;
        $this->picEdit = '';
        $this->editTime = '1700-01-01 00:00:00';
        $this->picInput = '';
        $this->inputTime = '1700-01-01 00:00:00';
    }
    /* END OF RESET VALUES */
    /* START OF ID GENERATOR */
    public function generateId($columnId)
    {
        $strSql = "SELECT ";
        $strSql .= " CASE WHEN id_year = curr_ym THEN ";
        $strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
        $strSql .= " ELSE ";
        $strSql .= "   CONCAT(curr_ym, '00001') ";
        $strSql .= " END AS doc_id ";
        $strSql .= "FROM ";
        $strSql .= " (SELECT ";
        $strSql .= "   MAX(" . $columnId . ") fi,";
        $strSql .= "   LEFT(" . $columnId . ",4) id_year,";
        $strSql .= "   current_date dt,";
        $strSql .= "   RIGHT(" . $columnId . ", 5) curr_id,";
        $strSql .= "   CONCAT(";
        $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
        $strSql .= "   LPAD(";
        $strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
        $strSql .= "    )";
        $strSql .= "   ) curr_ym,";
        $strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
        $strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
        $strSql .= " FROM ";
        $strSql .= "   " . $this->table . " ";
        $strSql .= " GROUP BY " . $columnId . ") a ";
        $strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
        $query  = $this->db->query($strSql);
        $arrayRow = $query->getRowArray();
        if (!isset($arrayRow)) {
            $curYM = date('ym');
            $arrayRow['doc_id'] = $curYM . '00001';
        }
        return $arrayRow;
    }
    /* END OF ID GENERATOR */

    public function getDataTax($biodataId, $bulan, $tahun)
    {

        $start_date         = $tahun . '-01-01';
        $min_year           = date('Y', strtotime('-1 month', strtotime($start_date)));
        $min_month          = date('m', strtotime('-1 month', strtotime($start_date)));

        // $sql = "SELECT SUM(pph21) AS total_pph21, SUM(brutto) AS total_kotor FROM tr_slip
        //       WHERE biodata_id = ?
        //       AND ((year_period = ? AND month_period >= 12)
        //       OR (year_period = ? AND month_period < ?))";

        // $totalPPH21 = DB::connection('db_hris_daily')->select($sql, [$biodataId, $min_year, $tahun, $bulan]);

        $sql = "SELECT SUM(pph21) AS total_pph21, SUM(brutto) AS total_kotor, SUM(emp_jp) as total_jp, SUM(emp_jht) as total_jht
               FROM tr_slip
               WHERE biodata_id = " . $biodataId . "
               AND ((year_period = " . $min_year . " AND month_period >= 12)
               OR (year_period = " . $tahun . " AND month_period < " . $bulan . "))";

        // Bind the parameters and execute the query
        $result = $this->db->query($sql)->getRow();

        return $result;
    }

    public function deleteByBiodataIdPeriod($biodataId, $clientName, $year, $month)
    {
        $st  = "DELETE FROM " . $this->table . " ";
        $st .= 'WHERE month_period =' . '"' . $month . '"';
        $st .= 'AND year_period =' . '"' . $year . '"';
        $st .= 'AND biodata_id =' . '"' . $biodataId . '"';
        $st .= 'AND client_name =' . '"' . $clientName . '"';
        $this->db->query($st);
    }

    public function getPayrollList($clientName, $year, $month, $dataGroup)
    {
        // Koneksi ke database lain (misalnya 'db_hris_sgt' dari app/Config/Database.php)
        $db = \Config\Database::connect();
        $builder = $db->table('tr_slip as ss');

        $builder->select([
            'ss.slip_id',
            'ms.biodata_id',
            'ss.full_name',
            'ss.client_name as company_name',
            'ss.dept',
            'ss.position',
            'ss.check_final'
        ]);

        $builder->join('mt_salary as ms', 'ss.biodata_id = ms.biodata_id');

        $builder->where('ss.client_name', $clientName)
            ->where('ss.year_period', $year)
            ->where('ss.month_period', $month);

        if ($dataGroup != 'All') {
            $builder->where('ss.dept', $dataGroup);
        }

        $builder->orderBy('ss.full_name', 'ASC');

        return $builder->get()->getResult(); // atau getResultArray() jika ingin hasil array

    }

    public function deleteByIdPeriod($biodataId, $clientName, $year, $month)
    {
        return $this->where('biodata_id', $biodataId)
            ->where('year_period', $year)
            ->where('month_period', $month)
            ->where('client_name', $clientName)
            ->delete();
    }

    public static function fetchOvertimeData($biodataId, $clientName, $dept, $yearPeriod, $monthPeriod)
    {
        // Koneksi ke database (gunakan koneksi 'db_hris_sgt' jika sudah di config)
        $db = \Config\Database::connect();
        // mbr.is_bpjs_health, mbr.is_bpjs_tk,  mbr.npwp_no, tro.permit_total,  mr.is_end
        $sql = "
    SELECT
        mr.*, 
        tro.*, 
        mbr.biodata_id, mbr.full_name, mbr.marital_status,
        mbr.emp_position AS position,
        mr.ts_id, mr.roster_base, mr.dept,
        tro.attend_total, tro.attend_in_off, tro.ph_total, tro.in_ph_total, tro.vacation_days,
        ms.monthly AS basic_salary,
        ms.daily AS daily_basic,
        mr.d01, mr.d02, mr.d03, mr.d04, mr.d05, mr.d06, mr.d07, mr.d08, mr.d09, mr.d10,
        mr.d11, mr.d12, mr.d13, mr.d14, mr.d15, mr.d16, mr.d17, mr.d18, mr.d19, mr.d20,
        mr.d21, mr.d22, mr.d23, mr.d24, mr.d25, mr.d26, mr.d27, mr.d28, mr.d29, mr.d30, mr.d31
    FROM mt_salary ms
    JOIN mt_biodata_01 mbr ON ms.biodata_id = mbr.biodata_id
    JOIN tr_timesheet mr ON mbr.biodata_id = mr.biodata_id
    JOIN tr_overtime tro ON mbr.biodata_id = tro.bio_rec_id
    WHERE 
        mr.year_process = ?
        AND mr.month_process = ?
        AND tro.year_period = ?
        AND tro.month_period = ?
        AND ms.company_name = ?
        AND mr.client_name = ?
        AND mbr.is_active = 1
";

        // Binding parameter
        $bindings = [$yearPeriod, $monthPeriod, $yearPeriod, $monthPeriod, $clientName, $clientName];

        if (!empty($biodataId)) {
            $sql .= " AND mr.biodata_id = ?";
            $bindings[] = $biodataId;
        }

        if ($dept != 'All') {
            $sql .= " AND mr.dept = ?";
            $bindings[] = $dept;
        }

        // Eksekusi query
        $query = $db->query($sql, $bindings);
        return $query->getResultArray(); // bisa getResult() kalau mau objek
    }

    public function getPtkpByPeriod($biodataId, $clientName, $year, $month)
    {
        return $this->select('ptkp_total')
            ->where('biodata_id', $biodataId)
            ->where('client_name', $clientName)
            ->where('year_period', $year)
            ->where('month_period', $month)
            ->first();
    }

    public function getSalaryDetails($clientName, $monthPeriod, $yearPeriod, $group)
    {
        // Koneksi database ke grup 'db_hris_sgt' (pastikan sudah didefinisikan di app/Config/Database.php)
        $db = \Config\Database::connect();

        $sql = "
        SELECT ss.slip_id, ss.client_name, ss.biodata_id, ss.is_end, ss.full_name
        FROM mt_salary ms
        JOIN mt_biodata_01 mb ON ms.biodata_id = mb.biodata_id
        JOIN tr_slip ss ON mb.biodata_id = ss.biodata_id
        WHERE ss.client_name = ?
        AND ss.month_period = ?
        AND ss.year_period = ?
        AND mb.is_active = 1
    ";

        $params = [$clientName, $monthPeriod, $yearPeriod];

        if ($group != "All") {
            $sql .= " AND ss.dept = ?";
            $params[] = $group;
        }

        $sql .= " ORDER BY mb.full_name";
        $query = $db->query($sql, $params);
        return $query->getResultObject();
    }

    public function getObjectById($id)
    {
        // Koneksi ke database
        $db = \Config\Database::connect();

        // Query SQL
        $sql = "SELECT * FROM tr_slip WHERE slip_id = ?";

        // Jalankan query
        $query = $db->query($sql, [$id]);

        // Ambil hasil sebagai object (satu baris)
        return $query->getRowObject();
    }

    public function getSlipDataWithoutTax($clientName, $slipId)
    {
        // Koneksi ke database (ubah 'db_hris_sgt' kalau nama koneksi berbeda di Config\Database.php)
        $db = \Config\Database::connect();

        // Query SQL
        $sql = "
        SELECT
            ss.*,
            mb.biodata_id AS biodata_id,
            ss.base_wage AS salary_basic,
            ss.bs_prorate,
            tro.*,
            mr.*,
            ss.emp_jp AS employeeJp,
            ss.emp_jht AS employeeJht
        FROM tr_slip ss
        JOIN mt_biodata_01 mb ON ss.biodata_id = mb.biodata_id
        JOIN tr_timesheet mr ON mb.biodata_id = mr.biodata_id
        JOIN tr_overtime tro ON mb.biodata_id = tro.bio_rec_id
        WHERE ss.client_name = ?
        AND ss.slip_id = ?
        AND ss.year_period = tro.year_period
        AND ss.month_period = tro.month_period
        AND ss.year_period = mr.year_process
        AND ss.month_period = mr.month_process
        LIMIT 1
    ";

        // Jalankan query
        $query = $db->query($sql, [$clientName, $slipId]);

        // Tampilkan query terakhir untuk debugging
        echo "<pre>Last Query: " . $db->getLastQuery() . "</pre>";

        // Jika ada error SQL
        if ($db->error()['code'] !== 0) {
            echo "<pre>DB Error: " . $db->error()['message'] . "</pre>";
            return null;
        }

        // Ambil hasil dalam bentuk object (karena mirip `selectOne` Laravel)
        return $query->getRowObject();
    }

    public function getPtkpByBiodataId($clientName, $bioRecId, $yearPeriod, $monthPeriod)
    {
        return $this->select('ptkp_total')
            ->where('client_name', $clientName)
            ->where('month_period', $monthPeriod)
            ->where('year_period', $yearPeriod)
            ->where('biodata_id', $bioRecId)
            ->get()
            ->getRow(); // untuk hasil object (setara first() di Laravel)
    }
    public function findSalarySlipById($id)
    {
        $result = $this->where('slip_id', $id)->first();

        if (!$result) {
            throw new \CodeIgniter\Exceptions\PageNotFoundException("Salary slip dengan ID {$id} tidak ditemukan");
        }

        return $result;
    }

    public function getSummaryPayrollData($clientName, $year, $month, $dataGroup)
    {
        // Koneksi database CI4
        $db = \Config\Database::connect();

        $builder = $db->table('tr_slip ss')
            ->select('ss.*, mb.biodata_id as biodata_id, ss.base_wage as salary_basic,
                  mb.gender, mb.id_card_no, mb.current_address, mb.id_card_address,
                  ss.bs_prorate, mb.id_card_no as npwp_no, tro.*, mr.*, tv.*')
            ->select('(ss.ot_1 + ss.ot_2 + ss.ot_3 + ss.ot_4) AS ot_total')
            ->select('ss.emp_jp as empJp')
            ->select('ss.emp_jht as empJht')
            ->join('mt_biodata_01 mb', 'ss.biodata_id = mb.biodata_id')
            ->join('tr_timesheet mr', 'mb.biodata_id = mr.biodata_id')
            ->join('tr_overtime tro', 'mb.biodata_id = tro.bio_rec_id')
            ->join('tr_tax tv', 'tv.biodata_id = tro.bio_rec_id')
            ->join('mt_salary ms', 'ms.biodata_id = tro.bio_rec_id')
            ->where('ss.year_period', $year)
            ->where('ss.month_period', $month)
            ->where('ss.client_name', $clientName)
            ->where('tv.company_name', $clientName)
            // ->where('ms.company_name', $clientName) // kalau mau dipakai buka saja
        ;

        // WHERE COLUMN (CI4)
        $builder->where('ss.year_period = tro.year_period', null, false);
        $builder->where('ss.month_period = tro.month_period', null, false);
        $builder->where('ss.year_period = mr.year_process', null, false);
        $builder->where('ss.month_period = mr.month_process', null, false);
        $builder->where('tv.year = mr.year_process', null, false);
        $builder->where('tv.month = mr.month_process', null, false);

        // Filter dept jika tidak All
        if ($dataGroup !== 'All') {
            $builder->where('ss.dept', $dataGroup);
        }

        $builder->orderBy('ss.full_name', 'asc');

        $query = $builder->get();

        return $query->getResult();
    }

    public function getListByBiorecIdSP($clientName, $yearPeriod, $monthPeriod, $dataGroup)
    {
        $db = \Config\Database::connect(); // jika DB lain, ganti di sini
        $builder = $db->table('tr_slip a');

        // Query utama
        $builder->select('a.biodata_id, a.full_name, a.month_period');
        $builder->where('a.year_period', $yearPeriod);
        $builder->where('a.month_period <=', $monthPeriod);
        $builder->where('a.client_name', $clientName);

        if ($dataGroup !== 'All') {
            $builder->where('a.dept', $dataGroup);
        }

        $builder->groupBy('a.biodata_id');
        $builder->orderBy('a.full_name', 'ASC');

        // Eksekusi
        $query = $builder->get();
        $employees = $query->getResult();

        // ✓ Sorting manual seperti Laravel Collection::sortBy()
        usort($employees, function ($a, $b) {
            // Urut berdasarkan month_period, lalu name
            $cmp = strcmp($a->month_period, $b->month_period);
            return $cmp === 0 ? strcmp($a->full_name, $b->full_name) : $cmp;
        });

        // Ambil last query
        $lastQuery = (string) $db->getLastQuery();

        // Ambil error jika ada
        $dbError = $db->error();

        return $employees;
    }

    public function getListSPByBioRecId($biodataId, $clientName, $year, $month, $dataGroup)
    {
        // Connect CI4 database
        $db = \Config\Database::connect();
        $builder = $db->table('tr_slip as ss');

        $builder->select('ss.*,
        mb.biodata_id as biodata_id,
        ss.base_wage as salary_basic,
        mb.gender,
        mb.id_card_no,
        mb.current_address,
        mb.id_card_address,
        ss.bs_prorate,
        mb.id_card_no,
        tro.*,
        mr.*,
        tv.*
    ');

        $builder->select("(ss.ot_1 + ss.ot_2 + ss.ot_3 + ss.ot_4) AS ot_total", false);
        $builder->select("ss.emp_jp as empJp", false);
        $builder->select("ss.emp_jht as empJht", false);

        $builder->join('mt_biodata_01 as mb', 'ss.biodata_id = mb.biodata_id');
        $builder->join('tr_timesheet as mr', 'mb.biodata_id = mr.biodata_id');
        $builder->join('tr_overtime as tro', 'mb.biodata_id = tro.bio_rec_id');
        $builder->join('tr_tax as tv', 'tv.biodata_id = tro.bio_rec_id');
        $builder->join('mt_salary as ms', 'ms.biodata_id = tro.bio_rec_id');

        // MAIN WHERE
        $builder->where('ss.year_period', $year);
        $builder->where('ss.month_period', $month);
        $builder->where('ss.biodata_id', $biodataId);

        // CI4 TIDAK PUNYA whereColumn → gunakan raw
        $builder->where("ss.year_period = tro.year_period");
        $builder->where("ss.month_period = tro.month_period");
        $builder->where("ss.year_period = mr.year_process");
        $builder->where("ss.month_period = mr.month_process");
        $builder->where("tv.year = mr.year_process");
        $builder->where("tv.month = mr.month_process");

        $builder->where('ss.client_name', $clientName);
        $builder->where('tv.company_name', $clientName);
        // $builder->where('ms.company_name', $clientName);

        if ($dataGroup !== 'All') {
            $builder->where('ss.dept', $dataGroup);
        }

        $builder->orderBy('ss.client_name');
        $builder->orderBy('ss.year_period');
        $builder->orderBy('ss.month_period');
        $builder->orderBy('ss.full_name');

        // ===== EXECUTE QUERY ====
        $result = $builder->get()->getRow();

        // ===== LAST QUERY (CI4) =====
        $lastQuery = $db->getLastQuery();

        // ===== ERROR HANDLING =====
        $dbError = $db->error(); // array('code' => ?, 'message' => ?)

        return $result;
        // return [
        //     'data'      => $result,
        //     'lastQuery' => (string)$lastQuery,
        //     'error'     => $dbError
        // ];
    }

    public function getEmployeePayrollDetails($clientName, $yearPeriod, $monthPeriod, $dataGroup = 'All')
    {
        $db = \Config\Database::connect();

        $builder = $db->table('mt_salary ms');

        $builder->select("
        mb.biodata_id,
        mb.full_name,
        ms.biodata_id,
        ss.full_name,
        ss.slip_id,
        ss.position as job_desc,
        ss.base_wage,
        ss.bs_prorate,
        (ss.bs_prorate - ss.potongan_absensi) as current_salary,
        TRUNCATE((ss.base_wage / 173), 1) as rate,
        ss.normal_time,
        ss.ot_count1,
        ss.ot_count2,
        ss.ot_count3,
        ss.ot_count4,
        ss.ot_1,
        ss.ot_2,
        ss.ot_3,
        ss.ot_4,
        (ss.normal_time + ss.ot_count1 + ss.ot_count2 + ss.ot_count3 + ss.ot_count4) as worked_hours,
        CASE 
            WHEN (ss.normal_time + ss.ot_count1 + ss.ot_count2 + ss.ot_count3 + ss.ot_count4) <= 312   
            THEN TRUNCATE((ss.normal_time + ss.ot_count1 + ss.ot_count2 + ss.ot_count3 + ss.ot_count4) * TRUNCATE((ss.base_wage / 173), 1) * (64 / 100), 2)
            ELSE TRUNCATE(312 * TRUNCATE((ss.base_wage / 173), 1) * (64 / 100), 2)
        END as uplift,
        TRUNCATE((ss.normal_time) + (ss.ot_count1 * 1.5) + (ss.ot_count2 * 2) + (ss.ot_count3 * 3) + (ss.ot_count4 * 4), 1) as paid_hours,
        (ss.ot_1 + ss.ot_2 + ss.ot_3 + ss.ot_4) as ot_total,
        TRUNCATE((ss.ot_1 + ss.ot_2 + ss.ot_3 + ss.ot_4) * (35 / 100), 2) as ot_bonus,
        ss.potongan_absensi,
        ss.thr,
        ss.bpjs,
        ss.jkkjkm,
        ss.jht,
        ss.emp_jht
    ");

        $builder->join('tr_slip ss', 'ms.biodata_id = ss.biodata_id');
        $builder->join('mt_biodata_01 mb', 'ms.biodata_id = mb.biodata_id');

        $builder->where('mb.is_active', 1);
        $builder->where('ss.year_period', $yearPeriod);
        $builder->where('ss.month_period', $monthPeriod);

        $builder->where('ss.client_name', $clientName);
        // $builder->where('ms.company_name', $clientName);

        if ($dataGroup != 'All') {
            $builder->where('ss.dept', $dataGroup);
        }

        $builder->orderBy('ss.full_name');

        // Execute query
        $results = $builder->get()->getResult();

        // LAST QUERY
        $lastQuery = $db->getLastQuery()->getQuery();

        // DB ERROR (if any)
        $dbError = $db->error(); // ['code' => ..., 'message' => ...]

        // ===== ECHO OUTPUT =====
        // echo "<pre>";
        // echo "=== LAST QUERY ===\n";
        // echo $lastQuery . "\n\n";

        // echo "=== DB ERROR ===\n";
        // print_r($dbError);

        // echo "\n=== RESULT DATA ===\n";
        // print_r($results);
        // echo "</pre>";

        return $results;
    }

    public function getTakeHomePay($clientName, $biodataId, $yearPeriod, $monthPeriod, $salarySlipId, $allowanceData)
    {
        // Load model Tax (CI4)
        $mTax = new Tax();

        // Ambil data pajak
        $taxResults = $mTax->getTaxDataByBiodata($clientName, $biodataId, $yearPeriod, $monthPeriod);

        // Ambil data slip tanpa pajak
        $rowData = $this->getSlipDataWithoutTax($clientName, $salarySlipId);

        // Null safety
        $taxFinal     = $taxResults->tax_val  ?? 0;
        $bruttoTotal  = $taxResults->brutto   ?? 0;

        // BPJS & potongan lain
        $healthBpjs      = $rowData->bpjs;
        $jkkJkm          = $rowData->jkkjkm;
        $jht             = $rowData->jht;
        $empJht          = $rowData->emp_jht;
        $jp              = $rowData->jp;
        $empJp           = $rowData->emp_jp;
        $empHealthBpjs   = $rowData->emp_bpjs;

        // Allowances
        $workdayAdj          = $allowanceData['workday_adjustment'] ?? 0;
        $thrByUser           = $allowanceData['thr_by_user'] ?? 0;
        $contractBonusByUser = $allowanceData['othersBonusByUser'] ?? 0;
        $tBurden             = $allowanceData['debt_burden'] ?? 0;

        // Perhitungan THP
        $potongPajak = $bruttoTotal
            - $taxFinal
            - $jkkJkm
            - $empJht
            - $empHealthBpjs
            - $healthBpjs
            - $empJp;

        $sebelumPembulatan = round(
            $potongPajak
                + $tBurden
                + $thrByUser
                + $workdayAdj
                + $contractBonusByUser
        );

        // Helper pembulatan
        $pembulatanGaji = ConfigurationHelper::pembulatanTotal($sebelumPembulatan);

        $totalTerima = $sebelumPembulatan + $pembulatanGaji;

        return $totalTerima;
    }


    public function getAttendDataByBiodataId($biodataId, $clientName, $yearPeriod, $monthPeriod)
    {
        $db = \Config\Database::connect();

        $builder = $db->table('tr_overtime');

        $builder->select([
            'night_shift_count',
            'day_shift_count',
            'off_total',
            'emergency_total',
            'standby_total',
            'paid_vacation_total',
            'paid_permit_total',
            'permit_total',
            'sick_total',
            'alpa_total',
            'attend_total',
            'ph_total',
            'in_ph_total',
            'out_camp_total',
            'exp_camp_total',
            'bs_only_count',
            'vacation_days',
            'unpaid_days',
            'attend_in_off',
        ]);

        $builder->where('bio_rec_id', $biodataId);
        $builder->where('client_name', $clientName);
        $builder->where('year_period', $yearPeriod);
        $builder->where('month_period', $monthPeriod);

        $query = $builder->get();

        return $query->getRow(); // ambil 1 row
    }

    public function getInvoicePaymentList($clientName, $yearPeriod, $monthPeriod, $dataGroup)
    {
        // Koneksi DB (jika pakai group db_hris_sgt)
        $db = \Config\Database::connect();

        // Query builder
        $builder = $db->table('mt_salary ms')
            ->select('mb.biodata_id, mb.full_name, ms.biodata_id, mb.emp_position,
              b.bank_name, b.bank_code , b.bank_name,
                  ms.bank_id, ms.account_name, ms.account_no, 
                   ss.*, tv.brutto, tv.tax_val')

            ->join('mt_biodata_01 mb', 'ms.biodata_id = mb.biodata_id')
            ->join('tr_slip ss', 'mb.biodata_id = ss.biodata_id')
            ->join('tr_tax tv', 'tv.biodata_id = ss.biodata_id')
            ->join('mt_bank b', 'b.bank_id = ms.bank_id') // <== JOIN BANK
            ->where('ss.month_period', $monthPeriod)
            ->where('ss.year_period', $yearPeriod)
            ->where('tv.month', $monthPeriod)
            ->where('tv.year', $yearPeriod)
            ->where('mb.is_active', 1)
            ->where('ss.client_name', $clientName);

        if ($dataGroup !== 'All') {
            $builder->where('ss.dept', $dataGroup);
        }

        $builder->orderBy('mb.full_name', 'ASC');

        // Execute
        $query = $builder->get();
        $results = $query->getResult();

        // LAST QUERY
        $lastQuery = $db->getLastQuery()->getQuery();

        // // SQL ERROR
        // $dbError = $db->error(); // array ['code' => ..., 'message' => ...]
        // echo "<pre>";
        // print_r($results);        // hasil data
        // echo "\nLAST QUERY:\n" . $lastQuery;
        // echo "\nDB ERROR:\n";
        // print_r($dbError);
        // echo "</pre>";
        // exit();
        // RETURN SEMUA DATA
        return $results;
    }

    public function getListForTaxCalculation($yearPeriod, $clientName)
    {
        $db = \Config\Database::connect();

        $builder = $db->table('tr_slip a')
            ->select('a.biodata_id, a.client_name')
            ->where('a.year_period', $yearPeriod)
            ->where('a.client_name', $clientName);

        // Group + order
        $builder->groupBy('a.biodata_id');
        $builder->orderBy('a.full_name', 'ASC');

        return $builder->get()->getResult();
    }
    public function getListBySlipTaxCalcPeriod($yearPeriod, $bioRecId)
    {
        $db = \Config\Database::connect();

        $builder = $db->table('tr_slip a')
            ->select("
            a.year_period,
            a.month_period,
            a.full_name,
            a.client_name,
            a.check_final,
            a.is_end,
            a.marital_status,
            a.ot_1,
            a.ot_2,
            a.ot_3,
            a.ot_4,
            a.bs_prorate,
            a.biodata_id,
            a.bpjs,
            a.emp_bpjs,
            a.emp_jp,
            a.emp_jht,
            a.base_wage,
            a.potongan_absensi,
            a.jkkjkm,
            a.ptkp_total,
            b.biodata_id,
            c.bpjs_no,
            a.emp_jp AS empJp,
            a.emp_jht AS empJht,
            a.jkkjkm AS jamsostek,
            a.emp_bpjs AS bpjs_kes
        ")
            ->join('mt_salary b', 'a.biodata_id = b.biodata_id')
            ->join('mt_biodata_01 c', 'a.biodata_id = c.biodata_id')
            ->where('a.year_period', $yearPeriod);

        // Filter biodata
        if ($bioRecId != 0) {
            $builder->where('a.biodata_id', $bioRecId);
        }

        $builder->orderBy('a.biodata_id')
            ->orderBy('a.month_period');

        // 🔍 DEBUG 1: LIHAT RAW SQL QUERY
        // echo "<pre>RAW QUERY:\n";
        // echo $builder->getCompiledSelect();
        // echo "</pre>";

        // RESULT AS OBJECT
        $results = $builder->get()->getResult();

        // // 🔍 DEBUG 2: LIHAT HASIL QUERY
        // echo "<pre>RESULTS FROM DATABASE:\n";
        // var_dump($results);
        // echo "</pre>";

        // 12 bulan format 01..12
        $months = array_map(function ($m) {
            return str_pad($m, 2, '0', STR_PAD_LEFT);
        }, range(1, 12));

        // Group by full_name
        $grouped = [];
        foreach ($results as $row) {
            $grouped[$row->full_name][] = $row;
        }

        // 🔍 DEBUG 3: LIHAT GROUPING
        // echo "<pre>GROUPED DATA:\n";
        // var_dump($grouped);
        // echo "</pre>";

        $finalResults = [];

        foreach ($grouped as $name => $records) {

            foreach ($months as $month) {

                // cari data bulan
                $found = null;
                foreach ($records as $rec) {
                    if ($rec->month_period == $month) {
                        $found = $rec;
                        break;
                    }
                }

                // Jika tidak ada → dummy OBJECT
                if (!$found) {
                    $found = (object)[
                        'full_name'              => $name,
                        'month_period'           => $month,
                        'year_period'            => $yearPeriod,
                        'client_name'            => '',
                        'is_empty'               => true,
                        'nie'                    => '',
                        'bpjs_no'                => '',
                        'empJp'                  => 0,
                        'is_end'                 => 0,
                        'check_final'            => '',
                        'empJht'                 => 0,
                        'jamsostek'              => 0,
                        'marital_status'         => 0,
                        'biodata_id'             => $bioRecId,
                        'ot_1'                   => 0,
                        'ot_2'                   => 0,
                        'ot_3'                   => 0,
                        'ot_4'                   => 0,
                        'bpjs'                   => 0,
                        'emp_bpjs'               => 0,
                        'emp_jp'                 => 0,
                        'emp_jht'                => 0,
                        'base_wage'              => 0,
                        'bs_prorate'             => 0,
                        'potongan_absensi'       => 0,
                        'bs_prorate_month_before' => 0,
                        'bs_prorate_this_month'  => 0,
                        'unpaid_total'           => 0,
                        'jkkjkm'                 => 0,
                        'ptkp_total'             => 0,
                    ];
                }

                $finalResults[] = $found;
            }
        }

        // 🔍 DEBUG 4: FINAL OUTPUT
        // echo "<pre>FINAL RESULTS (12 bulan per nama):\n";
        // var_dump($finalResults);
        // echo "</pre>";

        // exit(); // supaya output terlihat dan proses berhenti

        return $finalResults;
    }

    public function getEndWork($biodataId, $yearPeriod, $monthPeriod)
    {
        $db = \Config\Database::connect();

        // 1️⃣ Cari bulan END terdekat (>= monthPeriod)
        $sqlEndTerdekat = "
        SELECT month FROM tr_tax
        WHERE year = ?
        AND month >= ?
        AND biodata_id = ?
        AND golongan = 'END'
        ORDER BY month ASC
        LIMIT 1
    ";

        $row = $db->query($sqlEndTerdekat, [$yearPeriod, $monthPeriod, $biodataId])->getRow();
        $bulanEndTerdekat = $row->month ?? null;

        // 2️⃣ Total bulan dalam periode
        $sqlTotalBulan = "
        SELECT COUNT(*) as total FROM tr_tax
        WHERE year = ?
        AND biodata_id = ?
    ";

        $row = $db->query($sqlTotalBulan, [$yearPeriod, $biodataId])->getRow();
        $totalBulanDalamPeriode = $row->total ?? 0;

        // 3️⃣ Bulan pertama dalam periode
        $sqlBulanPertama = "
        SELECT month FROM tr_tax
        WHERE year = ?
        AND biodata_id = ?
        ORDER BY month ASC
        LIMIT 1
    ";

        $row = $db->query($sqlBulanPertama, [$yearPeriod, $biodataId])->getRow();
        $bulanPertama = $row->month ?? 1;

        // 4️⃣ Cari bulan END terakhir (> monthPeriod)
        $sqlEndTerakhir = "
        SELECT month FROM tr_tax
        WHERE year = ?
        AND month > ?
        AND biodata_id = ?
        AND golongan = 'END'
        ORDER BY month DESC
        LIMIT 1
    ";

        $row = $db->query($sqlEndTerakhir, [$yearPeriod, $monthPeriod, $biodataId])->getRow();
        $bulanEndTerakhir = $row->month ?? null;

        // 5️⃣ Hitung jumlah bulan dalam periode
        $jumlahBulanDalamPeriode = 12 - ($bulanPertama - 1);

        // 6️⃣ Logika hasil
        return ($totalBulanDalamPeriode == $jumlahBulanDalamPeriode)
            ? $bulanEndTerakhir
            : $bulanEndTerdekat;
    }

    public function getStartWork($biodataId, $yearPeriod, $monthPeriod)
    {
        $db = \Config\Database::connect();

        // 1️⃣ Query bulan pertama yang ada datanya
        $sqlBulanPertama = "
        SELECT month FROM tr_tax
        WHERE biodata_id = ?
        AND year = ?
        ORDER BY month ASC
        LIMIT 1
    ";

        // 2️⃣ Cari bulan END terdekat sebelum monthPeriod
        $sqlBulanEND = "
        SELECT month FROM tr_tax
        WHERE year = ?
        AND month < ?
        AND biodata_id = ?
        AND golongan = 'END'
        ORDER BY month DESC
        LIMIT 1
    ";

        $rowEnd = $db->query($sqlBulanEND, [$yearPeriod, $monthPeriod, $biodataId])->getRow();
        $bulanEND = $rowEnd->month ?? null;

        // 3️⃣ Jika tidak ada END sama sekali → kembalikan bulan pertama
        if (is_null($bulanEND)) {
            $row = $db->query($sqlBulanPertama, [$biodataId, $yearPeriod])->getRow();
            return $row->month ?? null;
        }

        // 4️⃣ Cari bulan pertama setelah END
        $sqlStartKerja = "
        SELECT month FROM tr_tax
        WHERE biodata_id = ?
        AND year = ?
        AND month > ?
        ORDER BY month ASC
        LIMIT 1
    ";

        $rowStart = $db->query($sqlStartKerja, [$biodataId, $yearPeriod, $bulanEND])->getRow();
        $start_kerja = $rowStart->month ?? null;

        // 5️⃣ Cek apakah ada jeda bulan
        if ($start_kerja && ($start_kerja - $bulanEND) > 1) {
            return $start_kerja;
        }

        // 6️⃣ Jika tidak ada jeda → kembali ke bulan pertama
        $row = $db->query($sqlBulanPertama, [$biodataId, $yearPeriod])->getRow();
        return $row->month ?? null;
    }

    public function getCheckFinalEnd($clientName, $biodataId, $yearPeriod, $monthPeriod)
    {
        $db = \Config\Database::connect();

        $row = $db->table('tr_slip')
            ->select('is_end')
            ->where('biodata_id', $biodataId)
            ->where('client_name', $clientName)
            ->where('year_period', $yearPeriod)
            ->where('month_period', $monthPeriod)
            ->get()
            ->getRow();

        return $row->is_end ?? null;
    }
}
