<?php namespace App\Models\Transaction; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Aug 18, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_download extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = 'hris';
     protected $table = 'tr_timesheet';
     protected $primaryKey = 'ts_id';
     protected $returnType = 'array';
     protected $db = null;

     public function getAll()
     {
       $stQuery  = "SELECT  ".$this->table." WHERE is_active='1' order by biodata_id desc "; 
          $query   = $this->db->query($stQuery);
          return $query->getResultArray();
     }

}