<?php namespace App\Models\Master; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Feb 13, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_mt_salary extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = '';
     protected $table = 'mt_salary';
     protected $primaryKey = 'salary_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $salaryId;
     protected $biodataId;
     protected $idNo;
     protected $bankId;
     protected $monthly;
     protected $daily;
     protected $isActive;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
     	parent::__construct();
     	$this->db = \Config\Database::connect($this->DBGroup, false);
          $this->salaryId = '';
          $this->biodataId = '';
          $this->idNo = '';
          $this->bankId = '';
          $this->monthly = 0;
          $this->daily = 0;
          $this->isActive = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setSalaryId($aSalaryId)
     {
     	$this->salaryId = $aSalaryId;
     }
     public function getSalaryId()
     {
     	return $this->salaryId;
     }
     public function setBiodataId($aBiodataId)
     {
     	$this->biodataId = $aBiodataId;
     }
     public function getBiodataId()
     {
     	return $this->biodataId;
     }
     public function setIdNo($aIdNo)
     {
     	$this->idNo = $aIdNo;
     }
     public function getIdNo()
     {
     	return $this->idNo;
     }
     public function setBankId($aBankId)
     {
     	$this->bankId = $aBankId;
     }
     public function getBankId()
     {
     	return $this->bankId;
     }
     public function setMonthly($aMonthly)
     {
     	$this->monthly = $aMonthly;
     }
     public function getMonthly()
     {
     	return $this->monthly;
     }
     public function setDaily($aDaily)
     {
     	$this->daily = $aDaily;
     }
     public function getDaily()
     {
     	return $this->daily;
     }
     public function setIsActive($aIsActive)
     {
     	$this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
     	return $this->isActive;
     }
     public function setPicInput($aPicInput)
     {
     	$this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
     	return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
     	$this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
     	return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
     	$this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
     	return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
     	$this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
     	return $this->editTime;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
     	if($this->salaryId =="" || $this->salaryId == NULL) 
     	{
          	$this->salaryId = ''; 
     	}
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{
          	$this->biodataId = ''; 
     	}
     	if($this->idNo =="" || $this->idNo == NULL) 
     	{
          	$this->idNo = ''; 
     	}
     	if($this->bankId =="" || $this->bankId == NULL) 
     	{
          	$this->bankId = ''; 
     	}
     	if($this->monthly =="" || $this->monthly == NULL) 
     	{
          	$this->monthly = 0; 
     	}
     	if($this->daily =="" || $this->daily == NULL) 
     	{
          	$this->daily = 0; 
     	}
     	if($this->isActive =="" || $this->isActive == NULL) 
     	{
          	$this->isActive = 0; 
     	}
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{
          	$this->picInput = ''; 
     	}
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	}
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{
          	$this->picEdit = ''; 
     	}
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{
          	$this->editTime = '1700-01-01 00:00:00'; 
     	}

     	$stQuery  = "INSERT INTO ".$this->table." ";
     	$stQuery .= "( ";
     	$stQuery .=   "salary_id,"; 
     	$stQuery .=   "biodata_id,"; 
     	$stQuery .=   "id_no,"; 
     	$stQuery .=   "bank_id,"; 
     	$stQuery .=   "monthly,"; 
     	$stQuery .=   "daily,"; 
     	$stQuery .=   "is_active,"; 
     	$stQuery .=   "pic_input,"; 
     	$stQuery .=   "input_time,"; 
     	$stQuery .=   "pic_edit,"; 
     	$stQuery .=   "edit_time"; 
     	$stQuery .= ") "; 
     	$stQuery .= "VALUES "; 
     	$stQuery .= "( "; 
     	$stQuery .=   "'".$this->db->escapeString($this->salaryId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->idNo)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->bankId)."',";
     	$stQuery .=   " ".$this->monthly.",";
     	$stQuery .=   " ".$this->daily.",";
     	$stQuery .=   " ".$this->isActive.",";
     	$stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
     	$stQuery .= "); "; 
     	$this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START QUERY INSERT */
     public function getInsQuery()
     {
     	if($this->salaryId =="" || $this->salaryId == NULL) 
     	{
          	$this->salaryId = ''; 
     	}
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{
          	$this->biodataId = ''; 
     	}
     	if($this->idNo =="" || $this->idNo == NULL) 
     	{
          	$this->idNo = ''; 
     	}
     	if($this->bankId =="" || $this->bankId == NULL) 
     	{
          	$this->bankId = ''; 
     	}
     	if($this->monthly =="" || $this->monthly == NULL) 
     	{
          	$this->monthly = 0; 
     	}
     	if($this->daily =="" || $this->daily == NULL) 
     	{
          	$this->daily = 0; 
     	}
     	if($this->isActive =="" || $this->isActive == NULL) 
     	{
          	$this->isActive = 0; 
     	}
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{
          	$this->picInput = ''; 
     	}
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	}
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{
          	$this->picEdit = ''; 
     	}
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{
          	$this->editTime = '1700-01-01 00:00:00'; 
     	}

     	$stQuery  = "INSERT INTO ".$this->table." ";
     	$stQuery .= "( ";
     	$stQuery .=   "salary_id,"; 
     	$stQuery .=   "biodata_id,"; 
     	$stQuery .=   "id_no,"; 
     	$stQuery .=   "bank_id,"; 
     	$stQuery .=   "monthly,"; 
     	$stQuery .=   "daily,"; 
     	$stQuery .=   "is_active,"; 
     	$stQuery .=   "pic_input,"; 
     	$stQuery .=   "input_time,"; 
     	$stQuery .=   "pic_edit,"; 
     	$stQuery .=   "edit_time"; 
     	$stQuery .= ") "; 
     	$stQuery .= "VALUES "; 
     	$stQuery .= "( "; 
     	$stQuery .=   "'".$this->db->escapeString($this->salaryId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->idNo)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->bankId)."',";
     	$stQuery .=   " ".$this->monthly.",";
     	$stQuery .=   " ".$this->daily.",";
     	$stQuery .=   " ".$this->isActive.",";
     	$stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
     	$stQuery .= "); "; 
     	return $stQuery; 
     }
     /* END QUERY INSERT */
     /* START UPDATE */
     public function upd($id)
     {
     	if($this->salaryId =="" || $this->salaryId == NULL) 
     	{ 
          	$this->salaryId = ''; 
     	} 
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{ 
          	$this->biodataId = ''; 
     	} 
     	if($this->idNo =="" || $this->idNo == NULL) 
     	{ 
          	$this->idNo = ''; 
     	} 
     	if($this->bankId =="" || $this->bankId == NULL) 
     	{ 
          	$this->bankId = ''; 
     	} 
     	if($this->monthly =="" || $this->monthly == NULL) 
     	{ 
          	$this->monthly = 0; 
     	} 
     	if($this->daily =="" || $this->daily == NULL) 
     	{ 
          	$this->daily = 0; 
     	} 
     	if($this->isActive =="" || $this->isActive == NULL) 
     	{ 
          	$this->isActive = 0; 
     	} 
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{ 
          	$this->picInput = ''; 
     	} 
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{ 
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	} 
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{ 
          	$this->picEdit = ''; 
     	} 
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{ 
          	$this->editTime = '1700-01-01 00:00:00'; 
     	} 

     	$stQuery  = "UPDATE ".$this->table." "; 
     	$stQuery .= "SET "; 
     	$stQuery .=   "salary_id ='".$this->db->escapeString($this->salaryId)."', "; 
     	$stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
     	$stQuery .=   "id_no ='".$this->db->escapeString($this->idNo)."', "; 
     	$stQuery .=   "bank_id ='".$this->db->escapeString($this->bankId)."', "; 
     	$stQuery .=   'monthly ='.$this->monthly.','; 
     	$stQuery .=   'daily ='.$this->daily.','; 
     	$stQuery .=   'is_active ='.$this->isActive.','; 
     	$stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
     	$stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
     	$stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
     	$stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
     	$stQuery .= 'WHERE '; 
     	$stQuery .=   "salary_id = '".$this->db->escapeString($id)."'"; 
     	$this->db->query($stQuery); 
     }
     /* END UPDATE */
     /* START QUERY UPDATE */
     public function getUpdQuery($id)
     {
     	if($this->salaryId =="" || $this->salaryId == NULL) 
     	{ 
          	$this->salaryId = ''; 
     	} 
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{ 
          	$this->biodataId = ''; 
     	} 
     	if($this->idNo =="" || $this->idNo == NULL) 
     	{ 
          	$this->idNo = ''; 
     	} 
     	if($this->bankId =="" || $this->bankId == NULL) 
     	{ 
          	$this->bankId = ''; 
     	} 
     	if($this->monthly =="" || $this->monthly == NULL) 
     	{ 
          	$this->monthly = 0; 
     	} 
     	if($this->daily =="" || $this->daily == NULL) 
     	{ 
          	$this->daily = 0; 
     	} 
     	if($this->isActive =="" || $this->isActive == NULL) 
     	{ 
          	$this->isActive = 0; 
     	} 
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{ 
          	$this->picInput = ''; 
     	} 
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{ 
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	} 
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{ 
          	$this->picEdit = ''; 
     	} 
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{ 
          	$this->editTime = '1700-01-01 00:00:00'; 
     	} 

     	$stQuery  = "UPDATE ".$this->table." "; 
     	$stQuery .= "SET "; 
     	$stQuery .=   "salary_id ='".$this->db->escapeString($this->salaryId)."', "; 
     	$stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
     	$stQuery .=   "id_no ='".$this->db->escapeString($this->idNo)."', "; 
     	$stQuery .=   "bank_id ='".$this->db->escapeString($this->bankId)."', "; 
     	$stQuery .=   'monthly ='.$this->monthly.','; 
     	$stQuery .=   'daily ='.$this->daily.','; 
     	$stQuery .=   'is_active ='.$this->isActive.','; 
     	$stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
     	$stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
     	$stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
     	$stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
     	$stQuery .= 'WHERE '; 
     	$stQuery .=   "salary_id = '".$this->db->escapeString($id)."'"; 
     	return $stQuery; 
     }
     /* END QUERY UPDATE */
     /* START DELETE */
     public function del($id)
     {
     	$stQuery  = "DELETE FROM ".$this->table." ";      
     	$stQuery .= "WHERE salary_id = '".$this->db->escapeString($id)."'";
     	$db->query($stQuery); 
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
     	$stQuery  = "SELECT * FROM ".$this->table." "; 
     	$query  = $this->db->query($stQuery); 
     	$arrayList = $query->getResultArray(); 
     	return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
     	$stQuery  = "SELECT * FROM ".$this->table." ";     
     	$stQuery .= "WHERE salary_id = '".$this->db->escapeString($id)."'";
     	$query  = $this->db->query($stQuery); 
     	$arrayRow = $query->getRowArray(); 
     	return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
     	$stQuery  = "SELECT * FROM ".$this->table." "; 
     	$stQuery .= "WHERE salary_id = '".$this->db->escapeString($id)."'";
     	$query  = $this->db->query($stQuery); 
     	$arrayRow = $query->getRowArray(); 
     	$this->salaryId = $arrayRow['salary_id']; 
     	$this->biodataId = $arrayRow['biodata_id']; 
     	$this->idNo = $arrayRow['id_no']; 
     	$this->bankId = $arrayRow['bank_id']; 
     	$this->monthly = $arrayRow['monthly']; 
     	$this->daily = $arrayRow['daily']; 
     	$this->isActive = $arrayRow['is_active']; 
     	$this->picInput = $arrayRow['pic_input']; 
     	$this->inputTime = $arrayRow['input_time']; 
     	$this->picEdit = $arrayRow['pic_edit']; 
     	$this->editTime = $arrayRow['edit_time']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
     	$this->salaryId = ''; 
     	$this->biodataId = ''; 
     	$this->idNo = ''; 
     	$this->bankId = ''; 
     	$this->monthly = 0; 
     	$this->daily = 0; 
     	$this->isActive = 0; 
     	$this->picInput = ''; 
     	$this->inputTime = '1700-01-01 00:00:00'; 
     	$this->picEdit = ''; 
     	$this->editTime = '1700-01-01 00:00:00'; 
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
		$strSql = "SELECT ";
		$strSql .= " CASE WHEN id_year = curr_ym THEN ";
		$strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
		$strSql .= " ELSE ";
		$strSql .= "   CONCAT(curr_ym, '00001') ";
		$strSql .= " END AS doc_id ";
		$strSql .= "FROM ";
		$strSql .= " (SELECT ";
		$strSql .= "   MAX(".$columnId.") fi,";
		$strSql .= "   LEFT(".$columnId.",4) id_year,";
		$strSql .= "   current_date dt,";
		$strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
		$strSql .= "   CONCAT(";
		$strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
		$strSql .= "   LPAD(";
		$strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
		$strSql .= "    )";
		$strSql .= "   ) curr_ym,";
		$strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
		$strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
		$strSql .= " FROM ";
		$strSql .= "   ".$this->table." ";
		$strSql .= " GROUP BY ".$columnId.") a ";
		$strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
		$query  = $this->db->query($strSql); 
		$arrayRow = $query->getRowArray(); 
		if(!isset($arrayRow))
		{
			$curYM = date('ym');
			$arrayRow['doc_id'] = $curYM.'00001';
		}
		return $arrayRow;
     }
     /* END OF ID GENERATOR */
}
