<?php namespace App\Models\Master; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Feb 13, 2022                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class M_mt_biodata_02 extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = '';
     protected $table = 'mt_biodata_02';
     protected $primaryKey = 'education_id';
     protected $returnType = 'array';
     protected $db = null;

     protected $educationId;
     protected $biodataId;
     protected $schoolName;
     protected $educationYear;
     protected $major;
     protected $cityName;
     protected $isCertified;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
     	parent::__construct();
     	$this->db = \Config\Database::connect($this->DBGroup, false);
          $this->educationId = '';
          $this->biodataId = '';
          $this->schoolName = '';
          $this->educationYear = 0;
          $this->major = '';
          $this->cityName = '';
          $this->isCertified = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setEducationId($aEducationId)
     {
     	$this->educationId = $aEducationId;
     }
     public function getEducationId()
     {
     	return $this->educationId;
     }
     public function setBiodataId($aBiodataId)
     {
     	$this->biodataId = $aBiodataId;
     }
     public function getBiodataId()
     {
     	return $this->biodataId;
     }
     public function setSchoolName($aSchoolName)
     {
     	$this->schoolName = $aSchoolName;
     }
     public function getSchoolName()
     {
     	return $this->schoolName;
     }
     public function setEducationYear($aEducationYear)
     {
     	$this->educationYear = $aEducationYear;
     }
     public function getEducationYear()
     {
     	return $this->educationYear;
     }
     public function setMajor($aMajor)
     {
     	$this->major = $aMajor;
     }
     public function getMajor()
     {
     	return $this->major;
     }
     public function setCityName($aCityName)
     {
     	$this->cityName = $aCityName;
     }
     public function getCityName()
     {
     	return $this->cityName;
     }
     public function setIsCertified($aIsCertified)
     {
     	$this->isCertified = $aIsCertified;
     }
     public function getIsCertified()
     {
     	return $this->isCertified;
     }
     public function setPicInput($aPicInput)
     {
     	$this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
     	return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
     	$this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
     	return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
     	$this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
     	return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
     	$this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
     	return $this->editTime;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
     	if($this->educationId =="" || $this->educationId == NULL) 
     	{
          	$this->educationId = ''; 
     	}
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{
          	$this->biodataId = ''; 
     	}
     	if($this->schoolName =="" || $this->schoolName == NULL) 
     	{
          	$this->schoolName = ''; 
     	}
     	if($this->educationYear =="" || $this->educationYear == NULL) 
     	{
          	$this->educationYear = 0; 
     	}
     	if($this->major =="" || $this->major == NULL) 
     	{
          	$this->major = ''; 
     	}
     	if($this->cityName =="" || $this->cityName == NULL) 
     	{
          	$this->cityName = ''; 
     	}
     	if($this->isCertified =="" || $this->isCertified == NULL) 
     	{
          	$this->isCertified = 0; 
     	}
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{
          	$this->picInput = ''; 
     	}
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	}
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{
          	$this->picEdit = ''; 
     	}
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{
          	$this->editTime = '1700-01-01 00:00:00'; 
     	}

     	$stQuery  = "INSERT INTO ".$this->table." ";
     	$stQuery .= "( ";
     	$stQuery .=   "education_id,"; 
     	$stQuery .=   "biodata_id,"; 
     	$stQuery .=   "school_name,"; 
     	$stQuery .=   "education_year,"; 
     	$stQuery .=   "major,"; 
     	$stQuery .=   "city_name,"; 
     	$stQuery .=   "is_certified,"; 
     	$stQuery .=   "pic_input,"; 
     	$stQuery .=   "input_time,"; 
     	$stQuery .=   "pic_edit,"; 
     	$stQuery .=   "edit_time"; 
     	$stQuery .= ") "; 
     	$stQuery .= "VALUES "; 
     	$stQuery .= "( "; 
     	$stQuery .=   "'".$this->db->escapeString($this->educationId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->schoolName)."',";
     	$stQuery .=   " ".$this->educationYear.",";
     	$stQuery .=   "'".$this->db->escapeString($this->major)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->cityName)."',";
     	$stQuery .=   " ".$this->isCertified.",";
     	$stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
     	$stQuery .= "); "; 
     	$this->db->query($stQuery); 
     }
     /* END INSERT */
     /* START QUERY INSERT */
     public function getInsQuery()
     {
     	if($this->educationId =="" || $this->educationId == NULL) 
     	{
          	$this->educationId = ''; 
     	}
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{
          	$this->biodataId = ''; 
     	}
     	if($this->schoolName =="" || $this->schoolName == NULL) 
     	{
          	$this->schoolName = ''; 
     	}
     	if($this->educationYear =="" || $this->educationYear == NULL) 
     	{
          	$this->educationYear = 0; 
     	}
     	if($this->major =="" || $this->major == NULL) 
     	{
          	$this->major = ''; 
     	}
     	if($this->cityName =="" || $this->cityName == NULL) 
     	{
          	$this->cityName = ''; 
     	}
     	if($this->isCertified =="" || $this->isCertified == NULL) 
     	{
          	$this->isCertified = 0; 
     	}
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{
          	$this->picInput = ''; 
     	}
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	}
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{
          	$this->picEdit = ''; 
     	}
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{
          	$this->editTime = '1700-01-01 00:00:00'; 
     	}

     	$stQuery  = "INSERT INTO ".$this->table." ";
     	$stQuery .= "( ";
     	$stQuery .=   "education_id,"; 
     	$stQuery .=   "biodata_id,"; 
     	$stQuery .=   "school_name,"; 
     	$stQuery .=   "education_year,"; 
     	$stQuery .=   "major,"; 
     	$stQuery .=   "city_name,"; 
     	$stQuery .=   "is_certified,"; 
     	$stQuery .=   "pic_input,"; 
     	$stQuery .=   "input_time,"; 
     	$stQuery .=   "pic_edit,"; 
     	$stQuery .=   "edit_time"; 
     	$stQuery .= ") "; 
     	$stQuery .= "VALUES "; 
     	$stQuery .= "( "; 
     	$stQuery .=   "'".$this->db->escapeString($this->educationId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->biodataId)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->schoolName)."',";
     	$stQuery .=   " ".$this->educationYear.",";
     	$stQuery .=   "'".$this->db->escapeString($this->major)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->cityName)."',";
     	$stQuery .=   " ".$this->isCertified.",";
     	$stQuery .=   "'".$this->db->escapeString($this->picInput)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->inputTime)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->picEdit)."',";
     	$stQuery .=   "'".$this->db->escapeString($this->editTime)."'";
     	$stQuery .= "); "; 
     	return $stQuery; 
     }
     /* END QUERY INSERT */
     /* START UPDATE */
     public function upd($id)
     {
     	if($this->educationId =="" || $this->educationId == NULL) 
     	{ 
          	$this->educationId = ''; 
     	} 
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{ 
          	$this->biodataId = ''; 
     	} 
     	if($this->schoolName =="" || $this->schoolName == NULL) 
     	{ 
          	$this->schoolName = ''; 
     	} 
     	if($this->educationYear =="" || $this->educationYear == NULL) 
     	{ 
          	$this->educationYear = 0; 
     	} 
     	if($this->major =="" || $this->major == NULL) 
     	{ 
          	$this->major = ''; 
     	} 
     	if($this->cityName =="" || $this->cityName == NULL) 
     	{ 
          	$this->cityName = ''; 
     	} 
     	if($this->isCertified =="" || $this->isCertified == NULL) 
     	{ 
          	$this->isCertified = 0; 
     	} 
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{ 
          	$this->picInput = ''; 
     	} 
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{ 
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	} 
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{ 
          	$this->picEdit = ''; 
     	} 
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{ 
          	$this->editTime = '1700-01-01 00:00:00'; 
     	} 

     	$stQuery  = "UPDATE ".$this->table." "; 
     	$stQuery .= "SET "; 
     	$stQuery .=   "education_id ='".$this->db->escapeString($this->educationId)."', "; 
     	$stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
     	$stQuery .=   "school_name ='".$this->db->escapeString($this->schoolName)."', "; 
     	$stQuery .=   'education_year ='.$this->educationYear.','; 
     	$stQuery .=   "major ='".$this->db->escapeString($this->major)."', "; 
     	$stQuery .=   "city_name ='".$this->db->escapeString($this->cityName)."', "; 
     	$stQuery .=   'is_certified ='.$this->isCertified.','; 
     	$stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
     	$stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
     	$stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
     	$stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
     	$stQuery .= 'WHERE '; 
     	$stQuery .=   "education_id = '".$this->db->escapeString($id)."'"; 
     	$this->db->query($stQuery); 
     }
     /* END UPDATE */
     /* START QUERY UPDATE */
     public function getUpdQuery($id)
     {
     	if($this->educationId =="" || $this->educationId == NULL) 
     	{ 
          	$this->educationId = ''; 
     	} 
     	if($this->biodataId =="" || $this->biodataId == NULL) 
     	{ 
          	$this->biodataId = ''; 
     	} 
     	if($this->schoolName =="" || $this->schoolName == NULL) 
     	{ 
          	$this->schoolName = ''; 
     	} 
     	if($this->educationYear =="" || $this->educationYear == NULL) 
     	{ 
          	$this->educationYear = 0; 
     	} 
     	if($this->major =="" || $this->major == NULL) 
     	{ 
          	$this->major = ''; 
     	} 
     	if($this->cityName =="" || $this->cityName == NULL) 
     	{ 
          	$this->cityName = ''; 
     	} 
     	if($this->isCertified =="" || $this->isCertified == NULL) 
     	{ 
          	$this->isCertified = 0; 
     	} 
     	if($this->picInput =="" || $this->picInput == NULL) 
     	{ 
          	$this->picInput = ''; 
     	} 
     	if($this->inputTime =="" || $this->inputTime == NULL) 
     	{ 
          	$this->inputTime = '1700-01-01 00:00:00'; 
     	} 
     	if($this->picEdit =="" || $this->picEdit == NULL) 
     	{ 
          	$this->picEdit = ''; 
     	} 
     	if($this->editTime =="" || $this->editTime == NULL) 
     	{ 
          	$this->editTime = '1700-01-01 00:00:00'; 
     	} 

     	$stQuery  = "UPDATE ".$this->table." "; 
     	$stQuery .= "SET "; 
     	$stQuery .=   "education_id ='".$this->db->escapeString($this->educationId)."', "; 
     	$stQuery .=   "biodata_id ='".$this->db->escapeString($this->biodataId)."', "; 
     	$stQuery .=   "school_name ='".$this->db->escapeString($this->schoolName)."', "; 
     	$stQuery .=   'education_year ='.$this->educationYear.','; 
     	$stQuery .=   "major ='".$this->db->escapeString($this->major)."', "; 
     	$stQuery .=   "city_name ='".$this->db->escapeString($this->cityName)."', "; 
     	$stQuery .=   'is_certified ='.$this->isCertified.','; 
     	$stQuery .=   "pic_input ='".$this->db->escapeString($this->picInput)."', "; 
     	$stQuery .=   "input_time ='".$this->db->escapeString($this->inputTime)."', "; 
     	$stQuery .=   "pic_edit ='".$this->db->escapeString($this->picEdit)."', "; 
     	$stQuery .=   "edit_time ='".$this->db->escapeString($this->editTime)."' "; 
     	$stQuery .= 'WHERE '; 
     	$stQuery .=   "education_id = '".$this->db->escapeString($id)."'"; 
     	return $stQuery; 
     }
     /* END QUERY UPDATE */
     /* START DELETE */
     public function del($id)
     {
     	$stQuery  = "DELETE FROM ".$this->table." ";      
     	$stQuery .= "WHERE education_id = '".$this->db->escapeString($id)."'";
     	$db->query($stQuery); 
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
     	$stQuery  = "SELECT * FROM ".$this->table." "; 
     	$query  = $this->db->query($stQuery); 
     	$arrayList = $query->getResultArray(); 
     	return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
     	$stQuery  = "SELECT * FROM ".$this->table." ";     
     	$stQuery .= "WHERE education_id = '".$this->db->escapeString($id)."'";
     	$query  = $this->db->query($stQuery); 
     	$arrayRow = $query->getRowArray(); 
     	return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
     	$stQuery  = "SELECT * FROM ".$this->table." "; 
     	$stQuery .= "WHERE education_id = '".$this->db->escapeString($id)."'";
     	$query  = $this->db->query($stQuery); 
     	$arrayRow = $query->getRowArray(); 
     	$this->educationId = $arrayRow['education_id']; 
     	$this->biodataId = $arrayRow['biodata_id']; 
     	$this->schoolName = $arrayRow['school_name']; 
     	$this->educationYear = $arrayRow['education_year']; 
     	$this->major = $arrayRow['major']; 
     	$this->cityName = $arrayRow['city_name']; 
     	$this->isCertified = $arrayRow['is_certified']; 
     	$this->picInput = $arrayRow['pic_input']; 
     	$this->inputTime = $arrayRow['input_time']; 
     	$this->picEdit = $arrayRow['pic_edit']; 
     	$this->editTime = $arrayRow['edit_time']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
     	$this->educationId = ''; 
     	$this->biodataId = ''; 
     	$this->schoolName = ''; 
     	$this->educationYear = 0; 
     	$this->major = ''; 
     	$this->cityName = ''; 
     	$this->isCertified = 0; 
     	$this->picInput = ''; 
     	$this->inputTime = '1700-01-01 00:00:00'; 
     	$this->picEdit = ''; 
     	$this->editTime = '1700-01-01 00:00:00'; 
     }
     /* END OF RESET VALUES */
     /* START OF ID GENERATOR */
     public function generateId($columnId)
     {
		$strSql = "SELECT ";
		$strSql .= " CASE WHEN id_year = curr_ym THEN ";
		$strSql .= "   CONCAT(id_year,LPAD(CAST( (CAST(RIGHT(fi,5) AS INTEGER)+1) AS CHAR),5,'0')) ";
		$strSql .= " ELSE ";
		$strSql .= "   CONCAT(curr_ym, '00001') ";
		$strSql .= " END AS doc_id ";
		$strSql .= "FROM ";
		$strSql .= " (SELECT ";
		$strSql .= "   MAX(".$columnId.") fi,";
		$strSql .= "   LEFT(".$columnId.",4) id_year,";
		$strSql .= "   current_date dt,";
		$strSql .= "   RIGHT(".$columnId.", 5) curr_id,";
		$strSql .= "   CONCAT(";
		$strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2), ";
		$strSql .= "   LPAD(";
		$strSql .= "      CAST(DATE_FORMAT(NOW(), '%m') AS CHAR),2,'0'";
		$strSql .= "    )";
		$strSql .= "   ) curr_ym,";
		$strSql .= "   RIGHT(CAST(DATE_FORMAT(NOW(), '%y') AS CHAR),2) tYear,";
		$strSql .= "   CAST(DATE_FORMAT(NOW(), '%m') AS CHAR) tMonth ";
		$strSql .= " FROM ";
		$strSql .= "   ".$this->table." ";
		$strSql .= " GROUP BY ".$columnId.") a ";
		$strSql .= " ORDER BY doc_id DESC LIMIT 1 ";
		$query  = $this->db->query($strSql); 
		$arrayRow = $query->getRowArray(); 
		if(!isset($arrayRow))
		{
			$curYM = date('ym');
			$arrayRow['doc_id'] = $curYM.'00001';
		}
		return $arrayRow;
     }
     /* END OF ID GENERATOR */
}
