<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_biodata_04;

class Mt_biodata_04 extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../v_mt_biodata_04';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../ins_mt_biodata_04';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$mtBiodata04 = new M_mt_biodata_04();
          $data['mtBiodata04'] = $mtBiodata04->getById($skill_id);
          /* ***Using Valid Path */
          $data['actView'] = '../upd_mt_biodata_04';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$mtBiodata04 = new M_mt_biodata_04();
     	$mtBiodata04->resetValues();
     	$mtBiodata04->setSkillId($_POST['skillId']);
     	$mtBiodata04->setBiodataId($_POST['biodataId']);
     	$mtBiodata04->setSkill($_POST['skill']);
     	$mtBiodata04->setRemarks($_POST['remarks']);
     	$mtBiodata04->setPicInput($_POST['picInput']);
     	$mtBiodata04->setInputTime($_POST['inputTime']);
     	$mtBiodata04->setPicEdit($_POST['picEdit']);
     	$mtBiodata04->setEditTime($_POST['editTime']);
     	$mtBiodata04->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['skillId'];
     	$mtBiodata04 = new M_mt_biodata_04();
     	$mtBiodata04->setObjectById($id);
     	$mtBiodata04->setSkillId($_POST['skillId']);
     	$mtBiodata04->setBiodataId($_POST['biodataId']);
     	$mtBiodata04->setSkill($_POST['skill']);
     	$mtBiodata04->setRemarks($_POST['remarks']);
     	$mtBiodata04->setPicInput($_POST['picInput']);
     	$mtBiodata04->setInputTime($_POST['inputTime']);
     	$mtBiodata04->setPicEdit($_POST['picEdit']);
     	$mtBiodata04->setEditTime($_POST['editTime']);
     	$mtBiodata04->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtBiodata04 = new M_mt_biodata_04();
     	$id = $_POST['skillId'];
     	$mtBiodata04->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtBiodata04 = new M_mt_biodata_04();
     	$rs = $mtBiodata04->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
