<?php namespace App\Controllers\Master; 
/*********************************************************************
 *  Created By       : Generator Version 1.0.23                      *
 *  Created Date     : Feb 13, 2022                                 *
 *  Description      : All code generated by controller generator    *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Controller;
use App\Controllers\BaseController;
use App\Models\Master\M_mt_configuration;

class Mt_configuration extends BaseController
{
     /* START INDEX FUNCTION */
     public function index()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../v_mt_configuration';
         return view('home', $data);
     }
     /* END INDEX FUNCTION */
     /* START INPUT FUNCTION */
     public function ins_view()
     {
         /* ***Using Valid Path */
         $data['actView'] = '../ins_mt_configuration';
         return view('home', $data);
     }
     /* END INPUT FUNCTION */
     /* START UPDATE FUNCTION */
     public function upd_view()
     {
     	$mtConfiguration = new M_mt_configuration();
          $data['mtConfiguration'] = $mtConfiguration->getById($conf_id);
          /* ***Using Valid Path */
          $data['actView'] = '../upd_mt_configuration';
          return view('home', $data);
     }
     /* END UPDATE FUNCTION */
     /* START INSERT */
     public function ins()
     {
     	$mtConfiguration = new M_mt_configuration();
     	$mtConfiguration->resetValues();
     	$mtConfiguration->setConfId($_POST['confId']);
     	$mtConfiguration->setConfCode($_POST['confCode']);
     	$mtConfiguration->setConfName($_POST['confName']);
     	$mtConfiguration->setConfValue($_POST['confValue']);
     	$mtConfiguration->setRemarks($_POST['remarks']);
     	$mtConfiguration->ins();
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd()
     {
     	$id = $_POST['confId'];
     	$mtConfiguration = new M_mt_configuration();
     	$mtConfiguration->setObjectById($id);
     	$mtConfiguration->setConfId($_POST['confId']);
     	$mtConfiguration->setConfCode($_POST['confCode']);
     	$mtConfiguration->setConfName($_POST['confName']);
     	$mtConfiguration->setConfValue($_POST['confValue']);
     	$mtConfiguration->setRemarks($_POST['remarks']);
     	$mtConfiguration->upd($id);
     }
     /* END UPDATE */
     /* START DELETE */
     public function del()
     {
     	$mtConfiguration = new M_mt_configuration();
     	$id = $_POST['confId'];
     	$mtConfiguration->del($id);
     }
     /* END DELETE */
     /* START GET ALL */
     public function getAll()
     {
     	$mtConfiguration = new M_mt_configuration();
     	$rs = $mtConfiguration->getAll();
     	return json_encode($rs); 
     }
     /* END GET ALL */
}
?>
