<?php namespace App\Models\Admin; 
/*********************************************************************
 *  Created By       :  Generator Version 1.0.23                     *
 *  Created Date     :  Jul 02, 2020                                 *
 *  Description      : All code generated by model generator         *
 *  Generator Author : Tommy Maurice(tommy_maurice@yahoo.com)        *
 *********************************************************************/
use CodeIgniter\Model;

class UserModel extends Model
{
     /* START PRIVATE VARIABLES */
     protected $DBGroup = 'hris';
     protected $table = 'mst_user';
     protected $primaryKey = 'user_name';
     protected $returnType = 'array';
     protected $db = null;

     protected $userId;
     protected $nip;
     protected $fullName;
     protected $userName;
     protected $userPassword;
     protected $phoneImei;
     protected $userLevel;
     protected $lastLogin;
     protected $lastIp;
     protected $isActive;
     protected $picInput;
     protected $inputTime;
     protected $picEdit;
     protected $editTime;
     protected $userGroup;
     /* END PRIVATE VARIABLES */
     /* START CONSTRUCTOR */ 
     public function __construct()
     {
        parent::__construct();
          $this->userId = '';
          $this->nip = '';
          $this->fullName = '';
          $this->userName = '';
          $this->userPassword = '';
          $this->phoneImei = '';
          $this->userLevel = 0;
          $this->lastLogin = '1700-01-01 00:00:00';
          $this->lastIp = '';
          $this->isActive = 0;
          $this->picInput = '';
          $this->inputTime = '1700-01-01 00:00:00';
          $this->picEdit = '';
          $this->editTime = '1700-01-01 00:00:00';
          $this->userGroup = '';
     }
     /* END CONSTRUCTOR */
     
     /* START GENERATE SETTER AND GETTER */
     public function setUserId($aUserId)
     {
        $this->userId = $aUserId;
     }
     public function getUserId()
     {
        return $this->userId;
     }
     public function setNip($aNip)
     {
        $this->nip = $aNip;
     }
     public function getNip()
     {
        return $this->nip;
     }
     public function setFullName($aFullName)
     {
        $this->fullName = $aFullName;
     }
     public function getFullName()
     {
        return $this->fullName;
     }
     public function setUserName($aUserName)
     {
        $this->userName = $aUserName;
     }
     public function getUserName()
     {
        return $this->userName;
     }
     public function setUserPassword($aUserPassword)
     {
        $this->userPassword = $aUserPassword;
     }
     public function getUserPassword()
     {
        return $this->userPassword;
     }
     public function setPhoneImei($aPhoneImei)
     {
        $this->phoneImei = $aPhoneImei;
     }
     public function getPhoneImei()
     {
        return $this->phoneImei;
     }
     public function setUserLevel($aUserLevel)
     {
        $this->userLevel = $aUserLevel;
     }
     public function getUserLevel()
     {
        return $this->userLevel;
     }
     public function setLastLogin($aLastLogin)
     {
        $this->lastLogin = $aLastLogin;
     }
     public function getLastLogin()
     {
        return $this->lastLogin;
     }
     public function setLastIp($aLastIp)
     {
        $this->lastIp = $aLastIp;
     }
     public function getLastIp()
     {
        return $this->lastIp;
     }
     public function setIsActive($aIsActive)
     {
        $this->isActive = $aIsActive;
     }
     public function getIsActive()
     {
        return $this->isActive;
     }
     public function setPicInput($aPicInput)
     {
        $this->picInput = $aPicInput;
     }
     public function getPicInput()
     {
        return $this->picInput;
     }
     public function setInputTime($aInputTime)
     {
        $this->inputTime = $aInputTime;
     }
     public function getInputTime()
     {
        return $this->inputTime;
     }
     public function setPicEdit($aPicEdit)
     {
        $this->picEdit = $aPicEdit;
     }
     public function getPicEdit()
     {
        return $this->picEdit;
     }
     public function setEditTime($aEditTime)
     {
        $this->editTime = $aEditTime;
     }
     public function getEditTime()
     {
        return $this->editTime;
     }
     public function setUserGroup($aUserGroup)
     {
        $this->userGroup = $aUserGroup;
     }
     public function getUserGroup()
     {
        return $this->userGroup;
     }
     /* END GENERATE SETTER AND GETTER */
     /* START INSERT */
     public function ins()
     {
        if($this->userId =="" || $this->userId == NULL) 
        {
            $this->userId = ''; 
        }
        if($this->nip =="" || $this->nip == NULL) 
        {
            $this->nip = ''; 
        }
        if($this->fullName =="" || $this->fullName == NULL) 
        {
            $this->fullName = ''; 
        }
        if($this->userName =="" || $this->userName == NULL) 
        {
            $this->userName = ''; 
        }
        if($this->userPassword =="" || $this->userPassword == NULL) 
        {
            $this->userPassword = ''; 
        }
        if($this->phoneImei =="" || $this->phoneImei == NULL) 
        {
            $this->phoneImei = ''; 
        }
        if($this->userLevel =="" || $this->userLevel == NULL) 
        {
            $this->userLevel = 0; 
        }
        if($this->lastLogin =="" || $this->lastLogin == NULL) 
        {
            $this->lastLogin = '1700-01-01 00:00:00'; 
        }
        if($this->lastIp =="" || $this->lastIp == NULL) 
        {
            $this->lastIp = ''; 
        }
        if($this->isActive =="" || $this->isActive == NULL) 
        {
            $this->isActive = 0; 
        }
        if($this->picInput =="" || $this->picInput == NULL) 
        {
            $this->picInput = ''; 
        }
        if($this->inputTime =="" || $this->inputTime == NULL) 
        {
            $this->inputTime = '1700-01-01 00:00:00'; 
        }
        if($this->picEdit =="" || $this->picEdit == NULL) 
        {
            $this->picEdit = ''; 
        }
        if($this->editTime =="" || $this->editTime == NULL) 
        {
            $this->editTime = '1700-01-01 00:00:00'; 
        }
        if($this->userGroup =="" || $this->userGroup == NULL) 
        {
            $this->userGroup = ''; 
        }

        $db = \Config\Database::connect($this->DBGroup);
        $stQuery  = "INSERT INTO ".$this->table." ";
        $stQuery .= "( ";
        $stQuery .=   "user_id,"; 
        $stQuery .=   "nip,"; 
        $stQuery .=   "full_name,"; 
        $stQuery .=   "user_name,"; 
        $stQuery .=   "user_password,"; 
        $stQuery .=   "phone_imei,"; 
        $stQuery .=   "user_level,"; 
        $stQuery .=   "last_login,"; 
        $stQuery .=   "last_ip,"; 
        $stQuery .=   "is_active,"; 
        $stQuery .=   "pic_input,"; 
        $stQuery .=   "input_time,"; 
        $stQuery .=   "pic_edit,"; 
        $stQuery .=   "edit_time,"; 
        $stQuery .=   "user_group,"; 
        $stQuery .= ") "; 
        $stQuery .= "VALUES "; 
        $stQuery .= "( "; 
        $stQuery .=   "'".$db->escapeString($this->userId)."',";
        $stQuery .=   "'".$db->escapeString($this->nip)."',";
        $stQuery .=   "'".$db->escapeString($this->fullName)."',";
        $stQuery .=   "'".$db->escapeString($this->userName)."',";
        $stQuery .=   "'".$db->escapeString($this->userPassword)."',";
        $stQuery .=   "'".$db->escapeString($this->phoneImei)."',";
        $stQuery .=   "".$db->escapeString($this->userLevel).",";
        $stQuery .=   "'".$db->escapeString($this->lastLogin)."',";
        $stQuery .=   "'".$db->escapeString($this->lastIp)."',";
        $stQuery .=   "".$db->escapeString($this->isActive).",";
        $stQuery .=   "'".$db->escapeString($this->picInput)."',";
        $stQuery .=   "'".$db->escapeString($this->inputTime)."',";
        $stQuery .=   "'".$db->escapeString($this->picEdit)."',";
        $stQuery .=   "'".$db->escapeString($this->editTime)."',";
        $stQuery .=   "'".$db->escapeString($this->userGroup)."'";
        $stQuery .= "); "; 
        $db->query($stQuery); 
     }
     /* END INSERT */
     /* START UPDATE */
     public function upd($id)
     {
        if($this->userId =="" || $this->userId == NULL) 
        { 
            $this->userId = ''; 
        } 
        if($this->nip =="" || $this->nip == NULL) 
        { 
            $this->nip = ''; 
        } 
        if($this->fullName =="" || $this->fullName == NULL) 
        { 
            $this->fullName = ''; 
        } 
        if($this->userName =="" || $this->userName == NULL) 
        { 
            $this->userName = ''; 
        } 
        if($this->userPassword =="" || $this->userPassword == NULL) 
        { 
            $this->userPassword = ''; 
        } 
        if($this->phoneImei =="" || $this->phoneImei == NULL) 
        { 
            $this->phoneImei = ''; 
        } 
        if($this->userLevel =="" || $this->userLevel == NULL) 
        { 
            $this->userLevel = 0; 
        } 
        if($this->lastLogin =="" || $this->lastLogin == NULL) 
        { 
            $this->lastLogin = '1700-01-01 00:00:00'; 
        } 
        if($this->lastIp =="" || $this->lastIp == NULL) 
        { 
            $this->lastIp = ''; 
        } 
        if($this->isActive =="" || $this->isActive == NULL) 
        { 
            $this->isActive = 0; 
        } 
        if($this->picInput =="" || $this->picInput == NULL) 
        { 
            $this->picInput = ''; 
        } 
        if($this->inputTime =="" || $this->inputTime == NULL) 
        { 
            $this->inputTime = '1700-01-01 00:00:00'; 
        } 
        if($this->picEdit =="" || $this->picEdit == NULL) 
        { 
            $this->picEdit = ''; 
        } 
        if($this->editTime =="" || $this->editTime == NULL) 
        { 
            $this->editTime = '1700-01-01 00:00:00'; 
        } 
        if($this->userGroup =="" || $this->userGroup == NULL) 
        { 
            $this->userGroup = ''; 
        } 

        $db = \Config\Database::connect($this->DBGroup); 
        $stQuery  = "UPDATE ".$this->table." "; 
        $stQuery .= "SET "; 
        $stQuery .=   "user_id ='".$db->escapeString($this->userId)."', "; 
        $stQuery .=   "nip ='".$db->escapeString($this->nip)."', "; 
        $stQuery .=   "full_name ='".$db->escapeString($this->fullName)."', "; 
        $stQuery .=   "user_name ='".$db->escapeString($this->userName)."', "; 
        $stQuery .=   "user_password ='".$db->escapeString($this->userPassword)."', "; 
        $stQuery .=   "phone_imei ='".$db->escapeString($this->phoneImei)."', "; 
        $stQuery .=   'user_level ='.$db->escapeString($this->userLevel).','; 
        $stQuery .=   "last_login ='".$db->escapeString($this->lastLogin)."', "; 
        $stQuery .=   "last_ip ='".$db->escapeString($this->lastIp)."', "; 
        $stQuery .=   'is_active ='.$db->escapeString($this->isActive).','; 
        $stQuery .=   "pic_input ='".$db->escapeString($this->picInput)."', "; 
        $stQuery .=   "input_time ='".$db->escapeString($this->inputTime)."', "; 
        $stQuery .=   "pic_edit ='".$db->escapeString($this->picEdit)."', "; 
        $stQuery .=   "edit_time ='".$db->escapeString($this->editTime)."', "; 
        $stQuery .=   "user_group ='".$db->escapeString($this->userGroup)."' "; 
        $stQuery .= 'WHERE '; 
        $stQuery .=   "user_id = '".$db->escapeString($id)."'"; 
        $db->query($stQuery); 
     }
     /* END UPDATE */
     /* START DELETE */
     public function del($id)
     {
        $db = \Config\Database::connect($this->DBGroup); 
        $stQuery  = "DELETE FROM ".$this->table." ";      
        $stQuery .= "WHERE user_id = '".$db->escapeString($id)."'";
        $db->query($stQuery); 
     }
     /* END DELETE */
     /* START GET ALL DATA */
     public function getAll()
     {
        $db = \Config\Database::connect($this->DBGroup); 
        $stQuery  = "SELECT * FROM ".$this->table." "; 
        $query  = $db->query($stQuery); 
        $arrayList = $query->getResultArray(); 
        return $arrayList; 
     }
     /* END GET ALL DATA */
     /* START GET DATA BY ID */
     public function getById($id)
     {
        $db = \Config\Database::connect($this->DBGroup); 
        $stQuery  = "SELECT * FROM ".$this->table." ";     
        $stQuery .= "WHERE  = '".$db->escapeString($id)."'";
        $query  = $db->query($stQuery); 
        $arrayRow = $query->getRowArray(); 
        return $arrayRow; 
     }
     /* END GET DATA BY ID */
     /* START GET OBJECT DATA BY ID */
     public function setObjectById($id)
     {
        $db = \Config\Database::connect($this->DBGroup); 
        $stQuery  = "SELECT * FROM ".$this->table." "; 
        $stQuery .= "WHERE user_id = '".$db->escapeString($id)."'";
        $query  = $db->query($stQuery); 
        $arrayRow = $query->getRowArray(); 
        $this->userId = $arrayRow['user_id']; 
        $this->nip = $arrayRow['nip']; 
        $this->fullName = $arrayRow['full_name']; 
        $this->userName = $arrayRow['user_name']; 
        $this->userPassword = $arrayRow['user_password']; 
        $this->phoneImei = $arrayRow['phone_imei']; 
        $this->userLevel = $arrayRow['user_level']; 
        $this->lastLogin = $arrayRow['last_login']; 
        $this->lastIp = $arrayRow['last_ip']; 
        $this->isActive = $arrayRow['is_active']; 
        $this->picInput = $arrayRow['pic_input']; 
        $this->inputTime = $arrayRow['input_time']; 
        $this->picEdit = $arrayRow['pic_edit']; 
        $this->editTime = $arrayRow['edit_time']; 
        $this->userGroup = $arrayRow['user_group']; 
     }
     /* END GET OBJECT DATA BY ID */
     /* START OF RESET VALUES */
     public function resetValues()
     {
        $this->userId = ''; 
        $this->nip = ''; 
        $this->fullName = ''; 
        $this->userName = ''; 
        $this->userPassword = ''; 
        $this->phoneImei = ''; 
        $this->lastLogin = '1700-01-01 00:00:00'; 
        $this->lastIp = ''; 
        $this->picInput = ''; 
        $this->inputTime = '1700-01-01 00:00:00'; 
        $this->picEdit = ''; 
        $this->editTime = '1700-01-01 00:00:00'; 
        $this->userGroup = ''; 
     }
     /* END OF RESET VALUES */
}
?>
